// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("esri/request dojo/json dojo/topic dojo/_base/lang esri/arcgis/Portal esri/layers/FeatureLayer jimu/LayerInfos/LayerInfos jimu/utils".split(" "),function(f,h,c,e,n,l,m,k){return{saveToPortal:function(a){(new n.Portal(a.appConfig.portalUrl)).signIn().then(e.hitch(this,function(b){var g=b.credential.token,d=b.orgId,f=b.username;if("org_user"===b.role)a.publishMessage.innerHTML=k.sanitizeHTML(a.nls.createService.format(a.nls.userRole)),c.publish("setLastFocusNode",!1);else if(a.url)b=new l(a.url+
"?token\x3d"+g,{id:a.layerName,outFields:["*"]}),b._wabProperties={itemLayerInfo:{portalUrl:a.appConfig.portalUrl,itemId:a.itemId}},b.applyEdits(a.graphics,null,null).then(e.hitch(this,function(){c.publish("clear")})).otherwise(e.hitch(this,function(){c.publish("clear")})),c.publish("setBusyIndicator",!1),a.publishMessage.innerHTML=a.nls.successfullyAppended+('\x3cbr /\x3e\x3ca role\x3d"link" tabindex\x3d"0" aria-label\x3d"'+a.nls.successfullyAppended+'" href\x3d"'+a.appConfig.portalUrl+"home/item.html?id\x3d"+
a.serviceItemId+'" target\x3d"_blank"\x3e'+a.nls.manageWebLayerText+"\x3c/a\x3e"),c.publish("setLastFocusNode",!0);else{var h=a.appConfig.portalUrl+"sharing/content/users/"+f+"/createService";this.isNameAvailable(a.appConfig.portalUrl+"sharing/rest/portals/"+d+"/isServiceNameAvailable",g,a.layerName).then(e.hitch(this,function(b){b.available?(c.publish("setBusyIndicator",!0),this.createFeatureService(h,g,this.getFeatureServiceParams(a.layerName,a.map)).then(e.hitch(this,function(b){if(b.success){var d=
b.serviceurl.replace(/rest/g,"rest/admin")+"/addToDefinition";this.addDefinitionToService(d,g,this.getLayerParams(a.layerName,a.map,a.renderer,a.nls)).then(e.hitch(this,function(d){if(d.success){d=new l(b.serviceurl+"/0?token\x3d"+g,{id:a.layerName,outFields:["*"]});d._wabProperties={itemLayerInfo:{portalUrl:a.appConfig.portalUrl,itemId:b.itemId}};a.map.addLayer(d);var f;if(d.loaded)f=m.getInstanceSync().getLayerInfoById(a.layerName),f.enablePopup();else d.on("load",e.hitch(this,function(){f=m.getInstanceSync().getLayerInfoById(a.layerName);
f.enablePopup()}));d.applyEdits(a.graphics,null,null).then(e.hitch(this,function(){c.publish("clear")})).otherwise(e.hitch(this,function(){c.publish("clear")}));c.publish("setBusyIndicator",!1);a.publishMessage.innerHTML=a.nls.successfullyPublished+('\x3cbr /\x3e\x3ca role\x3d"link" tabindex\x3d"0" aria-label\x3d"'+a.nls.successfullyPublished+'" href\x3d"'+a.appConfig.portalUrl+"home/item.html?id\x3d"+b.itemId+'" target\x3d"_blank"\x3e'+a.nls.manageWebLayerText+"\x3c/a\x3e");c.publish("setLastFocusNode",
!0)}}),e.hitch(this,function(b){c.publish("setBusyIndicator",!1);a.publishMessage.innerHTML=k.sanitizeHTML(a.nls.addToDefinition.format(b.message));c.publish("setLastFocusNode",!1)}))}else c.publish("setBusyIndicator",!1),a.publishMessage.innerHTML=k.sanitizeHTML(a.nls.unableToCreate.format(a.layerName)),c.publish("setLastFocusNode",!1)}),e.hitch(this,function(b){c.publish("setBusyIndicator",!1);a.publishMessage.innerHTML=k.sanitizeHTML(a.nls.createService.format(b.message));c.publish("setLastFocusNode",
!1)}))):(c.publish("setBusyIndicator",!1),a.publishMessage.innerHTML=a.nls.layerNameExists);c.publish("setLastFocusNode",!1)}))}}),e.hitch(this,function(b){a.publishMessage.innerHTML=b.message;c.publish("setLastFocusNode",!1)}))},getFeatureServiceParams:function(a,b){return{name:a,serviceDescription:"",hasStaticData:!1,maxRecordCount:1E3,supportedQueryFormats:"JSON",capabilities:"Create,Delete,Query,Update,Editing",tags:"ThreatAnalysis",description:"",copyrightText:"",spatialReference:{wkid:102100},
initialExtent:{xmin:b.extent.xmin,ymin:b.extent.ymin,xmax:b.extent.xmax,ymax:b.extent.ymax,spatialReference:{wkid:102100}},allowGeometryUpdates:!0,units:"esriMeters",xssPreventionInfo:{xssPreventionEnabled:!0,xssPreventionRule:"InputOnly",xssInputRule:"rejectInvalid"}}},getLayerParams:function(a,b,c,d){return{layers:[{adminLayerInfo:{geometryField:{name:"Shape"},xssTrustedFields:""},id:0,name:a,type:"Feature Layer",displayField:"",description:"",tags:"ThreatAnalysis",copyrightText:"",defaultVisibility:!0,
ownershipBasedAccessControlForFeatures:{allowOthersToQuery:!1,allowOthersToDelete:!1,allowOthersToUpdate:!1},relationships:[],isDataVersioned:!1,supportsCalculate:!0,supportsAttachmentsByUploadId:!0,supportsRollbackOnFailureParameter:!0,supportsStatistics:!0,supportsAdvancedQueries:!0,supportsValidateSql:!0,supportsCoordinatesQuantization:!0,supportsApplyEditsWithGlobalIds:!0,advancedQueryCapabilities:{supportsPagination:!0,supportsQueryWithDistance:!0,supportsReturningQueryExtent:!0,supportsStatistics:!0,
supportsOrderBy:!0,supportsDistinct:!0,supportsQueryWithResultType:!0,supportsSqlExpression:!0,supportsReturningGeometryCentroid:!0},useStandardizedQueries:!1,geometryType:"esriGeometryPolygon",minScale:0,maxScale:0,extent:b.extent,drawingInfo:{renderer:c.toJson(),transparency:0},allowGeometryUpdates:!0,hasAttachments:!1,htmlPopupType:"esriServerHTMLPopupTypeNone",hasM:!1,hasZ:!1,objectIdField:"OBJECTID",globalIdField:"",typeIdField:"",fields:[{name:"OBJECTID",type:"esriFieldTypeOID",actualType:"int",
alias:"OBJECTID",sqlType:"sqlTypeOther",nullable:!1,editable:!1,domain:null,defaultValue:null},{name:"zone_type",type:"esriFieldTypeString",alias:d.zoneTypeLabel,actualType:"nvarchar",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeNVarchar",length:256},{name:"threat_type",type:"esriFieldTypeString",alias:d.threatType,actualType:"nvarchar",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeNVarchar",length:256},{name:"mandatory_dist",type:"esriFieldTypeDouble",
alias:d.mandatoryLabel,actualType:"float",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeFloat"},{name:"safe_dist",type:"esriFieldTypeDouble",alias:d.safeLabel,actualType:"float",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeFloat"},{name:"lpg_fireball_dia",type:"esriFieldTypeDouble",alias:d.fireBallDiameterFieldAlias,actualType:"float",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeFloat"},{name:"lpg_safe_dist",type:"esriFieldTypeDouble",
alias:d.lpgSafeDistanceFieldAlias,actualType:"float",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeFloat"},{name:"units",type:"esriFieldTypeString",alias:d.unitsLabel,actualType:"nvarchar",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeNVarchar",length:256}],indexes:[],types:[],templates:[{name:"New Feature",description:"",drawingTool:"esriFeatureEditToolPolygon",prototype:{attributes:{type:""}}}],supportedQueryFormats:"JSON",hasStaticData:!1,maxRecordCount:1E4,
standardMaxRecordCount:4E3,tileMaxRecordCount:4E3,maxRecordCountFactor:1,exceedsLimitFactor:1,capabilities:"Query,Editing,Create,Update,Delete"}]}},isNameAvailable:function(a,b,c){return f({url:a,content:{name:c,type:"Feature Service",token:b,f:"json"},handleAs:"json",callbackParamName:"callback"},{usePost:!0})},createFeatureService:function(a,b,c){return f({url:a,content:{f:"json",token:b,typeKeywords:"ArcGIS Server,Data,Feature Access,Feature Service,Service,Hosted Service",createParameters:h.stringify(c),
outputType:"featureService"},handleAs:"json",callbackParamName:"callback"},{usePost:!0})},addDefinitionToService:function(a,b,c){return f({url:a,content:{token:b,addToDefinition:h.stringify(c),f:"json"},handleAs:"json",callbackParamName:"callback"},{usePost:!0})}}});