// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/_base/array dojo/DeferredList dojo/Deferred dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/on dojo/keys jimu/utils jimu/dijit/Message esri/graphic esri/layers/FeatureLayer esri/tasks/query ./analysisUtils".split(" "),function(C,D,z,u,v,p,q,r,x,y,w,A,E,t,B,n){return C("GroupedCountInfo",[D],{summaryLayer:null,summaryFields:[],summaryIds:[],summaryFeatures:[],tabNum:null,popupFields:[],groupedResults:{},specialFields:null,dateFields:{},symbolField:null,
graphicsLayer:null,lyrRenderer:null,lyrSymbol:null,featureCount:0,incidentCount:0,displayCount:!1,allFields:!1,configuredPopUpFields:[],constructor:function(a,d,c){this.tab=a;this.container=d;this.parent=c;this.config=c.config;this.graphicsLayer=null;this.specialFields={};this.typeIdField="";this.types=[];this.dateFields={};this.baseLabel=""!==a.label?a.label:a.layerTitle?a.layerTitle:a.layers;this.parentNode=c.domNode},queryTabCount:function(a,d,c,g){var e=new v;this.displayCount=g;this.incidentCount=
a.length;var f=[this.tab.tabLayers[0]];this.mapServiceLayer&&1<this.tab.tabLayers.length&&(f=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer")){this.mapServiceLayer=!0;var b;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],this.summaryLayer.hasOwnProperty("loaded")&&this.summaryLayer.loaded?(this.summaryFields=this._getFields(this.summaryLayer),this._performQuery(a,d,
c,g,f).then(function(a){e.resolve(a)})):(b=new t(this.summaryLayer.url),b.infoTemplate=this.tab.tabLayers[0].infoTemplate,f=[b],this.tab.tabLayers=f,x(b,"load",p.hitch(this,function(){this.summaryLayer=b;this.summaryFields=this._getFields(this.summaryLayer);this._performQuery(a,d,c,g,f).then(function(a){e.resolve(a)})})))):this.loading||(b=new t(this.tab.tabLayers[0].url),this.loading=!0,x(b,"load",p.hitch(this,function(){this.summaryLayer=b;this.summaryFields=this._getFields(this.summaryLayer);for(var k=
this.tab.tabLayers[0].url.split("MapServer/")[1],m=this.parent.map.itemInfo.itemData.operationalLayers,l=0;l<m.length;l++){var h=m[l];if(-1<this.tab.tabLayers[0].url.indexOf(h.url)&&"undefined"!==typeof h.layerObject)if(h.layerObject.infoTemplates){if(h=h.layerObject.infoTemplates[k]){b.infoTemplate=h.infoTemplate;break}}else if(h.layerObject.infoTemplate){b.infoTemplate=h.layerObject.infoTemplate;break}}f=[b];this.tab.tabLayers=f;this.loading=!1;this._performQuery(a,d,c,g,f).then(function(a){e.resolve(a)})})))}this.mapServiceLayer||
this._performQuery(a,d,c,g,f).then(function(a){e.resolve(a)});return e},_performQuery:function(a,d,c,g,e){var f=new v,b=[],k,m;0<d.length?m=n.getGeoms(d):0<a.length&&(m=n.getGeoms(a));this.summaryGeoms=m;if(0<m.length)for(a=0;a<m.length;a++)b=m[a],d=n.createDefArray(e,b,this.parent.opLayers,this.tab),k=0===a?b=d:b=k.concat(d);(new u(b)).then(p.hitch(this,function(a){for(var d=0,b=0;b<a.length;b++){var e=a[b][1];isNaN(e)?e&&e.features?d+=e.features.length:e&&"undefined"!==typeof e.length&&(d+=e.length):
d+=e}this.updateTabCount(d,c,g);this.queryOnLoad&&p.hitch(this,this._queryFeatures(this.summaryGeoms));f.resolve(d)}));return f},updateTabCount:function(a,d,c){this.displayCount=c;this.featureCount=a;n.updateTabCount(this.featureCount,d,c,this.baseLabel,this.incidentCount)},updateForIncident:function(a,d,c,g,e,f,b){this.incidentCount=a.length;this.allFields="undefined"!==typeof f&&"undefined"!==typeof b?f?!0:b:!1;var k="undefined"!==typeof e,m;this.tabNum=g;k?m=new v:(this.container.innerHTML="",
q.add(this.container,"loading"));this.summaryIds=[];this.summaryFeatures=[];this.groupedResults={};if(0<this.tab.tabLayers.length){var l=[];if(0<d.length)l=d;else for(d=0;d<a.length;d++)g=a[d].geometry?a[d].geometry:a[d],"polygon"===g.type&&l.push(g);var h;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],h=new t(this.summaryLayer.url),h.infoTemplate=this.tab.tabLayers[0].infoTemplate,this.tab.tabLayers[1]=h,this.summaryFields=this._getFields(this.tab.tabLayers[0]),
this.configuredPopUpFields=n.getPopupConfiguredFields(this.tab.tabLayers[0]),k?this._queryFeatures(l,k).then(function(a){m.resolve(a)}):(this._initGraphicsLayer(c),p.hitch(this,this._queryFeatures(l)))):(h=new t(this.tab.tabLayers[0].url),x(h,"load",p.hitch(this,function(){this.summaryLayer=h;if(-1<this.tab.tabLayers[0].url.indexOf("MapServer"))for(var a=this.tab.tabLayers[0].url.split("MapServer/")[1],d=this.parent.map.itemInfo.itemData.operationalLayers,e=0;e<d.length;e++){var b=d[e];if(-1<this.tab.tabLayers[0].url.indexOf(b.url)&&
"undefined"!==typeof b.layerObject&&b.layerObject.infoTemplates&&(b=b.layerObject.infoTemplates[a])){h.infoTemplate=b.infoTemplate;break}}this.tab.tabLayers[1]=h;this.summaryLayer=this.tab.tabLayers[1];this.summaryFields=this._getFields(this.tab.tabLayers[1]);this.configuredPopUpFields=n.getPopupConfiguredFields(this.tab.tabLayers[1]);k?this._queryFeatures(l,k).then(function(a){m.resolve(a)}):(this._initGraphicsLayer(c),p.hitch(this,this._queryFeatures(l)))})));if(k)return m}},_initGraphicsLayer:function(a){null!==
a&&(this.graphicsLayer=a,this.graphicsLayer.clear(),this.summaryLayer&&this.summaryLayer.renderer&&(this.lyrRenderer=this.summaryLayer.renderer,this.graphicsLayer.renderer=this.lyrRenderer,"undefined"!==typeof this.summaryLayer.renderer.attributeField?this.symbolField=this.summaryLayer.renderer.attributeField:this.lyrSymbol=this.lyrRenderer.symbol))},_queryFeatures:function(a,d){var c;d&&(c=new v);for(var g=[],e=-1===[null,void 0,""].indexOf(this.tab.tabLayers[0].id)?this.tab.tabLayers[0].id:this.tab.layers,
e=n.getFilter(e,this.parent.opLayers),f=new B,b=0;b<a.length;b++)f.geometry=a[b],f.where=e,g.push(this.summaryLayer.queryIds(f));(new u(g)).then(p.hitch(this,function(a){for(var b,e,f=0;f<a.length;f++)a[f][0]&&(b=a[f][1],e=b=0===f?b:e.concat(b));b?(this.summaryIds=b,0<this.summaryIds.length?d?this._queryFeaturesByIds(d).then(function(a){c.resolve(a)}):this._queryFeaturesByIds():d||this._processResults()):d||this._processResults()}),p.hitch(this,function(a){console.error(a);new A({message:a})}));if(d)return c},
_queryFeaturesByIds:function(a){var d,c=[];a&&(d=new v);var g=this.summaryLayer.maxRecordCount||1E3,e=this.summaryIds.slice(0,g);this.summaryIds.splice(0,g);var f=new B,b=-1===[null,void 0,""].indexOf(this.summaryLayer.id)?this.summaryLayer.id:this.tab.layers;f.where=n.getFilter(b,this.parent.opLayers);var k=!1;z.some(this.summaryFields,p.hitch(this,function(a){if("area"===a.type||"length"===a.type||this.graphicsLayer)return k=!0}));a&&(k=!0);this.summaryLayer.supportsAdvancedQueries&&(f.orderByFields=
[this.summaryFields[0].field]);f.returnGeometry=k;f.outSpatialReference=this.parent.map.spatialReference;f.outFields=["*"];f.objectIds=e;for(c.push(this.summaryLayer.queryFeatures(f));0<this.summaryIds.length;)e=this.summaryIds.slice(0,g),this.summaryIds.splice(0,g),f.objectIds=e,c.push(this.summaryLayer.queryFeatures(f));(new u(c)).then(p.hitch(this,function(c){this.summaryFeatures=[];for(var b=0;b<c.length;b++)if(c[b][0]){var e=c[b][1];e.features&&(this.summaryFeatures=this.summaryFeatures.concat(e.features))}a?
this._processResults(a).then(p.hitch(this,function(a){this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing");d.resolve(a)})):(this._processResults(),this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing"));this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing")}),p.hitch(this,function(a){console.error(a);new A({message:a})}));if(a)return d},_prepGroupedResults:function(){for(var a=0;a<this.summaryFeatures.length;a++){var d=this.summaryFeatures[a];
if("undefined"!==typeof this.summaryFields&&0<this.summaryFields.length){var c=n.getFieldValue(this.summaryFields[0].field,d.attributes[this.summaryFields[0].field],this.specialFields,this.dateFields,"longMonthDayYear",this.typeIdField,this.types,this.layerObject&&this.layerObject.renderer?this.layerObject:this.layerDefinition,d.attributes),c="undefined"!==typeof c&&null!==c?w.stripHTML(c.toString()):"";c in this.groupedResults?this.groupedResults[c].features.push(d):this.groupedResults[c]={features:[d]}}}},
_prepResults:function(){for(var a in this.groupedResults){var d=this.summaryFields[0];d.total=this.groupedResults[a].features.length;this.groupedResults[a].total=d.total;this.groupedResults[a].type=d.type;this.groupedResults[a].label=d.alias}},_processResults:function(a){this._prepGroupedResults();this._prepResults();var d=this.groupedResults,c=0,g,e;if(a)e=new v;else{this.container.innerHTML="";q.remove(this.container,"loading");if(0===Object.keys(this.groupedResults).length){this.container.innerHTML=
this.parent.nls.noFeaturesFound;return}var f=Object.keys(this.groupedResults).length+1;g=r.create("div",{style:"width:"+220*f+"px;"},this.container);q.add(g,"SAT_tabPanelContent");f=r.create("div",{},g);q.add(f,"SATcolExport");q.add(f,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");var b=r.create("div",{"data-dojo-attach-point":"SA_SAT_download",title:this.parent.nls.downloadCSV,tabindex:"0",role:"button","aria-label":this.parent.nls.downloadCSVdownloadCSV,"class":"grpSummaryDownLoadCSVButton"},
f);q.add(b,[this.parent.isBlackTheme?"btnExportBlack":"btnExport","download"]);q.add(b,this.parent.lightTheme?"lightThemeBackground":"darkThemeBackground");b.focus();w.initFirstFocusNode(this.parentNode,b);w.initLastFocusNode(this.parentNode,b);x(b,"click",p.hitch(this,this._exportToCSV,d));x(b,"keydown",p.hitch(this,function(a){if(!a.shiftKey||a.keyCode!==y.TAB)if(a.keyCode===y.ENTER||a.keyCode===y.SPACE)this._exportToCSV(d,a),setTimeout(function(){b.focus()},500)}))}var k=Object.keys(d).sort(),
f=[];this.displayCount&&f.push({total:this.featureCount,a:void 0,info:this.parent.nls.count,c:void 0});for(var m in k){var c=k[m],l=d[c],h=w.stripHTML(c.toString()),c=l.total;isNaN(c)&&(c=0);var c=w.localizeNumber(c),n="pre"===l.type?l.label.trim():h,h="pre"===l.type?h:l.label.trim(),l=""!==l.label?"colGroupedSummary":"colSummary";if(a)f.push({total:c,a:n,info:""===h?n:h,c:l});else{var t=r.create("div",{"class":"SATcol"},g);q.add(t,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");var u=
r.create("div",{style:"max-height: 45px;"},t);r.create("div",{"class":"SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:n},u);r.create("div",{"class":"SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:h},u);r.create("div",{"class":l,innerHTML:c},t)}}m=[];g=null!==this.graphicsLayer;!a&&g&&(this.graphicsLayer.clear(),this.tab.tabLayers[1]&&this.tab.tabLayers[1].clear());if(this.summaryFeatures)for(k=0;k<this.summaryFeatures.length;k++)c=this.summaryFeatures[k],this.lyrSymbol?
c.symbol=this.lyrSymbol:this.graphicsLayer?this.graphicsLayer.renderer&&(n=this.graphicsLayer.renderer.getSymbol(c),c.symbol=n):this.summaryLayer.renderer&&this.summaryLayer.renderer.getSymbol&&(c.symbol=this.summaryLayer.renderer.getSymbol(c)),c=c.toJson?new E(c.toJson()):c,!a&&g?(this.graphicsLayer.add(c),this.tab.tabLayers[1].add(c)):m.push(c);!a&&g&&(this.graphicsLayer.setVisibility(!0),this.parent._toggleTabLayersNew(this.tabNum),this.tab.retsore&&this.emit("summary-complete",{bubbles:!0,cancelable:!0,
tab:this.tabNum}));if(a)return e.resolve({graphics:m,analysisResults:f,context:this}),e},_exportToCSV:function(a,d,c,g){var e;this.parent.config.hasOwnProperty("exportFieldsOptionForCSV")?e=this.parent.config.exportFieldsOptionForCSV:this.parent.config.hasOwnProperty("csvAllFields")&&(e=this.parent.config.csvAllFields);a=n.exportToCSV(this.summaryFeatures,d,c,g,{type:"grouped",baseLabel:this.baseLabel,csvAllFields:e,layer:this.summaryLayer,opLayers:this.parent.opLayers,nlsValue:this.parent.nls.groupedSummary,
nlsCount:this.parent.nls.count,summaryFields:this.summaryFields,allFields:this.allFields,configuredPopUpFields:this.configuredPopUpFields});this.summaryLayer=a.summaryLayer;return a.details},_getFields:function(a){this.layerDefinition=w.getFeatureLayerDefinition(a);this.layerObject=a;var d=n.getSkipFields(a),c,g=[];if("undefined"!==typeof this.tab.advStat){var e=this.tab.advStat.stats,f;for(f in e)0<e[f].length&&z.forEach(e[f],function(a){var b={field:a.expression,alias:a.label+"",type:f,total:0};
c=a.expression;g.push(b)})}e=n.getSpecialFields(a);this.dateFields=e.dateFields;this.specialFields=e.specialFields;this.typeIdField=e.typeIdField;this.types=e.types;if(this.allFields)for(e=0;e<a.fields.length;e++){var b=a.fields[e];-1===d.indexOf(b.name)&&c!==b.name&&g.push({field:b.name,alias:b.alias,type:b.type})}return g}})});