// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/DeferredList dojo/_base/array jimu/utils jimu/dijit/SnapShot ./CSVUtils".split(" "),function(r,m,n,q,t,p,u,v){return r("SnapShotUtils",null,{portal:null,portalUrl:"",logo:"",originMapId:"",originAppId:"",credential:null,nls:null,layerArray:[],parent:null,downloadAll:!1,time:null,constructor:function(a){this.parent=a;this.snapshot=new u(a.appConfig,a.map);this.map=this.parent.map;this.extent=this.map.extent;this.nls=m.mixin({},a.nls,window.jimuNls.drawBox,
window.jimuNls.snapshot)},createSnapShot:function(a){var e=new n,g=p.stripHTML(a.name),b=this._getTime(a.time);this.createLayerItems(a,b,g).then(m.hitch(this,function(c){this.snapshot.createSnapShot({folderOptions:{folderName:g+"_"+b,title:g+"_"+b,description:g+" "+this.nls.snapshot},mapTitle:g+" ("+this.nls.snapshot_append+" "+b+")",name:g+" ("+b+")",shareWith:{everyone:!1,org:!1,groups:a.groups.join()},mapExtent:this.map.extent,data:c}).then(function(){e.resolve()})}));return e},_getTime:function(a){a=
new Date(a);var e=a.getTimezoneOffset();return p.fieldFormatter.getFormattedDate(a,{dateFormat:"shortDateShortTime"})+" "+this.nls.utc+(0>e?"+"+Math.abs(e)/60:"-"+e/60)},createLayerItems:function(a,e,g){var b=new n,c=a.layers.reverse();this.buffers=a.buffers;this.incidents=a.incidents;a=[];for(var d=0;d<c.length;d++){var h=!0;c[d].analysisObject&&"undefined"!==typeof c[d].analysisObject.featureCount&&0===c[d].analysisObject.featureCount&&(h=!1);c[d].graphics&&0===c[d].graphics.length&&(h=!1);h&&a.push(this.createItem(c[d],
this.incidents,this.buffers,e,this.nls,g))}var k=[];(new q(a)).then(m.hitch(this,function(a){for(var d=0;d<a.length;d++){var c=a[d][1];if(Array.isArray(c))for(var f=0;f<c.length;f++)k.push(c[f]);else k.push(c)}b.resolve(k)}),m.hitch(this,function(a){b.reject(a)}));return b},createItem:function(a,e,g,b,c,d){var h=new n,k={label:a.label,title:a.label+"_"+b,desc:c.snapshot_append+" "+c.of_append+" "+(a.type?a.type:a.label)+" "+c.layer_append+" "+a.label+" ("+b+")",name:a.label+"("+b+")",tags:[d+","+
c.snapshot_append],originalLayerName:a.label};if(a.layerObject){var f=a.layerObject;d=a.analysisObject;var l;f.infoTemplate&&f.infoTemplate.info&&(l=f.infoTemplate.info);k.popupInfo=l;"groupedSummary"===a.type||"summary"===a.type?d.updateForIncident(e,g,null,null,!0,!0,!0).then(m.hitch(this,function(a){a=this.createAnalysisLayerJSON(a,f,c,b,k);h.resolve(a)})):d.updateForIncident(e,"closest"===a.type?this.parent.config.maxDistance:g,null,!0,!0,!0).then(m.hitch(this,function(a){a=this.createAnalysisLayerJSON(a,
f,c,b,k);h.resolve(a)}))}else a=this.createIncidentBufferLayerJSON(a.graphics,c,b,k),h.resolve(a);return h},createAnalysisLayerJSON:function(a,e,g,b,c){g=a.graphics;b=a.context._exportToCSV(g,!0);a=[];for(var d=0;d<b.length;d++){var h=b[d];"esriFieldTypeOID"!==h.type&&a.push(h)}for(b=0;b<g.length;b++)d=g[b],d.geometry.cache&&(d.geometry.clearCache(),delete d.geometry.cahce);return{graphics:g,renderer:e.renderer,infoTemplate:c.popupInfo,fields:a,tags:c.tags,description:c.desc,name:c.name,visibleOnStartup:!1,
typeIdField:e.typeIdField,types:e.types,minScale:e.minScale,maxScale:e.maxScale,originalLayerName:c.originalLayerName}},createIncidentBufferLayerJSON:function(a,e,g,b){var c=[],d=[],h=[];e=[];t.forEach(a,function(a){switch(a.geometry.type){case "point":c.push(a);break;case "polyline":d.push(a);break;case "polygon":h.push(a)}});a=[];0<c.length&&a.push(c);0<d.length&&a.push(d);0<h.length&&a.push(h);g={point:this.nls.point,polyline:this.nls.line,polygon:this.nls.polygon};for(var k=0;k<a.length;k++){var f=
a[k],l;0<f.length&&(l=f[0],l=g["undefined"!==typeof l.geometry?l.geometry.type:l.type],e.push({graphics:f,fields:[],tags:b.tags,description:b.desc,name:1===a.length?b.name:l+" "+b.name,visibleOnStartup:!1,originalLayerName:b.originalLayerName}))}return e},createDownloadZip:function(a,e,g){var b=new n,c=this.nls.calculated_results;this._performAnalysis(a,e,g,this.downloadAll,!1).then(function(a){for(var d=[],e=0;e<a.length;e++){var f=a[e];(f=f.context._exportToCSV(f.graphics,!1,!0,f.analysisResults))&&
d.push(f)}0<d.length&&v.exportCalculatedResultsCSV(c,d);b.resolve("success")},function(a){b.reject(a)});return b},_performAnalysis:function(a,e,g,b,c){for(var d=new n,h=[],k=0;k<a.length;k++){var f=a[k];console.log("AO: "+f);var l=!0;f.analysisObject&&"undefined"!==typeof f.analysisObject.featureCount&&0===f.analysisObject.featureCount&&(l=!1);l&&("groupedSummary"===f.type||"summary"===f.type?h.push(f.analysisObject.updateForIncident(e,g,null,null,!0,c,b)):h.push(f.analysisObject.updateForIncident(e,
"closest"===f.type?this.parent.config.maxDistance:g,null,!0,c,b)))}var p=[];(new q(h)).then(m.hitch(this,function(a){for(var b=0;b<a.length;b++)p.push(a[b][1]);d.resolve(p)}),m.hitch(this,function(a){console.error(a);d.reject(a)}));return d}})});