// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/_base/kernel dojo/_base/lang dojo/Deferred dojo/promise/all esri/arcade/arcade esri/arcade/Feature esri/support/expressionUtils esri/arcadeProfiles/utils esri/graphic ./generalUtils".split(" "),function(h,q,k,m,p,n,r,l,t,u,v){var f={convertPopupToLabelSpec:function(a){var c=[],b,d,e;b=a.description;d=a.fieldInfos;e=a.expressionInfos;a=v.sanitizeNoTags(f.convertBreaksToEOLs(f.convertEndParasToEOLs(b))).trim();a=a.replace(/\{/gi,"${");a=a.replace(/\u00a0/gi," ");a=a.split("\n");
a=h.map(a,function(a){var b="";a=a.replace(/\{([^}]+)\}/g,function(a,c){var g;h.some(d,function(a){var d;if(a.fieldName.toLowerCase()===c.toLowerCase()){g=a.fieldName;d=a.label||a.fieldName;if(!a.hasOwnProperty("label")&&e)for(a=0;a<e.length;a++)d==="expression/"+e[a].name&&(d=e[a].title);b=""===b?d:b+" "+d;return!0}});return g?c?"{"+g+"}":a:c?"{"+c+"}":a});c.push(b);return a.trim()});a.csvHeaderRow=c;return a},createLabelsFromFeatures:function(a,c,b,d){var e=new m,g=[],l=[],k=0;f.layer=b;f.map=d;
f.expressionInfos=c.expressionInfos;if(c.relationships)h.forEach(a,function(a){f.objEach(c.relationships,function(b,d){var e=new m,g=b.relatedQuery,k;l.push(e);k=a.attributes[b.operLayer.layerObject.objectIdField];g.objectIds=[k];b.operLayer.layerObject.queryRelatedFeatures(g,function(b){var g=[];b[k]&&b[k].features&&(b=b[k].features,h.forEach(b,function(b){var e,h,k;e=a.attributes;h="relationships/"+d+"/";f.objEach(b.attributes,function(a,b){k=h+b;e[k]=a});b=new u(a.geometry,null,e);g.push(f.populateLabelLines(b,
c))}));p(g).then(function(a){e.resolve(a)})})})}),p(l).then(function(a){h.forEach(a,function(a){h.forEach(a,function(a){++k;g.push(a)})});console.log(k+" related address features found");e.resolve(g)});else{var n=[];h.forEach(a,function(a){n.push(f.populateLabelLines(a,c))});p(n).then(function(a){e.resolve(a)})}return e},populateLabelLines:function(a,c){var b=new m,d=[];f.combineFeatureAttributesAndExpressionResolutions(a,c.parsedExpressions).then(function(a){h.forEach(c,function(b){d.push(f.substitute(b,
a,f.useEmptyStringForNull))});b.resolve(d)});return b.promise},substitute:function(a,c,b){var d=q.global;b=b?k.hitch(d,b):function(a){return a};return a.replace(/\$\{([^\s\:\}]*)(?:\:([^\s\:\}]+))?\}/g,function(a,d){if(""===d)return"$";a=b(c[d],d);if("undefined"===typeof a)throw Error('string.substitute could not find key "'+d+'" in template');return a.toString()})},parseArcadeExpressions:function(a){var c;Array.isArray(a)&&0<a.length&&(c={},h.forEach(a,function(a){c[a.name]=n.parseScript(a.expression)}));
return c},initArcadeContext:function(a){var c=null,b=null,d=null,e=null;f.expressionInfos&&(d=f.expressionInfos);f.map&&(b=f.map);f.layer&&f.layer.layerObject&&(c=f.layer.layerObject);a&&a.geometry&&a.geometry.spatialReference&&(e=a.geometry.spatialReference);return f.getEvalOptions({expression:d,feature:a,layer:c,map:b,sr:e}).context},getEvalOptions:function(a){var c=a.feature,b=a.layer,d=a.map;a=a.spatialReference;var c=c?r.createFromGraphicLikeObject(c.geometry,c.attributes,b):null,e,g;b&&(g={spatialReference:a},
e=b.getMap()?l.createFeatureSetFromLayer(b,g):l.createFeatureSetFromLayerUrl(b.url,g),g=(b=t.getServiceUrl(b.url))?l.createFeatureSetCollectionFromServiceUrl(b,g):null);d=d?l.createFeatureSetCollectionFromMap(d):null;return{context:{vars:{$feature:c,$layer:e,$datastore:g,$map:d},spatialReference:a}}},combineFeatureAttributesAndExpressionResolutions:function(a,c){var b=new m,d=[],e,g;e=k.mixin({},a.attributes);if(c){a=f.initArcadeContext(a);for(g in c)d.push(f.executeArcadeExpression(g,c[g],a,e));
p(d).then(function(){b.resolve(e)})}else b.resolve(e);return b.promise},executeArcadeExpression:function(a,c,b,d){var e=new m;(c=n.executeScript(c,b))&&c.then?c.then(function(b){d["expression/"+a]=b?b.toString():"";e.resolve(b)},function(b){d["expression/"+a]=b?b.toString():"";e.resolve(b)}):(d["expression/"+a]=c?c.toString():"",e.resolve(c));return e.promise},convertEndParasToEOLs:function(a){var c=a;a=a.match(/<\/p>/gi);h.forEach(a,function(a){c=c.replace(a,"\n")});return c},convertBreaksToEOLs:function(a){var c=
a;a=a.match(/<br\s*\/?>/gi);h.forEach(a,function(a){c=c.replace(a,"\n")});return c},useEmptyStringForNull:function(a){return a?a:""},objEach:function(a,c,b){for(var d in a)a.hasOwnProperty(d)&&c.call(b,a[d],d)}};return f});