// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fet",copy:"Kopier",cut:"Klipp ut","delete":"Slett",indent:"Innrykk",insertHorizontalRule:"Vannrett strek",insertOrderedList:"Nummerert liste",insertUnorderedList:"Punktliste",italic:"Kursiv",justifyCenter:"Midtstill",justifyFull:"Juster",justifyLeft:"Venstrejuster",justifyRight:"H\u00f8yrejuster",outdent:"Fjern innrykk",paste:"Lim inn",redo:"Gj\u00f8r om",removeFormat:"Fjern format",selectAll:"Velg alle",strikethrough:"Gjennomstreking",subscript:"Senket skrift",
superscript:"Hevet skrift",underline:"Understreking",undo:"Angre",unlink:"Fjern kobling",createLink:"Opprett kobling",toggleDir:"Bytt retning",insertImage:"Sett inn bilde",insertTable:"Sett inn/rediger tabell",toggleTableBorder:"Bytt tabellkant",deleteTable:"Slett tabell",tableProp:"Tabellegenskap",htmlToggle:"HTML-kilde",foreColor:"Forgrunnsfarge",hiliteColor:"Bakgrunnsfarge",plainFormatBlock:"Avsnittsstil",formatBlock:"Avsnittsstil",fontSize:"Skriftst\u00f8rrelse",fontName:"Skriftnavn",tabIndent:"Tabulatorinnrykk",
fullScreen:"Sl\u00e5 p\u00e5/av full skjerm",viewSource:"Vis HTML-kilde",print:"Skriv ut",newPage:"Ny side",systemShortcut:'Handlingen "${0}" er bare tilgjengelig i nettleseren ved hjelp av en tastatursnarvei. Bruk ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"s\u00f8. ma. ti. on. to. fr. l\u00f8.".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"n\u00e5",
"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Ukedag","field-wed-relative+0":"onsdag denne uken","field-wed-relative+1":"onsdag neste uke","dateFormatItem-GyMMMEd":"E d. MMM y G","dateFormatItem-MMMEd":"E d. MMM",eraNarrow:["AH"],"field-tue-relative+-1":"tirsdag sist uke","days-format-short":"s\u00f8. ma. ti. on. to. fr. l\u00f8.".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d. MMMM y G","field-fri-relative+-1":"fredag sist uke","field-wed-relative+-1":"onsdag sist uke",
"months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"p.m.","dateFormat-full":"EEEE d. MMMM y G","dateFormatItem-yyyyMEd":"E d.M.y G","field-thu-relative+-1":"torsdag sist uke","dateFormatItem-Md":"d.M.","dayPeriods-format-abbr-am":"a.m.","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})",
"dayPeriods-format-wide-noon":"noon","field-era":"Tidsalder","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH.mm","quarters-format-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"timeFormat-long":"HH.mm.ss z","field-year":"\u00c5r","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Time","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),
"field-sat-relative+0":"l\u00f8rdag denne uken","field-sat-relative+1":"l\u00f8rdag neste uke","timeFormat-full":"HH.mm.ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"i dag","field-thu-relative+0":"torsdag denne uken","field-day-relative+1":"i morgen","field-thu-relative+1":"torsdag neste uke","dateFormatItem-GyMMMd":"d. MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),
"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-standAlone-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E d. MMM y G","dateFormatItem-M":"L.","days-standAlone-wide":"s\u00f8ndag mandag tirsdag onsdag torsdag fredag l\u00f8rdag".split(" "),"dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d. MMM y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH.mm.ss","field-sun-relative+0":"s\u00f8ndag denne uken",
"dateFormatItem-Hm":"HH.mm","field-sun-relative+1":"s\u00f8ndag neste uke","quarters-standAlone-abbr":["K1","K2","K3","K4"],eraAbbr:["AH"],"field-minute":"Minutt","field-dayperiod":"AM/PM","days-standAlone-abbr":"s\u00f8. ma. ti. on. to. fr. l\u00f8.".split(" "),"dateFormatItem-d":"d.","dateFormatItem-ms":"mm.ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"i g\u00e5r","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d. MMM",
"dateFormatItem-MEd":"E d.M","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"fredag denne uken","field-fri-relative+1":"fredag neste uke","field-day":"Dag","days-format-wide":"s\u00f8ndag mandag tirsdag onsdag torsdag fredag l\u00f8rdag".split(" "),"field-zone":"Tidssone","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"i fjor","field-month-relative+-1":"forrige m\u00e5ned",
"dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h.mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"p.m.","days-format-abbr":"s\u00f8n. man. tir. ons. tor. fre. l\u00f8r.".split(" "),eraNames:["AH"],"days-format-narrow":"SMTOTFL".split(""),"dateFormatItem-yyyyMd":"d.M.y G","field-month":"M\u00e5ned","days-standAlone-narrow":"SMTOTFL".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"tirsdag denne uken","field-tue-relative+1":"tirsdag neste uke",
"dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"a.m.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"mandag denne uken","field-mon-relative+1":"mandag neste uke","dateFormat-short":"d.M. y G","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Sekund","field-sat-relative+-1":"l\u00f8rdag sist uke",
"field-sun-relative+-1":"s\u00f8ndag sist uke","field-month-relative+0":"denne m\u00e5neden","field-month-relative+1":"neste m\u00e5ned","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E d.","field-week":"Uke","dateFormat-medium":"d. MMM y G","field-week-relative+-1":"forrige uke","field-year-relative+0":"i \u00e5r","dateFormatItem-yyyyM":"M.y G","field-year-relative+1":"neste \u00e5r","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1} {0}",
"dateFormatItem-Hms":"HH.mm.ss","dateFormatItem-hms":"h.mm.ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"mandag sist uke","dateFormatItem-yyyy":"y G","field-week-relative+0":"denne uken","field-week-relative+1":"neste uke","field-day-relative+2":"i overmorgen","field-day-relative+-2":"i forg\u00e5rs",_localized:{}},"widgets/ParcelDrafter/nls/strings":{_widgetLabel:"Parcel Drafter",newTraverseButtonLabel:"Start nytt polygondrag",invalidConfigMsg:"Ugyldig konfigurasjon",geometryServiceURLNotFoundMSG:"Kan ikke hente URL for geometritjeneste",
editTraverseButtonLabel:"Rediger polygondrag",mapTooltipForStartNewTraverse:"Velg et punkt p\u00e5 kartet eller skriv nedenfor for \u00e5 begynne",mapTooltipForEditNewTraverse:"Velg en teig som skal redigeres",mapTooltipForUpdateStartPoint:"Klikk for \u00e5 oppdatere startpunkt",mapTooltipForScreenDigitization:"Klikk for \u00e5 legge til teigpunkt",mapTooltipForUpdatingRotaionPoint:"Klikk for \u00e5 oppdatere rotasjonspunkt",mapTooltipForRotate:"Dra for \u00e5 rotere",mapTooltipForScale:"Dra for \u00e5 skalere",
backButtonTooltip:"Tilbake",newTraverseTitle:"Nytt polygondrag",editTraverseTitle:"Rediger polygondrag",clearingDataConfirmationMessage:"Endringene lagres ikke. Vil du fortsette?",unableToFetchParcelMessage:"Kan ikke hente teig.",unableToFetchParcelLinesMessage:"Kan ikke hente teiglinjer.",planSettings:{planSettingsTitle:"Innstillinger",directionOrAngleTypeLabel:"Retning- eller vinkeltype",directionOrAngleUnitsLabel:"Retning- eller vinkelenheter",distanceAndLengthUnitsLabel:"Avstands- eller lengdeenheter",
areaUnitsLabel:"Arealenheter",circularCurveParameters:"Sirkul\u00e6re kurveparametre",northAzimuth:"Nordlig asimut",southAzimuth:"S\u00f8rlig asimut",quadrantBearing:"Kvadrantpeiling",radiusAndChordLength:"Radius og kordelengde",radiusAndArcLength:"Radius og buelengde",expandGridTooltipText:"Vis rutenett",collapseGridTooltipText:"Skjul rutenett",zoomToLocationTooltipText:"Zoom til lokasjon",onScreenDigitizationTooltipText:"Digitaliser",updateRotationPointTooltipText:"Oppdater rotasjonspunkt"},traverseSettings:{bearingLabel:"Peiling",
lengthLabel:"Lengde",radiusLabel:"Radius",noMiscloseCalculated:"Ikke lukket ikke beregnet",traverseMiscloseBearing:"Ikke lukket peiling",traverseAccuracy:"N\u00f8yaktighet",accuracyHigh:"H\u00f8y",traverseDistance:"Ikke lukket avstand",traverseMiscloseRatio:"Ikke lukket forhold",traverseStatedArea:"Oppgitt areal",traverseCalculatedArea:"Beregnet areal",addButtonTitle:"Legg til",deleteButtonTitle:"Fjern"},parcelTools:{rotationToolLabel:"Vinkel",scaleToolLabel:"M\u00e5lestokk"},newTraverse:{invalidBearingMessage:"Ugyldig peiling.",
invalidLengthMessage:"Ugyldig lengde.",invalidRadiusMessage:"Ugyldig radius.",negativeLengthMessage:"Bare gyldig for kurver",enterValidValuesMessage:"Angi gyldige verdier.",enterValidParcelInfoMessage:"Angi gyldig teiginformasjon som skal lagres.",unableToDrawLineMessage:"Kan ikke tegne linje.",invalidEndPointMessage:"Ugyldig sluttpunkt. Kan ikke tegne linje.",lineTypeLabel:"Linjetype"},planInfo:{requiredText:"(obligatorisk)",optionalText:"(valgfritt)",parcelNamePlaceholderText:"Teignavn",parcelDocumentTypeText:"Dokumenttype",
planNamePlaceholderText:"Plannavn",cancelButtonLabel:"Avbryt",saveButtonLabel:"Lagre",saveNonClosedParcelConfirmationMessage:"Den angitte teigen er ikke lukket. Vil du fortsette og kun lagre teiglinjer?",unableToCreatePolygonParcel:"Kan ikke opprette teigpolygon.",unableToSavePolygonParcel:"Kan ikke lagre teigpolygon.",unableToSaveParcelLines:"Kan ikke lagre teiglinjer.",unableToUpdateParcelLines:"Kan ikke oppdatere teiglinjer.",parcelSavedSuccessMessage:"Lagring av teig var vellykket.",parcelDeletedSuccessMessage:"Eiendom er slettet.",
parcelDeleteErrorMessage:"Feil ved sletting av eiendom.",enterValidParcelNameMessage:"Angi et gyldig teignavn.",enterValidPlanNameMessage:"Angi et gyldig plannavn.",enterValidDocumentTypeMessage:"Ugyldig dokumenttype",enterValidStatedAreaNameMessage:"Angi et gyldig angitt omr\u00e5de.",showAttributeList:"Vis attributtliste",hideAttributeList:"Skul attributtliste"},xyInput:{explanation:"Angi koordinater i samme romlig referanse som laget"},_localized:{}}});