// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Bold",copy:"Copy",cut:"Cut","delete":"Delete",indent:"Indent",insertHorizontalRule:"Horizontal Rule",insertOrderedList:"Numbered List",insertUnorderedList:"Bullet List",italic:"Italic",justifyCenter:"Align Center",justifyFull:"Justify",justifyLeft:"Align Left",justifyRight:"Align Right",outdent:"Outdent",paste:"Paste",redo:"Redo",removeFormat:"Remove Format",selectAll:"Select All",strikethrough:"Strikethrough",subscript:"Subscript",superscript:"Superscript",
underline:"Underline",undo:"Undo",unlink:"Remove Link",createLink:"Create Link",toggleDir:"Toggle Direction",insertImage:"Insert Image",insertTable:"Insert/Edit Table",toggleTableBorder:"Toggle Table Border",deleteTable:"Delete Table",tableProp:"Table Property",htmlToggle:"HTML Source",foreColor:"Foreground Color",hiliteColor:"Background Color",plainFormatBlock:"Paragraph Style",formatBlock:"Paragraph Style",fontSize:"Font Size",fontName:"Font Name",tabIndent:"Tab Indent",fullScreen:"Toggle Full Screen",
viewSource:"View HTML Source",print:"Print",newPage:"New Page",systemShortcut:'The "${0}" action is only available in your browser using a keyboard shortcut. Use ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"now","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Day of the Week",
"field-wed-relative+0":"this Wednesday","field-wed-relative+1":"next Wednesday","dateFormatItem-GyMMMEd":"E, MMM d, y G","dateFormatItem-MMMEd":"E, MMM d",eraNarrow:["AH"],"field-tue-relative+-1":"last Tuesday","days-format-short":"Su Mo Tu We Th Fr Sa".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"MMMM d, y G","field-fri-relative+-1":"last Friday","field-wed-relative+-1":"last Wednesday","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE, MMMM d, y G","dateFormatItem-yyyyMEd":"E, M/d/y GGGGG","field-thu-relative+-1":"last Thursday","dateFormatItem-Md":"M/d","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"timeFormat-short":"h:mm a","quarters-format-wide":["1st quarter","2nd quarter","3rd quarter","4th quarter"],"timeFormat-long":"h:mm:ss a z","field-year":"Year","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Hour","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"this Saturday","field-sat-relative+1":"next Saturday","timeFormat-full":"h:mm:ss a zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})",
"field-day-relative+0":"today","field-thu-relative+0":"this Thursday","field-day-relative+1":"tomorrow","field-thu-relative+1":"next Thursday","dateFormatItem-GyMMMd":"MMM d, y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["Q1","Q2","Q3","Q4"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E, MMM d, y G","dateFormatItem-M":"L",
"days-standAlone-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"MMM d, y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"h:mm:ss a","field-sun-relative+0":"this Sunday","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"next Sunday","quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],eraAbbr:["AH"],"field-minute":"Minute","field-dayperiod":"am/pm","days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-d":"d",
"dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"yesterday","dateTimeFormat-long":"{1} 'at' {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"E, M/d","dateTimeFormat-full":"{1} 'at' {0}","field-fri-relative+0":"this Friday","field-fri-relative+1":"next Friday","field-day":"Day","days-format-wide":"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),"field-zone":"Time Zone",
"months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"last year","field-month-relative+-1":"last month","dateTimeFormats-appendItem-Year":"{0} {1}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),eraNames:["AH"],"days-format-narrow":"SMTWTFS".split(""),"dateFormatItem-yyyyMd":"M/d/y GGGGG",
"field-month":"Month","days-standAlone-narrow":"SMTWTFS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"this Tuesday","field-tue-relative+1":"next Tuesday","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"this Monday","field-mon-relative+1":"next Monday","dateFormat-short":"M/d/y GGGGG","dateFormatItem-EHms":"E HH:mm:ss",
"dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Second","field-sat-relative+-1":"last Saturday","field-sun-relative+-1":"last Sunday","field-month-relative+0":"this month","field-month-relative+1":"next month","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"d E","field-week":"Week","dateFormat-medium":"MMM d, y G","field-week-relative+-1":"last week","field-year-relative+0":"this year","dateFormatItem-yyyyM":"M/y GGGGG","field-year-relative+1":"next year",
"dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"last Monday","dateFormatItem-yyyy":"y G","field-week-relative+0":"this week","field-week-relative+1":"next week",_localized:{"en-au":1,"en-gb":1}},"widgets/ParcelDrafter/nls/strings":{_widgetLabel:"Parcel Drafter",newTraverseButtonLabel:"Start New Traverse",invalidConfigMsg:"Invalid Configuration",
geometryServiceURLNotFoundMSG:"Unable to get Geometry Service URL",editTraverseButtonLabel:"Edit Traverse",mapTooltipForStartNewTraverse:"Please select a point on map, or type below, to begin",mapTooltipForEditNewTraverse:"Please select a parcel to edit",mapTooltipForUpdateStartPoint:"Click to update start point",mapTooltipForScreenDigitization:"Click to add parcel point",mapTooltipForUpdatingRotaionPoint:"Click to update rotation point",mapTooltipForRotate:"Drag to rotate",mapTooltipForScale:"Drag to scale",
backButtonTooltip:"Back",newTraverseTitle:"New Traverse",editTraverseTitle:"Edit Traverse",clearingDataConfirmationMessage:"Changes will be discarded, do you want to proceed?",unableToFetchParcelMessage:"Unable to fetch parcel.",unableToFetchParcelLinesMessage:"Unable to fetch parcel lines.",planSettings:{planSettingsTitle:"Settings",directionOrAngleTypeLabel:"Direction or Angle Type",directionOrAngleUnitsLabel:"Direction or Angle Units",distanceAndLengthUnitsLabel:"Distance and Length Units",areaUnitsLabel:"Area Units",
circularCurveParameters:"Circular Curve Parameters",northAzimuth:"North Azimuth",southAzimuth:"South Azimuth",quadrantBearing:"Quadrant Bearing",radiusAndChordLength:"Radius and Chord Length",radiusAndArcLength:"Radius and Arc Length",expandGridTooltipText:"Expand grid",collapseGridTooltipText:"Collapse grid",zoomToLocationTooltipText:"Zoom to location",onScreenDigitizationTooltipText:"Digitize",updateRotationPointTooltipText:"Update rotation point"},traverseSettings:{bearingLabel:"Bearing",lengthLabel:"Length",
radiusLabel:"Radius",noMiscloseCalculated:"Misclose not calculated",traverseMiscloseBearing:"Misclose Bearing",traverseAccuracy:"Accuracy",accuracyHigh:"High",traverseDistance:"Misclose Distance",traverseMiscloseRatio:"Misclose Ratio",traverseStatedArea:"Stated Area",traverseCalculatedArea:"Calculated Area",addButtonTitle:"Add",deleteButtonTitle:"Remove"},parcelTools:{rotationToolLabel:"Angle",scaleToolLabel:"Scale"},newTraverse:{invalidBearingMessage:"Invalid Bearing.",invalidLengthMessage:"Invalid Length.",
invalidRadiusMessage:"Invalid Radius.",negativeLengthMessage:"Valid only for curves",enterValidValuesMessage:"Please enter valid values.",enterValidParcelInfoMessage:"Please enter some valid parcel info to save.",unableToDrawLineMessage:"Unable to draw line.",invalidEndPointMessage:"Invalid End-Point, unable to draw line.",lineTypeLabel:"Line Type"},planInfo:{requiredText:"(required)",optionalText:"(optional)",parcelNamePlaceholderText:"Parcel name",parcelDocumentTypeText:"Document type",planNamePlaceholderText:"Plan name",
cancelButtonLabel:"Cancel",saveButtonLabel:"Save",saveNonClosedParcelConfirmationMessage:"The entered parcel is not closed, do you still want to proceed and save only parcel lines?",unableToCreatePolygonParcel:"Unable to create parcel polygon.",unableToSavePolygonParcel:"Unable to save parcel polygon.",unableToSaveParcelLines:"Unable to save parcel lines.",unableToUpdateParcelLines:"Unable to update parcel lines.",parcelSavedSuccessMessage:"Parcel saved successfully.",parcelDeletedSuccessMessage:"Parcel deleted successfully.",
parcelDeleteErrorMessage:"Error in deleteing parcel.",enterValidParcelNameMessage:"Please enter valid parcel name.",enterValidPlanNameMessage:"Please enter valid plan name.",enterValidDocumentTypeMessage:"Invalid document type.",enterValidStatedAreaNameMessage:"Please enter valid stated area.",showAttributeList:"Show attribute list",hideAttributeList:"Hide attribute list"},xyInput:{explanation:"Enter coordinates in same spatial reference as the layer"},_localized:{}}});