// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Aldin",copy:"Copiere",cut:"T\u0103iere","delete":"\u015etergere",indent:"Mic\u015forare indent",insertHorizontalRule:"Linie delimitatoare",insertOrderedList:"List\u0103 numerotat\u0103",insertUnorderedList:"List\u0103 cu marcator",italic:"Cursiv",justifyCenter:"Aliniere centru",justifyFull:"Aliniere st\u00e2nga-dreapta",justifyLeft:"Aliniere st\u00e2nga",justifyRight:"Aliniere dreapta",outdent:"M\u0103rire indent",paste:"Lipire",redo:"Refacere ac\u0163iune",
removeFormat:"\u00cenl\u0103turare format",selectAll:"Selecteaz\u0103 tot",strikethrough:"T\u0103iere text cu o linie",subscript:"Scriere indice inferior",superscript:"Scriere indice superior",underline:"Subliniere",undo:"Anulare ac\u0163iune",unlink:"\u00cenl\u0103turare leg\u0103tur\u0103",createLink:"Creare leg\u0103tur\u0103",toggleDir:"Comutare direc\u0163ie",insertImage:"Inserare imagine",insertTable:"Inserare/Editare tabel\u0103",toggleTableBorder:"Comutare bordur\u0103 tabel\u0103",deleteTable:"\u015etergere tabel\u0103",
tableProp:"Proprietate tabel\u0103",htmlToggle:"Surs\u0103 HTML",foreColor:"Culoare de prim-plan",hiliteColor:"Culoare de fundal",plainFormatBlock:"Stil paragraf",formatBlock:"Stil paragraf",fontSize:"Dimensiune font",fontName:"Nume font",tabIndent:"Indentare Tab",fullScreen:"Comutare ecran complet",viewSource:"Vizualizara surs\u0103 HTML",print:"Tip\u0103rire",newPage:"Pagin\u0103 nou\u0103",systemShortcut:'Ac\u0163iunea "${0}" este disponibil\u0103 \u00een browser doar utiliz\u00e2nd o comand\u0103 rapid\u0103 de la tastatur\u0103. Utiliza\u0163i ${1}.',
ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Du Lu Ma Mi Jo Vi S\u00e2".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"acum","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Zi a s\u0103pt\u0103m\u00e2nii","field-wed-relative+0":"miercurea aceasta","field-wed-relative+1":"miercurea viitoare","dateFormatItem-GyMMMEd":"E, d MMM y G","dateFormatItem-MMMEd":"E, d MMM",
eraNarrow:["AH"],"field-tue-relative+-1":"mar\u021bea trecut\u0103","days-format-short":"Du Lu Ma Mi Jo Vi S\u00e2".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d MMMM y G","field-fri-relative+-1":"vinerea trecut\u0103","field-wed-relative+-1":"miercurea trecut\u0103","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G",
"dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"p.m.","dateFormat-full":"EEEE, d MMMM y G","dateFormatItem-yyyyMEd":"E, dd.MM.y G","field-thu-relative+-1":"joia trecut\u0103","dateFormatItem-Md":"dd.MM","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Er\u0103","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"timeFormat-short":"HH:mm","quarters-format-wide":["trimestrul I","trimestrul al II-lea","trimestrul al III-lea","trimestrul al IV-lea"],"timeFormat-long":"HH:mm:ss z","field-year":"An","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Or\u0103","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"s\u00e2mb\u0103ta aceasta","field-sat-relative+1":"s\u00e2mb\u0103ta viitoare","timeFormat-full":"HH:mm:ss zzzz",
"dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"azi","field-thu-relative+0":"joia aceasta","field-day-relative+1":"m\u00e2ine","field-thu-relative+1":"joia viitoare","dateFormatItem-GyMMMd":"d MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["trim. I","trim. II","trim. III","trim. IV"],"quarters-standAlone-wide":["Trimestrul I","Trimestrul al II-lea",
"Trimestrul al III-lea","Trimestrul al IV-lea"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E, d MMM y G","dateFormatItem-M":"L","days-standAlone-wide":"Duminic\u0103 Luni Mar\u021bi Miercuri Joi Vineri S\u00e2mb\u0103t\u0103".split(" "),"dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d MMM y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"duminica aceasta","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"duminica viitoare",
"quarters-standAlone-abbr":["Trim. I","Trim. II","Trim. III","Trim. IV"],eraAbbr:["AH"],"field-minute":"Minut","field-dayperiod":"a.m/p.m.","days-standAlone-abbr":"Dum Lun Mar Mie Joi Vin S\u00e2m".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"ieri","dateTimeFormat-long":"{1} 'la' {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E, dd.MM","dateTimeFormat-full":"{1} 'la' {0}",
"field-fri-relative+0":"vinerea aceasta","field-fri-relative+1":"vinerea viitoare","field-day":"Zi","days-format-wide":"duminic\u0103 luni mar\u021bi miercuri joi vineri s\u00e2mb\u0103t\u0103".split(" "),"field-zone":"Fus orar","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"anul trecut","field-month-relative+-1":"luna trecut\u0103","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a",
"dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Dum Lun Mar Mie Joi Vin S\u00e2m".split(" "),eraNames:["AH"],"days-format-narrow":"DLMMJVS".split(""),"dateFormatItem-yyyyMd":"dd.MM.y G","field-month":"Lun\u0103","days-standAlone-narrow":"DLMMJVS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"mar\u021bea aceasta","field-tue-relative+1":"mar\u021bea viitoare","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"a.m.",
"dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"lunea aceasta","field-mon-relative+1":"lunea viitoare","dateFormat-short":"dd.MM.y GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Secund\u0103","field-sat-relative+-1":"s\u00e2mb\u0103ta trecut\u0103","field-sun-relative+-1":"duminica trecut\u0103","field-month-relative+0":"luna aceasta",
"field-month-relative+1":"luna viitoare","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E d","field-week":"S\u0103pt\u0103m\u00e2n\u0103","dateFormat-medium":"dd.MM.y G","field-week-relative+-1":"s\u0103pt\u0103m\u00e2na trecut\u0103","field-year-relative+0":"anul acesta","dateFormatItem-yyyyM":"MM.y G","field-year-relative+1":"anul viitor","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss",
"dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"lunea trecut\u0103","dateFormatItem-yyyy":"y G","field-week-relative+0":"s\u0103pt\u0103m\u00e2na aceasta","field-week-relative+1":"s\u0103pt\u0103m\u00e2na viitoare","field-day-relative+2":"poim\u00e2ine","field-day-relative+-2":"alalt\u0103ieri",_localized:{}},"widgets/ParcelDrafter/nls/strings":{_widgetLabel:"Instrument de schi\u0163are a parcelelor",newTraverseButtonLabel:"Pornire transversal\u0103 nou\u0103",
invalidConfigMsg:"Configurare incorect\u0103",geometryServiceURLNotFoundMSG:"Imposibil de ob\u0163inut URL-ul serviciului de geometrie",editTraverseButtonLabel:"Editare transversal\u0103",mapTooltipForStartNewTraverse:"Selecta\u0163i un punct pe hart\u0103, sau introduce\u0163i mai jos, pentru a \u00eencepe",mapTooltipForEditNewTraverse:"Selecta\u0163i o parcel\u0103 pentru a o edita",mapTooltipForUpdateStartPoint:"Face\u0163i clic pentru a actualiza punctul de \u00eenceput",mapTooltipForScreenDigitization:"Face\u0163i clic pentru a ad\u0103uga un punct la parcel\u0103",
mapTooltipForUpdatingRotaionPoint:"Face\u021bi clic pentru a actualiza punctul de rotire",mapTooltipForRotate:"Tragere pentru rotire",mapTooltipForScale:"Trage\u0163i pentru a scala",backButtonTooltip:"\u00cenapoi",newTraverseTitle:"Transversal\u0103 nou\u0103",editTraverseTitle:"Editare transversal\u0103",clearingDataConfirmationMessage:"Modific\u0103rile vor fi anulate, dori\u0163i s\u0103 continua\u0163i?",unableToFetchParcelMessage:"Imposibil de preluat parcela.",unableToFetchParcelLinesMessage:"Imposibil de preluat liniile parcelei.",
planSettings:{planSettingsTitle:"Set\u0103ri",directionOrAngleTypeLabel:"Tip direc\u0163ie sau unghi",directionOrAngleUnitsLabel:"Unit\u0103\u0163i direc\u0163ie sau unghi",distanceAndLengthUnitsLabel:"Unit\u0103\u0163i distan\u0163\u0103 \u015fi lungime",areaUnitsLabel:"Unit\u0103\u0163i suprafa\u0163\u0103",circularCurveParameters:"Parametri curb\u0103 circular\u0103",northAzimuth:"Azimut nord",southAzimuth:"Azimut sud",quadrantBearing:"Azimut cvadrant",radiusAndChordLength:"Lungime raz\u0103 \u015fi coard\u0103",
radiusAndArcLength:"Lungime raz\u0103 \u015fi arc",expandGridTooltipText:"Extindere gril\u0103",collapseGridTooltipText:"Restr\u00e2ngere gril\u0103",zoomToLocationTooltipText:"Zoom la loca\u0163ie",onScreenDigitizationTooltipText:"Digitalizare",updateRotationPointTooltipText:"Actualizarea punctului de rotire"},traverseSettings:{bearingLabel:"Azimut",lengthLabel:"Lungime",radiusLabel:"Raz\u0103",noMiscloseCalculated:"\u00cenchidere eronat\u0103 necalculat\u0103",traverseMiscloseBearing:"Azimut \u00eenchidere eronat\u0103",
traverseAccuracy:"Precizie",accuracyHigh:"Ridicat",traverseDistance:"Distan\u0163\u0103 \u00eenchidere eronat\u0103",traverseMiscloseRatio:"Raport \u00eenchidere eronat\u0103",traverseStatedArea:"Suprafa\u0163\u0103 declarat\u0103",traverseCalculatedArea:"Suprafa\u0163\u0103 calculat\u0103",addButtonTitle:"Ad\u0103ugare",deleteButtonTitle:"Eliminare"},parcelTools:{rotationToolLabel:"Unghi",scaleToolLabel:"Scar\u0103"},newTraverse:{invalidBearingMessage:"Azimut nevalid.",invalidLengthMessage:"Lungime nevalid\u0103.",
invalidRadiusMessage:"Raz\u0103 nevalid\u0103.",negativeLengthMessage:"Valid doar pentru curbe",enterValidValuesMessage:"Introduce\u0163i valori valide.",enterValidParcelInfoMessage:"Introduce\u0163i informa\u0163ii valide despre parcel\u0103 pentru a salva.",unableToDrawLineMessage:"Imposibil de trasat linia.",invalidEndPointMessage:"Punct final nevalid, imposibil de trasat linia.",lineTypeLabel:"Tip de linie"},planInfo:{requiredText:"(obligatoriu)",optionalText:"(op\u0163ional)",parcelNamePlaceholderText:"Nume parcel\u0103",
parcelDocumentTypeText:"Tip document",planNamePlaceholderText:"Nume plan",cancelButtonLabel:"Anulare",saveButtonLabel:"Salvare",saveNonClosedParcelConfirmationMessage:"Parcela introdus\u0103 nu este \u00eenchis\u0103, dori\u0163i s\u0103 continua\u0163i \u015fi s\u0103 salva\u0163i doar liniile parcelei?",unableToCreatePolygonParcel:"Imposibil de creat poligonul parcelei.",unableToSavePolygonParcel:"Imposibil de salvat poligonul parcelei.",unableToSaveParcelLines:"Imposibil de salvat liniile parcelei.",
unableToUpdateParcelLines:"Imposibil de actualizat liniile parcelei.",parcelSavedSuccessMessage:"Parcel\u0103 salvat\u0103 cu succes.",parcelDeletedSuccessMessage:"Parcel\u0103 \u0219tears\u0103 cu succes.",parcelDeleteErrorMessage:"Eroare la \u0219tergerea parcelei.",enterValidParcelNameMessage:"Introduce\u0163i un nume de parcel\u0103 valid.",enterValidPlanNameMessage:"Introduce\u0163i un nume de plan valid.",enterValidDocumentTypeMessage:"Tip document nevalid.",enterValidStatedAreaNameMessage:"Introduce\u0163i o suprafa\u0163\u0103 declarat\u0103 valid\u0103.",
showAttributeList:"Ar\u0103ta\u021bi lista atributelor",hideAttributeList:"Ascunde\u021bi lista atributelor"},xyInput:{explanation:"Introduce\u021bi coordonatele \u00een aceea\u0219i referin\u021b\u0103 spa\u021bial\u0103 ca stratul tematic"},_localized:{}}});