// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Lihavointi",copy:"Kopioi",cut:"Leikkaa","delete":"Poista",indent:"Sisenn\u00e4",insertHorizontalRule:"Vaakasuuntainen viiva",insertOrderedList:"Numeroitu luettelo",insertUnorderedList:"Numeroimaton luettelo",italic:"Kursivointi",justifyCenter:"Tasaus keskelle",justifyFull:"Tasaus",justifyLeft:"Tasaus vasemmalle",justifyRight:"Tasaus oikealle",outdent:"Ulonna",paste:"Liit\u00e4",redo:"Tee uudelleen",removeFormat:"Poista muotoilu",selectAll:"Valitse kaikki",
strikethrough:"Yliviivaus",subscript:"Alennettu",superscript:"Korotettu",underline:"Alleviivaus",undo:"Kumoa",unlink:"Poista linkki",createLink:"Luo linkki",toggleDir:"Vaihda suuntaa",insertImage:"Lis\u00e4\u00e4 kuva",insertTable:"Lis\u00e4\u00e4 taulukko/muokkaa taulukkoa",toggleTableBorder:"Ota taulukon kehys k\u00e4ytt\u00f6\u00f6n/poista kehys k\u00e4yt\u00f6st\u00e4",deleteTable:"Poista taulukko",tableProp:"Taulukon ominaisuudet",htmlToggle:"HTML-l\u00e4hde",foreColor:"Edustav\u00e4ri",hiliteColor:"Taustav\u00e4ri",
plainFormatBlock:"Kappaletyyli",formatBlock:"Kappaletyyli",fontSize:"Fonttikoko",fontName:"Fontin nimi",tabIndent:"Sarkainsisennys",fullScreen:"Vaihda koko n\u00e4ytt\u00f6",viewSource:"N\u00e4yt\u00e4 HTML-l\u00e4hde",print:"Tulosta",newPage:"Uusi sivu",systemShortcut:'Toiminto "${0}" on k\u00e4ytett\u00e4viss\u00e4 selaimessa vain n\u00e4pp\u00e4imist\u00f6n pikatoiminnolla. K\u00e4yt\u00e4 seuraavaa: ${1}.',ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a",
"days-standAlone-short":"su ma ti ke to pe la".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"nyt","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"viikonp\u00e4iv\u00e4","field-wed-relative+0":"t\u00e4n\u00e4 keskiviikkona","field-wed-relative+1":"ensi keskiviikkona","dateFormatItem-GyMMMEd":"E d. MMM y G","dateFormatItem-MMMEd":"ccc d. MMM",eraNarrow:["AH"],"field-tue-relative+-1":"viime tiistaina","days-format-short":"su ma ti ke to pe la".split(" "),
"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d. MMMM y G","field-fri-relative+-1":"viime perjantaina","field-wed-relative+-1":"viime keskiviikkona","months-format-wide":"muharram;safar;rabi\u2019 al-awwal;rabi\u2019 al-akhir;d\u017eumada-l-ula;d\u017eumada-l-akhira;rad\u017eab;\u0161a\u2019ban;ramadan;\u0161awwal;dhu-l-qa\u2019da;dhu-l-hidd\u017ea".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"ip.","dateFormat-full":"cccc d. MMMM y G",
"dateFormatItem-yyyyMEd":"E d.M.y G","field-thu-relative+-1":"viime torstaina","dateFormatItem-Md":"d.M.","dayPeriods-format-abbr-am":"ap.","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"aikakausi","months-standAlone-wide":"muharram;safar;rabi\u2019 al-awwal;rabi\u2019 al-akhir;d\u017eumada-l-ula;d\u017eumada-l-akhira;rad\u017eab;\u0161a\u2019ban;ramadan;\u0161awwal;dhu-l-qa\u2019da;dhu-l-hidd\u017ea".split(";"),"timeFormat-short":"H.mm","quarters-format-wide":["1. nelj\u00e4nnes",
"2. nelj\u00e4nnes","3. nelj\u00e4nnes","4. nelj\u00e4nnes"],"timeFormat-long":"H.mm.ss z","field-year":"vuosi","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"tunti","months-format-abbr":"muharram;safar;rabi\u2019 al-awwal;rabi\u2019 al-akhir;d\u017eumada-l-ula;d\u017eumada-l-akhira;rad\u017eab;\u0161a\u2019ban;ramadan;\u0161awwal;dhu-l-qa\u2019da;dhu-l-hidd\u017ea".split(";"),"field-sat-relative+0":"t\u00e4n\u00e4 lauantaina","field-sat-relative+1":"ensi lauantaina","timeFormat-full":"H.mm.ss zzzz",
"dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"t\u00e4n\u00e4\u00e4n","field-thu-relative+0":"t\u00e4n\u00e4 torstaina","field-day-relative+1":"huomenna","field-thu-relative+1":"ensi torstaina","dateFormatItem-GyMMMd":"d. MMM y G","dateFormatItem-H":"H","months-standAlone-abbr":"muharram;safar;rabi\u2019 al-awwal;rabi\u2019 al-akhir;d\u017eumada-l-ula;d\u017eumada-l-akhira;rad\u017eab;\u0161a\u2019ban;ramadan;\u0161awwal;dhu-l-qa\u2019da;dhu-l-hidd\u017ea".split(";"),"quarters-format-abbr":["1. nelj.",
"2. nelj.","3. nelj.","4. nelj."],"quarters-standAlone-wide":["1. nelj\u00e4nnes","2. nelj\u00e4nnes","3. nelj\u00e4nnes","4. nelj\u00e4nnes"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E d. MMM y G","dateFormatItem-M":"L","days-standAlone-wide":"sunnuntai maanantai tiistai keskiviikko torstai perjantai lauantai".split(" "),"dateFormatItem-yyyyMMM":"LLL y G","dateFormatItem-yyyyMMMd":"d. MMM y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"H.mm.ss","field-sun-relative+0":"t\u00e4n\u00e4 sunnuntaina",
"dateFormatItem-Hm":"H.mm","field-sun-relative+1":"ensi sunnuntaina","quarters-standAlone-abbr":["1. nelj.","2. nelj.","3. nelj.","4. nelj."],eraAbbr:["AH"],"field-minute":"minuutti","field-dayperiod":"vuorokaudenaika","days-standAlone-abbr":"su ma ti ke to pe la".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm.ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"eilen","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"ap.","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d. MMM",
"dateFormatItem-MEd":"E d.M.","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"t\u00e4n\u00e4 perjantaina","field-fri-relative+1":"ensi perjantaina","field-day":"p\u00e4iv\u00e4","days-format-wide":"sunnuntaina maanantaina tiistaina keskiviikkona torstaina perjantaina lauantaina".split(" "),"field-zone":"aikavy\u00f6hyke","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"viime vuonna",
"field-month-relative+-1":"viime kuussa","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h.mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"ip.","days-format-abbr":"su ma ti ke to pe la".split(" "),eraNames:["AH"],"days-format-narrow":"SMTKTPL".split(""),"dateFormatItem-yyyyMd":"d.M.y G","field-month":"kuukausi","days-standAlone-narrow":"SMTKTPL".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"t\u00e4n\u00e4 tiistaina","field-tue-relative+1":"ensi tiistaina",
"dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"ap.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"t\u00e4n\u00e4 maanantaina","field-mon-relative+1":"ensi maanantaina","dateFormat-short":"d.M.y GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"sekunti","field-sat-relative+-1":"viime lauantaina",
"field-sun-relative+-1":"viime sunnuntaina","field-month-relative+0":"t\u00e4ss\u00e4 kuussa","field-month-relative+1":"ensi kuussa","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E d.","field-week":"viikko","dateFormat-medium":"d.M.y G","field-week-relative+-1":"viime viikolla","field-year-relative+0":"t\u00e4n\u00e4 vuonna","dateFormatItem-yyyyM":"L.y G","field-year-relative+1":"ensi vuonna","dayPeriods-format-narrow-pm":"ip.","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1} {0}",
"dateFormatItem-Hms":"H.mm.ss","dateFormatItem-hms":"h.mm.ss a","dateFormatItem-GyMMM":"LLL y G","field-mon-relative+-1":"viime maanantaina","dateFormatItem-yyyy":"y G","field-week-relative+0":"t\u00e4ll\u00e4 viikolla","field-week-relative+1":"ensi viikolla","field-day-relative+2":"ylihuomenna","field-day-relative+-2":"toissa p\u00e4iv\u00e4n\u00e4",_localized:{}},"widgets/ParcelDrafter/nls/strings":{_widgetLabel:"Kiinteist\u00f6jen luonnostelu",newTraverseButtonLabel:"Aloita uusi l\u00e4pik\u00e4ynti",
invalidConfigMsg:"Virheellinen m\u00e4\u00e4ritys",geometryServiceURLNotFoundMSG:"Geometriapalvelun URL-osoitetta ei voi noutaa",editTraverseButtonLabel:"Muokkaa l\u00e4pik\u00e4ynti\u00e4",mapTooltipForStartNewTraverse:"Aloita valitsemalla kartalta piste tai kirjoittamalla alle",mapTooltipForEditNewTraverse:"Valitse muokattava kiinteist\u00f6",mapTooltipForUpdateStartPoint:"P\u00e4ivit\u00e4 aloituspiste napsauttamalla",mapTooltipForScreenDigitization:"Lis\u00e4\u00e4 kiinteist\u00f6n piste napsauttamalla",
mapTooltipForUpdatingRotaionPoint:"P\u00e4ivit\u00e4 kiertopiste napsauttamalla",mapTooltipForRotate:"K\u00e4\u00e4nn\u00e4 vet\u00e4m\u00e4ll\u00e4",mapTooltipForScale:"Muuta mittakaavaa vet\u00e4m\u00e4ll\u00e4",backButtonTooltip:"Takaisin",newTraverseTitle:"Uusi l\u00e4pik\u00e4ynti",editTraverseTitle:"Muokkaa l\u00e4pik\u00e4ynti\u00e4",clearingDataConfirmationMessage:"Muutokset hyl\u00e4t\u00e4\u00e4n. Haluatko jatkaa?",unableToFetchParcelMessage:"Kiinteist\u00f6n tietoja ei voi noutaa.",unableToFetchParcelLinesMessage:"Kiinteist\u00f6n viivoja ei voi noutaa.",
planSettings:{planSettingsTitle:"Asetukset",directionOrAngleTypeLabel:"Suunta- tai kulmatyyppi",directionOrAngleUnitsLabel:"Suunta- tai kulmayksik\u00f6t",distanceAndLengthUnitsLabel:"Et\u00e4isyys- ja pituusyksik\u00f6t",areaUnitsLabel:"Pinta-alayksik\u00f6t",circularCurveParameters:"Ympyr\u00e4nmuotoisen kaaren parametrit",northAzimuth:"Pohjoinen-kompassisuunta",southAzimuth:"Etel\u00e4-kompassisuunta",quadrantBearing:"Kvadranttisuuntima",radiusAndChordLength:"S\u00e4de ja puoliympyr\u00e4n pituus",
radiusAndArcLength:"S\u00e4de ja kaaren pituus",expandGridTooltipText:"Laajenna ruudukko",collapseGridTooltipText:"Tiivist\u00e4 ruudukko",zoomToLocationTooltipText:"Tarkenna sijaintiin",onScreenDigitizationTooltipText:"Digitoi",updateRotationPointTooltipText:"P\u00e4ivit\u00e4 kiertopiste"},traverseSettings:{bearingLabel:"Suuntima",lengthLabel:"Pituus",radiusLabel:"S\u00e4de",noMiscloseCalculated:"Ep\u00e4sulkua ei ole laskettu",traverseMiscloseBearing:"Ep\u00e4sulkusuuntima",traverseAccuracy:"Tarkkuus",
accuracyHigh:"Suuri",traverseDistance:"Ep\u00e4sulkuet\u00e4isyys",traverseMiscloseRatio:"Ep\u00e4sulkusuhde",traverseStatedArea:"Ilmoitettu alue",traverseCalculatedArea:"Laskettu alue",addButtonTitle:"Lis\u00e4\u00e4",deleteButtonTitle:"Poista"},parcelTools:{rotationToolLabel:"Kulma",scaleToolLabel:"Mittakaava"},newTraverse:{invalidBearingMessage:"Virheellinen suuntima.",invalidLengthMessage:"Virheellinen pituus.",invalidRadiusMessage:"Virheellinen s\u00e4de.",negativeLengthMessage:"Kelpaa vain kaarteissa",
enterValidValuesMessage:"Anna kelvolliset arvot.",enterValidParcelInfoMessage:"Anna tallennettavat kelvolliset kiinteist\u00f6tiedot.",unableToDrawLineMessage:"Viivaa ei voi piirt\u00e4\u00e4.",invalidEndPointMessage:"Virheellinen p\u00e4\u00e4tepiste. Viivaa ei voi piirt\u00e4\u00e4.",lineTypeLabel:"Viivatyyppi"},planInfo:{requiredText:"(pakollinen)",optionalText:"(valinnainen)",parcelNamePlaceholderText:"Kiinteist\u00f6n nimi",parcelDocumentTypeText:"Dokumenttityyppi",planNamePlaceholderText:"Suunnitelman nimi",
cancelButtonLabel:"Peruuta",saveButtonLabel:"Tallenna",saveNonClosedParcelConfirmationMessage:"Annettua kiinteist\u00f6\u00e4 ei ole suljettu. Haluatko silti jatkaa ja tallentaa vain kiinteist\u00f6n viivat?",unableToCreatePolygonParcel:"Kiinteist\u00f6n aluetta ei voi luoda.",unableToSavePolygonParcel:"Kiinteist\u00f6n aluetta ei voi tallentaa.",unableToSaveParcelLines:"Kiinteist\u00f6n viivoja ei voi tallentaa.",unableToUpdateParcelLines:"Kiinteist\u00f6n viivoja ei voi p\u00e4ivitt\u00e4\u00e4.",
parcelSavedSuccessMessage:"Kiinteist\u00f6 on tallennettu.",parcelDeletedSuccessMessage:"Kiinteist\u00f6 on poistettu.",parcelDeleteErrorMessage:"Virhe kiinteist\u00f6n poistossa.",enterValidParcelNameMessage:"Kirjoita kelvollinen kiinteist\u00f6n nimi.",enterValidPlanNameMessage:"Kirjoita kelvollinen suunnitelman nimi.",enterValidDocumentTypeMessage:"Virheellinen dokumenttityyppi.",enterValidStatedAreaNameMessage:"Anna kelvollinen sovittu alue.",showAttributeList:"N\u00e4yt\u00e4 ominaisuustietoluettelo",
hideAttributeList:"Piilota ominaisuustietoluettelo"},xyInput:{explanation:"Sy\u00f6t\u00e4 koordinaatit, joiden koordinaatistotieto on sama kuin karttatasolla"},_localized:{}}});