// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Kal\u0131n",copy:"Kopyala",cut:"Kes","delete":"Sil",indent:"Girinti",insertHorizontalRule:"Yatay Kural",insertOrderedList:"Numaral\u0131 Liste",insertUnorderedList:"Madde \u0130\u015faretli Liste",italic:"\u0130talik",justifyCenter:"Ortaya Hizala",justifyFull:"Yasla",justifyLeft:"Sola Hizala",justifyRight:"Sa\u011fa Hizala",outdent:"\u00c7\u0131k\u0131nt\u0131",paste:"Yap\u0131\u015ft\u0131r",redo:"Yinele",removeFormat:"Bi\u00e7imi Kald\u0131r",selectAll:"T\u00fcm\u00fcn\u00fc Se\u00e7",
strikethrough:"\u00dcst\u00fc \u00c7izili",subscript:"Alt Simge",superscript:"\u00dcst Simge",underline:"Alt\u0131 \u00c7izili",undo:"Geri Al",unlink:"Ba\u011flant\u0131y\u0131 Kald\u0131r",createLink:"Ba\u011flant\u0131 Olu\u015ftur",toggleDir:"Y\u00f6n\u00fc De\u011fi\u015ftir",insertImage:"Resim Ekle",insertTable:"Tablo Ekle/D\u00fczenle",toggleTableBorder:"Tablo Kenarl\u0131\u011f\u0131n\u0131 G\u00f6ster/Gizle",deleteTable:"Tabloyu Sil",tableProp:"Tablo \u00d6zelli\u011fi",htmlToggle:"HTML Kayna\u011f\u0131",
foreColor:"\u00d6n Plan Rengi",hiliteColor:"Arka Plan Rengi",plainFormatBlock:"Paragraf Stili",formatBlock:"Paragraf Stili",fontSize:"Yaz\u0131 Tipi Boyutu",fontName:"Yaz\u0131 Tipi Ad\u0131",tabIndent:"Sekme Girintisi",fullScreen:"Tam Ekran\u0131 A\u00e7/Kapat",viewSource:"HTML Kayna\u011f\u0131n\u0131 G\u00f6r\u00fcnt\u00fcle",print:"Yazd\u0131r",newPage:"Yeni Sayfa",systemShortcut:'"${0}" i\u015flemi yaln\u0131zca taray\u0131c\u0131n\u0131zda bir klavye k\u0131sayoluyla birlikte kullan\u0131labilir. \u015eunu kullan\u0131n: ${1}.',
ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Pa Pt Sa \u00c7a Pe Cu Ct".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"\u015fimdi","quarters-standAlone-narrow":["1.","2.","3.","4."],"field-weekday":"Haftan\u0131n G\u00fcn\u00fc","field-wed-relative+0":"bu \u00e7ar\u015famba","field-wed-relative+1":"gelecek \u00e7ar\u015famba","dateFormatItem-GyMMMEd":"G d MMM y E",
"dateFormatItem-MMMEd":"d MMM E",eraNarrow:["Hicri"],"field-tue-relative+-1":"ge\u00e7en sal\u0131","days-format-short":"Pa Pt Sa \u00c7a Pe Cu Ct".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"G d MMMM y","field-fri-relative+-1":"ge\u00e7en cuma","field-wed-relative+-1":"ge\u00e7en \u00e7ar\u015famba","months-format-wide":"Muharrem Safer Rebi\u00fclevvel Rebi\u00fclahir Cemaziyelevvel Cemaziyelahir Recep \u015eaban Ramazan \u015eevval Zilkade Zilhicce".split(" "),
"dateFormatItem-yyyyQQQ":"G y/QQQ","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"\u00d6S","dateFormat-full":"G d MMMM y EEEE","dateFormatItem-yyyyMEd":"GGGGG dd.MM.y E","field-thu-relative+-1":"ge\u00e7en per\u015fembe","dateFormatItem-Md":"dd/MM","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Miladi D\u00f6nem","months-standAlone-wide":"Muharrem Safer Rebi\u00fclevvel Rebi\u00fclahir Cemaziyelevvel Cemaziyelahir Recep \u015eaban Ramazan \u015eevval Zilkade Zilhicce".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["1. \u00e7eyrek","2. \u00e7eyrek","3. \u00e7eyrek","4. \u00e7eyrek"],"timeFormat-long":"HH:mm:ss z","field-year":"Y\u0131l","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Saat","months-format-abbr":"Muharrem Safer Rebi\u00fclevvel Rebi\u00fclahir Cemaziyelevvel Cemaziyelahir Recep \u015eaban Ramazan \u015eevval Zilkade Zilhicce".split(" "),"field-sat-relative+0":"bu cumartesi","field-sat-relative+1":"gelecek cumartesi","timeFormat-full":"HH:mm:ss zzzz",
"dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"bug\u00fcn","field-thu-relative+0":"bu per\u015fembe","field-day-relative+1":"yar\u0131n","field-thu-relative+1":"gelecek per\u015fembe","dateFormatItem-GyMMMd":"G d MMM y","dateFormatItem-H":"HH","months-standAlone-abbr":"Muharrem Safer Rebi\u00fclevvel Rebi\u00fclahir Cemaziyelevvel Cemaziyelahir Recep \u015eaban Ramazan \u015eevval Zilkade Zilhicce".split(" "),"quarters-format-abbr":["\u00c71","\u00c72","\u00c73","\u00c74"],
"quarters-standAlone-wide":["1. \u00e7eyrek","2. \u00e7eyrek","3. \u00e7eyrek","4. \u00e7eyrek"],"dateFormatItem-Gy":"G y","dateFormatItem-yyyyMMMEd":"G d MMM y E","dateFormatItem-M":"L","days-standAlone-wide":"Pazar Pazartesi Sal\u0131 \u00c7ar\u015famba Per\u015fembe Cuma Cumartesi".split(" "),"dateFormatItem-yyyyMMM":"G MMM y","dateFormatItem-yyyyMMMd":"G dd MMM y","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"bu pazar","dateFormatItem-Hm":"HH:mm",
"field-sun-relative+1":"gelecek pazar","quarters-standAlone-abbr":["\u00c71","\u00c72","\u00c73","\u00c74"],eraAbbr:["Hicri"],"field-minute":"Dakika","field-dayperiod":"\u00d6\u00d6/\u00d6S","days-standAlone-abbr":"Paz Pzt Sal \u00c7ar Per Cum Cmt".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1.","2.","3.","4."],"field-day-relative+-1":"d\u00fcn","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d MMM",
"dateFormatItem-MEd":"dd/MM E","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"bu cuma","field-fri-relative+1":"gelecek cuma","field-day":"G\u00fcn","days-format-wide":"Pazar Pazartesi Sal\u0131 \u00c7ar\u015famba Per\u015fembe Cuma Cumartesi".split(" "),"field-zone":"Saat Dilimi","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"G y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"ge\u00e7en y\u0131l","field-month-relative+-1":"ge\u00e7en ay",
"dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Paz Pzt Sal \u00c7ar Per Cum Cmt".split(" "),eraNames:["Hicri"],"days-format-narrow":"PPS\u00c7PCC".split(""),"dateFormatItem-yyyyMd":"GGGGG dd.MM.y","field-month":"Ay","days-standAlone-narrow":"PPS\u00c7PCC".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"bu sal\u0131","field-tue-relative+1":"gelecek sal\u0131",
"dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"\u00d6\u00d6","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"bu pazartesi","field-mon-relative+1":"gelecek pazartesi","dateFormat-short":"GGGGG d.MM.y","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Saniye","field-sat-relative+-1":"ge\u00e7en cumartesi",
"field-sun-relative+-1":"ge\u00e7en pazar","field-month-relative+0":"bu ay","field-month-relative+1":"gelecek ay","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"d E","field-week":"Hafta","dateFormat-medium":"G d MMM y","field-week-relative+-1":"ge\u00e7en hafta","field-year-relative+0":"bu y\u0131l","dateFormatItem-yyyyM":"GGGGG M/y","field-year-relative+1":"gelecek y\u0131l","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"G y/QQQQ","dateTimeFormat-short":"{1} {0}",
"dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"G MMM y","field-mon-relative+-1":"ge\u00e7en pazartesi","dateFormatItem-yyyy":"G y","field-week-relative+0":"bu hafta","field-week-relative+1":"gelecek hafta","field-day-relative+2":"\u00f6b\u00fcr g\u00fcn","field-day-relative+-2":"evvelsi g\u00fcn",_localized:{}},"widgets/ParcelDrafter/nls/strings":{_widgetLabel:"Yap\u0131 Tasla\u011f\u0131 Olu\u015fturucu",newTraverseButtonLabel:"Yeni \u00c7apraz \u00c7izgi Ba\u015flat",
invalidConfigMsg:"Ge\u00e7ersiz Yap\u0131land\u0131rma",geometryServiceURLNotFoundMSG:"Geometri Servisi URL\u2019si al\u0131nam\u0131yor",editTraverseButtonLabel:"\u00c7apraz \u00c7izgiyi D\u00fczenle",mapTooltipForStartNewTraverse:"Ba\u015flamak i\u00e7in haritada bir nokta se\u00e7in veya a\u015fa\u011f\u0131ya girin",mapTooltipForEditNewTraverse:"D\u00fczenlenecek yap\u0131y\u0131 se\u00e7in",mapTooltipForUpdateStartPoint:"Ba\u015flang\u0131\u00e7 noktas\u0131n\u0131 g\u00fcncellemek i\u00e7in t\u0131klay\u0131n",
mapTooltipForScreenDigitization:"Yap\u0131 noktas\u0131 eklemek i\u00e7in t\u0131klay\u0131n",mapTooltipForUpdatingRotaionPoint:"D\u00f6nd\u00fcrme noktas\u0131n\u0131 g\u00fcncellemek i\u00e7in t\u0131klay\u0131n",mapTooltipForRotate:"D\u00f6nd\u00fcrmek i\u00e7in s\u00fcr\u00fckleyin",mapTooltipForScale:"\u00d6l\u00e7eklendirmek i\u00e7in s\u00fcr\u00fckleyin",backButtonTooltip:"Geri",newTraverseTitle:"Yeni \u00c7apraz \u00c7izgi",editTraverseTitle:"\u00c7apraz \u00c7izgiyi D\u00fczenle",clearingDataConfirmationMessage:"De\u011fi\u015fiklikler at\u0131lacak, devam etmek istiyor musunuz?",
unableToFetchParcelMessage:"Yap\u0131 al\u0131nam\u0131yor.",unableToFetchParcelLinesMessage:"Yap\u0131 \u00e7izgileri al\u0131nam\u0131yor.",planSettings:{planSettingsTitle:"Ayarlar",directionOrAngleTypeLabel:"Y\u00f6n veya A\u00e7\u0131 T\u00fcr\u00fc",directionOrAngleUnitsLabel:"Y\u00f6n veya A\u00e7\u0131 Birimi",distanceAndLengthUnitsLabel:"Mesafe ve Uzunluk Birimleri",areaUnitsLabel:"Alan Birimleri:",circularCurveParameters:"Dairesel E\u011fri Parametreleri",northAzimuth:"Kuzey Azimut",southAzimuth:"G\u00fcney Azimut",
quadrantBearing:"\u00c7eyrek Semt A\u00e7\u0131s\u0131",radiusAndChordLength:"Yar\u0131\u00e7ap ve Kiri\u015f Uzunlu\u011fu",radiusAndArcLength:"Yar\u0131\u00e7ap ve Yay Uzunlu\u011fu",expandGridTooltipText:"K\u0131lavuzu geni\u015flet",collapseGridTooltipText:"K\u0131lavuzu daralt",zoomToLocationTooltipText:"Konuma yakla\u015ft\u0131r",onScreenDigitizationTooltipText:"Say\u0131salla\u015ft\u0131rma",updateRotationPointTooltipText:"D\u00f6nd\u00fcrme noktas\u0131n\u0131 g\u00fcncelle"},traverseSettings:{bearingLabel:"Y\u00f6n",
lengthLabel:"Uzunluk",radiusLabel:"Yar\u0131\u00e7ap",noMiscloseCalculated:"Kapanmama hesaplanamad\u0131",traverseMiscloseBearing:"Kapanmama Y\u00f6n\u00fc",traverseAccuracy:"Do\u011fruluk",accuracyHigh:"Y\u00fcksek",traverseDistance:"Kapanmama Mesafesi",traverseMiscloseRatio:"Kapanmama Oran\u0131",traverseStatedArea:"Belirtilen Alan",traverseCalculatedArea:"Hesaplanan Alan",addButtonTitle:"Ekle",deleteButtonTitle:"Kald\u0131r"},parcelTools:{rotationToolLabel:"A\u00e7\u0131",scaleToolLabel:"\u00d6l\u00e7ek"},
newTraverse:{invalidBearingMessage:"Ge\u00e7ersiz Y\u00f6n.",invalidLengthMessage:"Ge\u00e7ersiz Uzunluk.",invalidRadiusMessage:"Ge\u00e7ersiz Yar\u0131\u00e7ap.",negativeLengthMessage:"Yaln\u0131zca e\u011friler i\u00e7in ge\u00e7erlidir",enterValidValuesMessage:"Ge\u00e7erli de\u011fer girin.",enterValidParcelInfoMessage:"Kaydedilecek ge\u00e7erli yap\u0131 bilgisi girin.",unableToDrawLineMessage:"\u00c7izgi \u00e7izilemiyor.",invalidEndPointMessage:"Ge\u00e7ersiz Biti\u015f Noktas\u0131, \u00e7izgi \u00e7izilemiyor.",
lineTypeLabel:"\u00c7izgi Tipi"},planInfo:{requiredText:"(gerekli)",optionalText:"(iste\u011fe ba\u011fl\u0131)",parcelNamePlaceholderText:"Yap\u0131 ad\u0131",parcelDocumentTypeText:"Belge t\u00fcr\u00fc",planNamePlaceholderText:"Plan ad\u0131",cancelButtonLabel:"\u0130ptal Et",saveButtonLabel:"Kaydet",saveNonClosedParcelConfirmationMessage:"Girilen yap\u0131 kapat\u0131lmam\u0131\u015f, yine de devam etmek ve yaln\u0131zca yap\u0131 \u00e7izgilerini kaydetmek istiyor musunuz?",unableToCreatePolygonParcel:"Yap\u0131 alan\u0131 olu\u015fturulam\u0131yor.",
unableToSavePolygonParcel:"Yap\u0131 alan\u0131 kaydedilemiyor.",unableToSaveParcelLines:"Yap\u0131 \u00e7izgileri kaydedilemiyor.",unableToUpdateParcelLines:"Yap\u0131 \u00e7izgileri g\u00fcncellenemiyor.",parcelSavedSuccessMessage:"Yap\u0131 ba\u015far\u0131yla kaydedildi.",parcelDeletedSuccessMessage:"Parsel ba\u015far\u0131yla silindi.",parcelDeleteErrorMessage:"Parselin silinmesinde hata olu\u015ftu.",enterValidParcelNameMessage:"Ge\u00e7erli yap\u0131 ad\u0131 girin.",enterValidPlanNameMessage:"Ge\u00e7erli plan ad\u0131 girin.",
enterValidDocumentTypeMessage:"Ge\u00e7ersiz belge t\u00fcr\u00fc.",enterValidStatedAreaNameMessage:"Ge\u00e7erli belirtilen alan girin.",showAttributeList:"\u00d6znitelik listesini g\u00f6ster",hideAttributeList:"\u00d6znitelik listesini gizle"},xyInput:{explanation:"Koordinatlar\u0131 katman olarak ayn\u0131 mekansal referansta girin"},_localized:{}}});