// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Gras",copy:"Copier",cut:"Couper","delete":"Supprimer",indent:"Retrait",insertHorizontalRule:"R\u00e8gle horizontale",insertOrderedList:"Liste num\u00e9rot\u00e9e",insertUnorderedList:"Liste \u00e0 puces",italic:"Italique",justifyCenter:"Aligner au centre",justifyFull:"Justifier",justifyLeft:"Aligner \u00e0 gauche",justifyRight:"Aligner \u00e0 droite",outdent:"Retrait n\u00e9gatif",paste:"Coller",redo:"R\u00e9tablir",removeFormat:"Supprimer la mise en forme",
selectAll:"S\u00e9lectionner tout",strikethrough:"Barrer",subscript:"Indice",superscript:"Exposant",underline:"Souligner",undo:"Annuler",unlink:"Supprimer le lien",createLink:"Cr\u00e9er un lien",toggleDir:"Changer de sens",insertImage:"Ins\u00e9rer une image",insertTable:"Ins\u00e9rer/Modifier un tableau",toggleTableBorder:"Afficher/Masquer la bordure du tableau",deleteTable:"Supprimer le tableau",tableProp:"Propri\u00e9t\u00e9 du tableau",htmlToggle:"Source HTML",foreColor:"Couleur avant-plan",
hiliteColor:"Couleur arri\u00e8re-plan",plainFormatBlock:"Style de paragraphe",formatBlock:"Style de paragraphe",fontSize:"Taille de police",fontName:"Nom de police",tabIndent:"Retrait de tabulation",fullScreen:"Basculer en plein \u00e9cran",viewSource:"Afficher la source HTML",print:"Imprimer",newPage:"Nouvelle page",systemShortcut:'Action "${0}" uniquement disponible dans votre navigateur via un raccourci clavier. Utilisez ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a",
"days-standAlone-short":"Di Lu Ma Me Je Ve Sa".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"maintenant","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"jour de la semaine","field-wed-relative+0":"ce mercredi","field-wed-relative+1":"mercredi prochain","dateFormatItem-GyMMMEd":"E d MMM y G","dateFormatItem-MMMEd":"E d MMM",eraNarrow:["AH"],"field-tue-relative+-1":"mardi dernier","days-format-short":"di lu ma me je ve sa".split(" "),
"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d MMMM y G","field-fri-relative+-1":"vendredi dernier","field-wed-relative+-1":"mercredi dernier","months-format-wide":"mouharram;safar;rabia al awal;rabia ath-thani;joumada al oula;joumada ath-thania;rajab;chaabane;ramadan;chawwal;dhou al qi`da;dhou al-hijja".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE d MMMM y G","dateFormatItem-yyyyMEd":"E d/M/y GGGGG",
"field-thu-relative+-1":"jeudi dernier","dateFormatItem-Md":"dd/MM","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"midi","field-era":"\u00e8re","months-standAlone-wide":"mouharram;safar;rabia al awal;rabia ath-thani;joumada al oula;joumada ath-thania;rajab;chaabane;ramadan;chawwal;dhou al qi`da;dhou al-hijja".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["1er trimestre","2e trimestre","3e trimestre","4e trimestre"],
"timeFormat-long":"HH:mm:ss z","field-year":"ann\u00e9e","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"heure","months-format-abbr":"mouh.;saf.;rab. aw.;rab. th.;joum. oul.;joum. tha.;raj.;chaa.;ram.;chaw.;dhou. q.;dhou. h.".split(";"),"field-sat-relative+0":"ce samedi","field-sat-relative+1":"samedi prochain","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"aujourd\u2019hui","field-thu-relative+0":"ce jeudi","field-day-relative+1":"demain",
"field-thu-relative+1":"jeudi prochain","dateFormatItem-GyMMMd":"d MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"mouh.;saf.;rab. aw.;rab. th.;joum. ou.;joum. th.;raj.;chaa.;ram.;chaw.;dhou. qi.;dhou. hi.".split(";"),"quarters-format-abbr":["T1","T2","T3","T4"],"quarters-standAlone-wide":["1er trimestre","2e trimestre","3e trimestre","4e trimestre"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E d MMM y G","dateFormatItem-M":"L","days-standAlone-wide":"Dimanche Lundi Mardi Mercredi Jeudi Vendredi Samedi".split(" "),
"dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d MMM y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"ce dimanche","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"dimanche prochain","quarters-standAlone-abbr":["T1","T2","T3","T4"],eraAbbr:["AH"],"field-minute":"minute","field-dayperiod":"cadran","days-standAlone-abbr":"Dim. Lun. Mar. Mer. Jeu. Ven. Sam.".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1",
"2","3","4"],"field-day-relative+-1":"hier","dateTimeFormat-long":"{1} '\u00e0' {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E dd/MM","dateTimeFormat-full":"{1} '\u00e0' {0}","field-fri-relative+0":"ce vendredi","field-fri-relative+1":"vendredi prochain","field-day":"jour","days-format-wide":"dimanche lundi mardi mercredi jeudi vendredi samedi".split(" "),"field-zone":"fuseau horaire","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),
"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"l\u2019ann\u00e9e derni\u00e8re","field-month-relative+-1":"le mois dernier","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"dim. lun. mar. mer. jeu. ven. sam.".split(" "),eraNames:["AH"],"days-format-narrow":"DLMMJVS".split(""),"dateFormatItem-yyyyMd":"d/M/y GGGGG","field-month":"mois",
"days-standAlone-narrow":"DLMMJVS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"ce mardi","field-tue-relative+1":"mardi prochain","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"ce lundi","field-mon-relative+1":"lundi prochain","dateFormat-short":"dd/MM/y GGGGG","dateFormatItem-EHms":"E HH:mm:ss",
"dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"midi","field-second":"seconde","field-sat-relative+-1":"samedi dernier","field-sun-relative+-1":"dimanche dernier","field-month-relative+0":"ce mois-ci","field-month-relative+1":"le mois prochain","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E d","field-week":"semaine","dateFormat-medium":"d MMM y G","field-week-relative+-1":"la semaine derni\u00e8re","field-year-relative+0":"cette ann\u00e9e","dateFormatItem-yyyyM":"M/y GGGGG",
"field-year-relative+1":"l\u2019ann\u00e9e prochaine","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"lundi dernier","dateFormatItem-yyyy":"y G","field-week-relative+0":"cette semaine","field-week-relative+1":"la semaine prochaine","dateFormatItem-yyyyMMMM":"MMMM y G","field-day-relative+2":"apr\u00e8s-demain","field-day-relative+-2":"avant-hier",
_localized:{}},"widgets/ParcelDrafter/nls/strings":{_widgetLabel:"Dessinateur de parcelles",newTraverseButtonLabel:"D\u00e9marrer un nouveau parcours",invalidConfigMsg:"Configuration non valide",geometryServiceURLNotFoundMSG:"Impossible d'obtenir l'URL du service de g\u00e9om\u00e9trie",editTraverseButtonLabel:"Modifier le parcours",mapTooltipForStartNewTraverse:"S\u00e9lectionnez un point sur la carte ou tapez ci-dessous pour commencer",mapTooltipForEditNewTraverse:"S\u00e9lectionnez une parcelle \u00e0 modifier",
mapTooltipForUpdateStartPoint:"Cliquez pour mettre \u00e0 jour le point de d\u00e9part",mapTooltipForScreenDigitization:"Cliquez pour ajouter un point de parcelle",mapTooltipForUpdatingRotaionPoint:"Cliquer pour mettre \u00e0 jour le point de rotation",mapTooltipForRotate:"Faites glisser pour faire pivoter",mapTooltipForScale:"Faire glisser pour mettre \u00e0 l'\u00e9chelle",backButtonTooltip:"Pr\u00e9c\u00e9dent",newTraverseTitle:"Nouveau parcours",editTraverseTitle:"Modifier le parcours",clearingDataConfirmationMessage:"Les modifications seront ignor\u00e9es. Voulez-vous continuer\u00a0?",
unableToFetchParcelMessage:"Impossible d'extraire la parcelle.",unableToFetchParcelLinesMessage:"Impossible d'extraire les lignes de parcelle.",planSettings:{planSettingsTitle:"Param\u00e8tres",directionOrAngleTypeLabel:"Type de direction ou d'angle",directionOrAngleUnitsLabel:"Unit\u00e9s de direction ou d'angle",distanceAndLengthUnitsLabel:"Unit\u00e9s de distance et de longueur",areaUnitsLabel:"Unit\u00e9s de surface",circularCurveParameters:"Param\u00e8tres de courbe circulaire",northAzimuth:"Nord azimutal",
southAzimuth:"Sud azimutal",quadrantBearing:"Orientation au quadrant",radiusAndChordLength:"Rayon et longueur de corde",radiusAndArcLength:"Rayon et longueur d'arc",expandGridTooltipText:"D\u00e9velopper la grille",collapseGridTooltipText:"R\u00e9duire la grille",zoomToLocationTooltipText:"Zoom sur l'emplacement",onScreenDigitizationTooltipText:"Num\u00e9riser",updateRotationPointTooltipText:"Mettre \u00e0 jour le point de rotation"},traverseSettings:{bearingLabel:"Orientation",lengthLabel:"Longueur",
radiusLabel:"Rayon",noMiscloseCalculated:"Ecart de fermeture non calcul\u00e9",traverseMiscloseBearing:"Misclose Bearing",traverseAccuracy:"Pr\u00e9cision",accuracyHigh:"Elev\u00e9e",traverseDistance:"Distance d'\u00e9cart de fermeture",traverseMiscloseRatio:"Taux d'\u00e9cart de fermeture",traverseStatedArea:"Zone indiqu\u00e9e",traverseCalculatedArea:"Zone calcul\u00e9e",addButtonTitle:"Ajouter",deleteButtonTitle:"Supprimer"},parcelTools:{rotationToolLabel:"Angle",scaleToolLabel:"Echelle"},newTraverse:{invalidBearingMessage:"Orientation non valide.",
invalidLengthMessage:"Longueur non valide.",invalidRadiusMessage:"Rayon non valide.",negativeLengthMessage:"Valide uniquement pour les courbes",enterValidValuesMessage:"Entrez des valeurs valides.",enterValidParcelInfoMessage:"Entrez des informations de parcelle valides \u00e0 enregistrer.",unableToDrawLineMessage:"Impossible de tracer une ligne.",invalidEndPointMessage:"Point de fin non valide. Impossible de tracer la ligne.",lineTypeLabel:"Type de ligne"},planInfo:{requiredText:"(obligatoire)",
optionalText:"(facultatif)",parcelNamePlaceholderText:"Nom de parcelle",parcelDocumentTypeText:"Type de document",planNamePlaceholderText:"Nom du plan",cancelButtonLabel:"Annuler",saveButtonLabel:"Enregistrer",saveNonClosedParcelConfirmationMessage:"La parcelle entr\u00e9e n'est pas ferm\u00e9e. Voulez-vous cependant continuer et enregistrer uniquement les lignes de la parcelle\u00a0?",unableToCreatePolygonParcel:"Impossible de cr\u00e9er le polygone de parcelle.",unableToSavePolygonParcel:"Impossible d'enregistrer le polygone de parcelle.",
unableToSaveParcelLines:"Impossible d'enregistrer les lignes de parcelle.",unableToUpdateParcelLines:"Impossible de mettre \u00e0 jour les lignes de parcelle.",parcelSavedSuccessMessage:"Parcelle enregistr\u00e9e avec succ\u00e8s.",parcelDeletedSuccessMessage:"Parcelle supprim\u00e9e avec succ\u00e8s.",parcelDeleteErrorMessage:"Erreur lors de la suppression de la parcelle.",enterValidParcelNameMessage:"Entrez un nom de parcelle valide.",enterValidPlanNameMessage:"Entrez un nom de plan valide.",enterValidDocumentTypeMessage:"Type de document non valide",
enterValidStatedAreaNameMessage:"Entrez une zone indiqu\u00e9e valide.",showAttributeList:"Afficher la liste des attributs",hideAttributeList:"Masquer la liste des attributs"},xyInput:{explanation:"Entrez les coordonn\u00e9es dans la m\u00eame r\u00e9f\u00e9rence spatiale que celle utilis\u00e9e pour la couche"},_localized:{}}});