// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fett",copy:"Kopieren",cut:"Ausschneiden","delete":"L\u00f6schen",indent:"Einr\u00fccken",insertHorizontalRule:"Horizontaler Strich",insertOrderedList:"Nummerierung",insertUnorderedList:"Aufz\u00e4hlungszeichen",italic:"Kursiv",justifyCenter:"Zentriert",justifyFull:"Blocksatz",justifyLeft:"Linksb\u00fcndig",justifyRight:"Rechtsb\u00fcndig",outdent:"Ausr\u00fccken",paste:"Einf\u00fcgen",redo:"Wiederholen",removeFormat:"Formatierung entfernen",selectAll:"Alles ausw\u00e4hlen",
strikethrough:"Durchgestrichen",subscript:"Tiefgestellt",superscript:"Hochgestellt",underline:"Unterstrichen",undo:"R\u00fcckg\u00e4ngig",unlink:"Link entfernen",createLink:"Link erstellen",toggleDir:"Richtung wechseln",insertImage:"Grafik einf\u00fcgen",insertTable:"Tabelle einf\u00fcgen/bearbeiten",toggleTableBorder:"Tabellenumrandung ein-/ausschalten",deleteTable:"Tabelle l\u00f6schen",tableProp:"Tabelleneigenschaft",htmlToggle:"HTML-Quelltext",foreColor:"Vordergrundfarbe",hiliteColor:"Hintergrundfarbe",
plainFormatBlock:"Absatzstil",formatBlock:"Absatzstil",fontSize:"Schriftgr\u00f6\u00dfe",fontName:"Schriftartname",tabIndent:"Registerkarteneinr\u00fcckung",fullScreen:"Gesamtanzeige",viewSource:"HTML-Quelle",print:"Drucken",newPage:"Neue Seite",systemShortcut:'Die Aktion "${0}" ist nur \u00fcber einen Direktaufruf in Ihrem Browser verf\u00fcgbar. Verwenden Sie ${1}.',ctrlKey:"Strg+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"So. Mo. Di. Mi. Do. Fr. Sa.".split(" "),
"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"jetzt","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Wochentag","field-wed-relative+0":"diesen Mittwoch","field-wed-relative+1":"n\u00e4chsten Mittwoch","dateFormatItem-GyMMMEd":"E, d. MMM y G","dateFormatItem-MMMEd":"E, d. MMM",eraNarrow:["AH"],"field-tue-relative+-1":"letzten Dienstag","days-format-short":"So. Mo. Di. Mi. Do. Fr. Sa.".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d. MMMM y G","field-fri-relative+-1":"letzten Freitag","field-wed-relative+-1":"letzten Mittwoch","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"nachm.","dateFormat-full":"EEEE, d. MMMM y G","dateFormatItem-yyyyMEd":"E, d.M.y GGGGG","field-thu-relative+-1":"letzten Donnerstag",
"dateFormatItem-Md":"d.M.","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"mittags","field-era":"Epoche","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["1. Quartal","2. Quartal","3. Quartal","4. Quartal"],"timeFormat-long":"HH:mm:ss z","field-year":"Jahr",
"dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Stunde","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"diesen Samstag","field-sat-relative+1":"n\u00e4chsten Samstag","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"heute","field-thu-relative+0":"diesen Donnerstag","field-day-relative+1":"morgen","field-thu-relative+1":"n\u00e4chsten Donnerstag",
"dateFormatItem-GyMMMd":"d. MMM y G","dateFormatItem-H":"HH 'Uhr'","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["1. Quartal","2. Quartal","3. Quartal","4. Quartal"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E, d. MMM y G","dateFormatItem-M":"L","days-standAlone-wide":"Sonntag Montag Dienstag Mittwoch Donnerstag Freitag Samstag".split(" "),
"dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d. MMM y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"diesen Sonntag","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"n\u00e4chsten Sonntag","quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],eraAbbr:["AH"],"field-minute":"Minute","field-dayperiod":"Tagesh\u00e4lfte","days-standAlone-abbr":"So Mo Di Mi Do Fr Sa".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1",
"2","3","4"],"field-day-relative+-1":"gestern","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MEd":"E, d.M.","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"diesen Freitag","field-fri-relative+1":"n\u00e4chsten Freitag","field-day":"Tag","days-format-wide":"Sonntag Montag Dienstag Mittwoch Donnerstag Freitag Samstag".split(" "),"field-zone":"Zeitzone","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),
"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"letztes Jahr","field-month-relative+-1":"letzten Monat","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"So. Mo. Di. Mi. Do. Fr. Sa.".split(" "),eraNames:["AH"],"days-format-narrow":"SMDMDFS".split(""),"dateFormatItem-yyyyMd":"d.M.y GGGGG","field-month":"Monat","days-standAlone-narrow":"SMDMDFS".split(""),
"dateFormatItem-MMM":"LLL","field-tue-relative+0":"diesen Dienstag","field-tue-relative+1":"n\u00e4chsten Dienstag","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"vorm.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"diesen Montag","field-mon-relative+1":"n\u00e4chsten Montag","dateFormat-short":"dd.MM.yy GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a",
"dayPeriods-format-narrow-noon":"n","field-second":"Sekunde","field-sat-relative+-1":"letzten Samstag","field-sun-relative+-1":"letzten Sonntag","field-month-relative+0":"diesen Monat","field-month-relative+1":"n\u00e4chsten Monat","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E, d.","field-week":"Woche","dateFormat-medium":"dd.MM.y G","field-week-relative+-1":"letzte Woche","field-year-relative+0":"dieses Jahr","dateFormatItem-yyyyM":"M.y GGGGG","field-year-relative+1":"n\u00e4chstes Jahr",
"dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"letzten Montag","dateFormatItem-yyyy":"y G","field-week-relative+0":"diese Woche","field-week-relative+1":"n\u00e4chste Woche","field-day-relative+2":"\u00fcbermorgen","field-day-relative+-2":"vorgestern",_localized:{}},"widgets/ParcelDrafter/nls/strings":{_widgetLabel:"Flurst\u00fcckserstellung",
newTraverseButtonLabel:"Neuen Polygonzug beginnen",invalidConfigMsg:"Ung\u00fcltige Konfiguration",geometryServiceURLNotFoundMSG:"URL des Geometrieservice kann nicht abgerufen werden",editTraverseButtonLabel:"Polygonzug bearbeiten",mapTooltipForStartNewTraverse:"W\u00e4hlen Sie einen Punkt auf der Karte oder einen Typ unten aus, um zu beginnen.",mapTooltipForEditNewTraverse:"W\u00e4hlen Sie ein zu bearbeitendes Flurst\u00fcck aus.",mapTooltipForUpdateStartPoint:"Zum Aktualisieren des Startpunkts klicken",
mapTooltipForScreenDigitization:"Zum Hinzuf\u00fcgen von Flurst\u00fcckspunkt klicken",mapTooltipForUpdatingRotaionPoint:"Zum Aktualisieren des Drehpunkts klicken",mapTooltipForRotate:"Zum Drehen ziehen",mapTooltipForScale:"Zum Skalieren ziehen",backButtonTooltip:"Zur\u00fcck",newTraverseTitle:"Neuer Polygonzug",editTraverseTitle:"Polygonzug bearbeiten",clearingDataConfirmationMessage:"Die \u00c4nderungen werden verworfen. M\u00f6chten Sie fortfahren?",unableToFetchParcelMessage:"Flurst\u00fcck konnte nicht abgerufen werden.",
unableToFetchParcelLinesMessage:"Flurst\u00fcckslinien konnten nicht abgerufen werden.",planSettings:{planSettingsTitle:"Einstellungen",directionOrAngleTypeLabel:"Richtungs- oder Winkeltyp",directionOrAngleUnitsLabel:"Richtungs- oder Winkeleinheiten",distanceAndLengthUnitsLabel:"Strecken- und L\u00e4ngeneinheiten",areaUnitsLabel:"Fl\u00e4cheneinheiten",circularCurveParameters:"Parameter der kreisf\u00f6rmigen Kurve",northAzimuth:"Nordazimut",southAzimuth:"S\u00fcdazimut",quadrantBearing:"Quadrantwinkel",
radiusAndChordLength:"Radius und Sehnenl\u00e4nge",radiusAndArcLength:"Radius und Kreisbogenl\u00e4nge",expandGridTooltipText:"Gitternetz erweitern",collapseGridTooltipText:"Gitternetz reduzieren",zoomToLocationTooltipText:"Auf Position zoomen",onScreenDigitizationTooltipText:"Digitalisieren",updateRotationPointTooltipText:"Drehpunkt aktualisieren"},traverseSettings:{bearingLabel:"Peilung",lengthLabel:"L\u00e4nge",radiusLabel:"Radius",noMiscloseCalculated:"Abschlussfehler nicht berechnet",traverseMiscloseBearing:"Abschlussfehler-Peilung",
traverseAccuracy:"Genauigkeit",accuracyHigh:"Hoch",traverseDistance:"Abschlussfehler-Entfernung",traverseMiscloseRatio:"Abschlussfehler-Verh\u00e4ltnis",traverseStatedArea:"Angegebene Fl\u00e4che",traverseCalculatedArea:"Berechnete Fl\u00e4che",addButtonTitle:"Hinzuf\u00fcgen",deleteButtonTitle:"Entfernen"},parcelTools:{rotationToolLabel:"Winkel",scaleToolLabel:"Ma\u00dfstab"},newTraverse:{invalidBearingMessage:"Ung\u00fcltige Peilung.",invalidLengthMessage:"Ung\u00fcltige L\u00e4nge.",invalidRadiusMessage:"Ung\u00fcltiger Radius.",
negativeLengthMessage:"Nur f\u00fcr Kurven g\u00fcltig",enterValidValuesMessage:"Geben Sie g\u00fcltige Werte ein.",enterValidParcelInfoMessage:"Geben Sie zum Speichern g\u00fcltige Informationen zum Flurst\u00fcck ein.",unableToDrawLineMessage:"Linie kann nicht gezogen werden.",invalidEndPointMessage:"Ung\u00fcltiger Endpunkt, Linie kann nicht gezogen werden.",lineTypeLabel:"Linientyp"},planInfo:{requiredText:"(erforderlich)",optionalText:"(optional)",parcelNamePlaceholderText:"Flurst\u00fccksname",
parcelDocumentTypeText:"Dokumenttyp",planNamePlaceholderText:"Planname",cancelButtonLabel:"Abbrechen",saveButtonLabel:"Speichern",saveNonClosedParcelConfirmationMessage:"Das eingegebene Flurst\u00fcck ist nicht geschlossen. M\u00f6chten Sie den Vorgang trotzdem fortsetzen und nur die Flurst\u00fcckslinien speichern?",unableToCreatePolygonParcel:"Flurst\u00fcckspolygon kann nicht erstellt werden.",unableToSavePolygonParcel:"Flurst\u00fcckspolygon kann nicht gespeichert werden.",unableToSaveParcelLines:"Flurst\u00fcckslinien k\u00f6nnen nicht gespeichert werden.",
unableToUpdateParcelLines:"Flurst\u00fcckslinien k\u00f6nnen nicht aktualisiert werden.",parcelSavedSuccessMessage:"Flurst\u00fcck erfolgreich gespeichert.",parcelDeletedSuccessMessage:"Das Flurst\u00fcck wurde erfolgreich gel\u00f6scht.",parcelDeleteErrorMessage:"Fehler beim L\u00f6schen des Flurst\u00fccks.",enterValidParcelNameMessage:"Geben Sie einen g\u00fcltigen Flurst\u00fccksnamen ein.",enterValidPlanNameMessage:"Geben Sie einen g\u00fcltigen Plannamen ein.",enterValidDocumentTypeMessage:"Ung\u00fcltiger Dokumenttyp",
enterValidStatedAreaNameMessage:"Geben Sie eine g\u00fcltige angegebene Fl\u00e4che ein.",showAttributeList:"Attributliste anzeigen",hideAttributeList:"Attributliste ausblenden"},xyInput:{explanation:"Koordinaten im Raumbezug des Layers eingeben"},_localized:{}}});