// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Podebljaj",copy:"Kopiraj",cut:"Izre\u017ei","delete":"Izbri\u0161i",indent:"Uvuci",insertHorizontalRule:"Vodoravno ravnalo",insertOrderedList:"Numerirani popis",insertUnorderedList:"Popis s grafi\u010dkim oznakama",italic:"Kurziv",justifyCenter:"Centriraj",justifyFull:"Poravnaj",justifyLeft:"Poravnaj lijevo",justifyRight:"Poravnaj desno",outdent:"Izvuci",paste:"Zalijepi",redo:"Ponovno napravi",removeFormat:"Ukloni oblikovanje",selectAll:"Izaberi sve",strikethrough:"Precrtaj",
subscript:"Indeks",superscript:"Superskript",underline:"Podcrtaj",undo:"Poni\u0161ti",unlink:"Ukloni vezu",createLink:"Kreiraj vezu",toggleDir:"Prebaci smjer",insertImage:"Umetni sliku",insertTable:"Umetni/Uredi tablicu",toggleTableBorder:"Prebaci rub tablice",deleteTable:"Izbri\u0161i tablicu",tableProp:"Svojstvo tablice",htmlToggle:"HTML izvor",foreColor:"Boja prednjeg plana",hiliteColor:"Boja pozadine",plainFormatBlock:"Stil odlomka",formatBlock:"Stil odlomka",fontSize:"Veli\u010dina fonta",fontName:"Ime fonta",
tabIndent:"Tabulator uvla\u010denja",fullScreen:"Prebaci na potpun ekran",viewSource:"Pogledaj HTML izvor",print:"Ispis",newPage:"Nova stranica",systemShortcut:'"${0}" akcija je dostupna jedino u va\u0161em pregledniku upotrebom pre\u010dice tipkovnice. Koristite ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"ned pon uto sri \u010det pet sub".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),
"field-second-relative+0":"sada","quarters-standAlone-narrow":["1.","2.","3.","4."],"field-weekday":"Dan u tjednu","field-wed-relative+0":"ova srijeda","field-wed-relative+1":"sljede\u0107a srijeda","dateFormatItem-GyMMMEd":"E, d. MMM y. G","dateFormatItem-MMMEd":"E, d. MMM",eraNarrow:["AH"],"field-tue-relative+-1":"pro\u0161li utorak","days-format-short":"ned pon uto sri \u010det pet sub".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d. MMMM y. G","field-fri-relative+-1":"pro\u0161li petak",
"field-wed-relative+-1":"pro\u0161la srijeda","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y. G","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE, d. MMMM y. G","dateFormatItem-yyyyMEd":"E, dd.MM.y. GGGGG","field-thu-relative+-1":"pro\u0161li \u010detvrtak","dateFormatItem-Md":"d. M.","dayPeriods-format-abbr-am":"AM",
"dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"podne","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"timeFormat-long":"HH:mm:ss z","field-year":"Godina","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Sat",
"months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"ova subota","field-sat-relative+1":"sljede\u0107a subota","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"danas","field-thu-relative+0":"ovaj \u010detvrtak","field-day-relative+1":"sutra","field-thu-relative+1":"sljede\u0107i \u010detvrtak","dateFormatItem-GyMMMd":"d. MMM y. G","dateFormatItem-H":"HH",
"months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["1kv","2kv","3kv","4kv"],"quarters-standAlone-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"dateFormatItem-Gy":"y. G","dateFormatItem-yyyyMMMEd":"E, d. MMM y. G","dateFormatItem-M":"L.","days-standAlone-wide":"nedjelja ponedjeljak utorak srijeda \u010detvrtak petak subota".split(" "),"dateFormatItem-yyyyMMM":"LLL y. G","dateFormatItem-yyyyMMMd":"d. MMM y. G",
"dayPeriods-format-abbr-noon":"podne","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"ova nedjelja","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"sljede\u0107a nedjelja","quarters-standAlone-abbr":["1kv","2kv","3kv","4kv"],eraAbbr:["AH"],"field-minute":"Minuta","field-dayperiod":"AM/PM","days-standAlone-abbr":"ned pon uto sri \u010det pet sub".split(" "),"dateFormatItem-d":"d.","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1.","2.","3.","4."],"field-day-relative+-1":"ju\u010der",
"dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"hh a","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MEd":"E, d. M.","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"ovaj petak","field-fri-relative+1":"sljede\u0107i petak","field-day":"Dan","days-format-wide":"nedjelja ponedjeljak utorak srijeda \u010detvrtak petak subota".split(" "),"field-zone":"Vremenska zona","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y. G",
"dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"pro\u0161le godine","field-month-relative+-1":"pro\u0161li mjesec","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"hh:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"ned pon uto sri \u010det pet sub".split(" "),eraNames:["AH"],"days-format-narrow":"NPUS\u010cPS".split(""),"dateFormatItem-yyyyMd":"dd.MM.y. GGGGG","field-month":"Mjesec","days-standAlone-narrow":"npus\u010dps".split(""),
"dateFormatItem-MMM":"LLL","field-tue-relative+0":"ovaj utorak","field-tue-relative+1":"sljede\u0107i utorak","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"ovaj ponedjeljak","field-mon-relative+1":"sljede\u0107i ponedjeljak","dateFormat-short":"d.M.y. GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a",
"dayPeriods-format-narrow-noon":"n","field-second":"Sekunda","field-sat-relative+-1":"pro\u0161la subota","field-sun-relative+-1":"pro\u0161la nedjelja","field-month-relative+0":"ovaj mjesec","field-month-relative+1":"sljede\u0107i mjesec","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E, d.","field-week":"Tjedan","dateFormat-medium":"d. M. y. G","field-week-relative+-1":"pro\u0161li tjedan","field-year-relative+0":"ove godine","dateFormatItem-yyyyM":"MM.y. GGGGG","field-year-relative+1":"sljede\u0107e godine",
"dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"QQQQ y. G","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"hh:mm:ss a","dateFormatItem-GyMMM":"LLL y. G","field-mon-relative+-1":"pro\u0161li ponedjeljak","dateFormatItem-yyyy":"y. G","field-week-relative+0":"ovaj tjedan","field-week-relative+1":"sljede\u0107i tjedan","field-day-relative+2":"prekosutra","field-day-relative+-2":"prekju\u010der",_localized:{}},"widgets/ParcelDrafter/nls/strings":{_widgetLabel:"Skice parcela",
newTraverseButtonLabel:"Zapo\u010dni novi prijelaz",invalidConfigMsg:"Nevaljana konfiguracija",geometryServiceURLNotFoundMSG:"Nije mogu\u0107e dohvatiti URL geometrijske usluge",editTraverseButtonLabel:"Uredi prijelaz",mapTooltipForStartNewTraverse:"Odaberite to\u010dku na karti ili je upi\u0161ite u nastavku za po\u010detak",mapTooltipForEditNewTraverse:"Odaberite parcelu za ure\u0111ivanje",mapTooltipForUpdateStartPoint:"Kliknite za a\u017euriranje po\u010detne to\u010dke",mapTooltipForScreenDigitization:"Kliknite za dodavanje to\u010dke parcele",
mapTooltipForUpdatingRotaionPoint:"Kliknite za a\u017euriranje to\u010dke zakretanja",mapTooltipForRotate:"Povucite za okretanje",mapTooltipForScale:"Povucite za promjenu mjerila",backButtonTooltip:"Natrag",newTraverseTitle:"Novi prijelaz",editTraverseTitle:"Uredi prijelaz",clearingDataConfirmationMessage:"Promjene \u0107e biti odba\u010dene, \u017eelite li nastaviti?",unableToFetchParcelMessage:"Nije mogu\u0107e dohvatiti parcelu.",unableToFetchParcelLinesMessage:"Nije mogu\u0107e dohvatiti linije parcele.",
planSettings:{planSettingsTitle:"Postavke",directionOrAngleTypeLabel:"Vrsta smjera ili kuta",directionOrAngleUnitsLabel:"Jedinice smjera ili kuta",distanceAndLengthUnitsLabel:"Jedinice udaljenosti i du\u017eine",areaUnitsLabel:"Povr\u0161inske jedinice",circularCurveParameters:"Parametri kru\u017ene krivulje",northAzimuth:"Sjeverni azimut",southAzimuth:"Ju\u017eni azimut",quadrantBearing:"Azimut kvadranta",radiusAndChordLength:"Du\u017eina polumjera i tetive",radiusAndArcLength:"Du\u017eina polumjera i luka",
expandGridTooltipText:"Pro\u0161iri mre\u017eu",collapseGridTooltipText:"Sa\u017emi mre\u017eu",zoomToLocationTooltipText:"Uve\u0107aj na lokaciju",onScreenDigitizationTooltipText:"Digitaliziraj",updateRotationPointTooltipText:"A\u017eurirajte to\u010dku zakretanja"},traverseSettings:{bearingLabel:"Azimut",lengthLabel:"Duljina",radiusLabel:"Polumjer",noMiscloseCalculated:"Nepodudaranje nije izra\u010dunato",traverseMiscloseBearing:"Nepodudaranje azimuta",traverseAccuracy:"To\u010dnost",accuracyHigh:"Visoko",
traverseDistance:"Udaljenost nepodudaranja",traverseMiscloseRatio:"Omjer nepodudaranja",traverseStatedArea:"Navedeno podru\u010dje",traverseCalculatedArea:"Izra\u010dunato podru\u010dje",addButtonTitle:"Dodaj",deleteButtonTitle:"Ukloni"},parcelTools:{rotationToolLabel:"Kut",scaleToolLabel:"Mjerilo"},newTraverse:{invalidBearingMessage:"Neva\u017ee\u0107i azimut.",invalidLengthMessage:"Neva\u017ee\u0107a duljina.",invalidRadiusMessage:"Neva\u017ee\u0107i polumjer.",negativeLengthMessage:"Va\u017ee\u0107e samo za krivulje",
enterValidValuesMessage:"Unesite valjane vrijednosti.",enterValidParcelInfoMessage:"Unesite valjane informacije o parceli za spremanje.",unableToDrawLineMessage:"Nije mogu\u0107e nacrtati liniju.",invalidEndPointMessage:"Neva\u017ee\u0107a zavr\u0161na to\u010dka, nije mogu\u0107e nacrtati liniju.",lineTypeLabel:"Vrsta linije"},planInfo:{requiredText:"(obavezno)",optionalText:"(neobavezno)",parcelNamePlaceholderText:"Naziv parcele",parcelDocumentTypeText:"Vrsta dokumenta",planNamePlaceholderText:"Naziv plana",
cancelButtonLabel:"Odustani",saveButtonLabel:"Spremi",saveNonClosedParcelConfirmationMessage:"Unesena parcela nije zatvorena, \u017eelite li i dalje nastaviti i spremiti samo linije parcele?",unableToCreatePolygonParcel:"Nije mogu\u0107e stvoriti poligon parcele.",unableToSavePolygonParcel:"Nije mogu\u0107e spremiti poligon parcele.",unableToSaveParcelLines:"Nije mogu\u0107e spremiti linije parcele.",unableToUpdateParcelLines:"Nije mogu\u0107e a\u017eurirati linije parcele.",parcelSavedSuccessMessage:"Parcela je uspje\u0161no spremljena.",
parcelDeletedSuccessMessage:"Parcela je uspje\u0161no izbrisana.",parcelDeleteErrorMessage:"Pogre\u0161ka pri brisanju parcele.",enterValidParcelNameMessage:"Unesite valjani naziv parcele.",enterValidPlanNameMessage:"Unesite valjani naziv plana.",enterValidDocumentTypeMessage:"Neva\u017ee\u0107a vrsta dokumenta.",enterValidStatedAreaNameMessage:"Unesite valjano navedeno podru\u010dje.",showAttributeList:"Prika\u017ei popis atributa",hideAttributeList:"Sakrij popis atributa"},xyInput:{explanation:"Unesite koordinate s jednakom prostornom referencom kao sloj"},
_localized:{}}});