// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("esri/geometry/Point esri/geometry/Polygon esri/geometry/geometryEngine esri/graphic esri/geometry/webMercatorUtils esri/SpatialReference esri/geometry/Circle esri/request dojo/json ./geometryUtils".split(" "),function(x,T,k,Q,R,U,W,H,L,p){var K={createGRG:function(a,b,d,l,G,f,F,h,q,y,c,r,C,D){var g,n,e,t,z,M,E,N,O,S,H,L=[],v=0,A=0,B=l/2/Math.cos(30*Math.PI/180),V,P=a;switch(F){case "upperLeft":"horizontal"===q?(g=b-1,n=-1,"numeric"!==h?e=0:(e=(b-1)*a,"hexagon"===y&&(e+=Math.floor(b/2)))):
(g=-1,n=b-1,"numeric"!==h&&(e=b));break;case "upperRight":"horizontal"===q?(g=b-1,n=a,"numeric"!==h?e=a+1:(e=b*a+1,"hexagon"===y&&(e+=Math.floor(b/2)))):(e="numeric"!==h?b:b*(a+1),g=a,n=b-1);break;case "lowerRight":"horizontal"===q?(g=0,n=a,e=a+1):(g=a,n=0,e=1);break;case "lowerLeft":"horizontal"===q?(e=g=0,n=-1):(g=-1,e=1,n=0)}var J=a*l/2,I;I="hexagon"===y?1===b%2?((b-1)/2*3*B+B)/2:(b/2*3*B-B/2)/2:b*G/2;for(var m=null,m=null,u=1;u<=b;u++){for(var w=1;w<=a;w++){if(r){m=new T;if(1===u&&1===w)switch(102100===
d.spatialReference.wkid&&(d=R.webMercatorToGeographic(d)),c){case "center":t=p.getDestinationPoint(d,180+f,I);t=p.getDestinationPoint(t,270+f,J);break;case "upperLeft":t=p.getDestinationPoint(d,180+f,2*I);break;case "upperRight":t=p.getDestinationPoint(d,180+f,2*I);t=p.getDestinationPoint(t,270+f,2*J);break;case "lowerRight":t=p.getDestinationPoint(d,270+f,2*J);break;case "lowerLeft":t=d}"default"===y?(M=p.getDestinationPoint(t,0+f,G),E=p.getDestinationPoint(M,90+f,l),z=p.getDestinationPoint(E,180+
f,G),m.addRing([[t.x,t.y],[M.x,M.y],[E.x,E.y],[z.x,z.y]]),t=z):(z=t,N=p.getDestinationPoint(z,0+f,B),O=p.getDestinationPoint(N,60+f,B),E=p.getDestinationPoint(O,120+f,B),S=p.getDestinationPoint(E,180+f,B),H=p.getDestinationPoint(S,240+f,B),m.addRing([[z.x,z.y],[N.x,N.y],[O.x,O.y],[E.x,E.y],[S.x,S.y],[H.x,H.y]]),t=p.getDestinationPoint(t,90+f,l));m=k.simplify(m);C.spatialReference.wkid&&4326!==C.spatialReference.wkid&&(m=D.isLoaded()?D.project(m,C.spatialReference):R.geographicToWebMercator(m));m=
new Q(m);1===w&&(V="hexagon"===y?P===a?p.getDestinationPoint(N,300+f,B):O:M)}else{m=new T(new U({wkid:102100}));4326===d.spatialReference.wkid&&(d=R.geographicToWebMercator(d));switch(c){case "center":v=d.x-J;A=d.y-I;break;case "upperLeft":v=d.x;A=d.y-2*I;break;case "upperRight":v=d.x-2*J;A=d.y-2*I;break;case "lowerRight":v=d.x-2*J;A=d.y;break;case "lowerLeft":v=d.x,A=d.y}"default"===y?m.addRing([[v+(w-1)*l,A+(u-1)*G],[v+(w-1)*l,A+u*G],[v+w*l,A+u*G],[v+w*l,A+(u-1)*G],[v+(w-1)*l,A+(u-1)*G]]):(v=P===
a?v+(w-1)*l+l/2:v+(w-1)*l,A=A+B+1.5*(u-1)*B,z=new x([v,A],new U({wkid:102100})),E=new W(z,{radius:B,numberOfPoints:6}),z=k.rotate(E,90,z),m.addRing(z.rings[0]));m=k.rotate(m,-1*f,d);C.spatialReference.wkid&&102100!==C.spatialReference.wkid&&(m=D.isLoaded()?D.project(m,C.spatialReference):R.webMercatorToGeographic(m));m=new Q(m)}switch(F){case "upperLeft":"horizontal"===q?(n+=1,e+=1):(g+=1,"numeric"===h&&(e=b*w-(u-1)));break;case "lowerLeft":"horizontal"===q?(n+=1,e+=1):(g+=1,"numeric"===h&&(e=b*(w-
1)+u));break;case "upperRight":"horizontal"===q?(--e,--n):(--g,"numeric"===h&&(e-=a));break;case "lowerRight":"horizontal"===q?(--e,--n):(--g,"numeric"===h&&(e=b*(a-w)+u))}L.push(K.addGraphicLabel(m,h,e,g,n))}t=V;"hexagon"===y&&(P===a?a++:a--);switch(F){case "upperLeft":"horizontal"===q?(--g,e="numeric"!==h?0:"hexagon"===y?e-2*P-1:e-2*a,n=-1):(g=-1,n=b-(u+1),"numeric"!==h&&(e=b-u));break;case "upperRight":"horizontal"===q?(--g,"numeric"!==h&&(e=a+1),n=a):(e="numeric"!==h?e-1:b*(a+1)-u,g=a,--n);break;
case "lowerRight":"horizontal"===q?(g+=1,e="numeric"!==h?a+1:"hexagon"===y?e+2*P+1:e+2*a,n=a):(g=a,n+=1,e="numeric"!==h?e+1:a*u);break;case "lowerLeft":"horizontal"===q?(g+=1,"numeric"!==h&&(e=0),n=-1):(g=-1,"numeric"!==h&&(e+=1),n=u)}}return L},convertNumberToLetters:function(a){for(var b="";0<=a;)b=String.fromCharCode(a%26+65)+b,a=Math.floor(a/26)-1;return b},checkGridSize:function(a,b){return 2E3>a*b},getFeatureServiceParams:function(a,b){return{name:a,serviceDescription:"",hasStaticData:!1,maxRecordCount:1E3,
supportedQueryFormats:"JSON",capabilities:"Create,Delete,Query,Update,Editing",tags:"GRG",description:"",copyrightText:"",spatialReference:{wkid:102100},initialExtent:{xmin:b.extent.xmin,ymin:b.extent.ymin,xmax:b.extent.xmax,ymax:b.extent.ymax,spatialReference:{wkid:102100}},allowGeometryUpdates:!0,units:"esriMeters",xssPreventionInfo:{xssPreventionEnabled:!0,xssPreventionRule:"InputOnly",xssInputRule:"rejectInvalid"}}},getLayerParams:function(a,b,d,l){return{layers:[{adminLayerInfo:{geometryField:{name:"Shape"},
xssTrustedFields:""},id:0,name:a,type:"Feature Layer",displayField:"",description:"A GRG (Gridded Reference Graphic) is a grid overlay used for a commonreference point in many situations - from cordon and search operations to securityfor presidential inaugurations.",tags:"GRG",copyrightText:"",defaultVisibility:!0,ownershipBasedAccessControlForFeatures:{allowOthersToQuery:!1,allowOthersToDelete:!1,allowOthersToUpdate:!1},relationships:[],isDataVersioned:!1,supportsCalculate:!0,supportsAttachmentsByUploadId:!0,
supportsRollbackOnFailureParameter:!0,supportsStatistics:!0,supportsAdvancedQueries:!0,supportsValidateSql:!0,supportsCoordinatesQuantization:!0,supportsApplyEditsWithGlobalIds:!0,advancedQueryCapabilities:{supportsPagination:!0,supportsQueryWithDistance:!0,supportsReturningQueryExtent:!0,supportsStatistics:!0,supportsOrderBy:!0,supportsDistinct:!0,supportsQueryWithResultType:!0,supportsSqlExpression:!0,supportsReturningGeometryCentroid:!0},useStandardizedQueries:!1,geometryType:"esriGeometryPolygon",
minScale:0,maxScale:0,extent:{xmin:b.extent.xmin,ymin:b.extent.ymin,xmax:b.extent.xmax,ymax:b.extent.ymax,spatialReference:{wkid:102100}},drawingInfo:{renderer:{type:"simple",symbol:l},transparency:0,labelingInfo:[{labelExpression:"[grid]",labelExpressionInfo:{value:"{grid}"},format:null,fieldInfos:null,useCodedValues:!1,maxScale:0,minScale:0,where:null,sizeInfo:null,labelPlacement:"esriServerPolygonPlacementAlwaysHorizontal",symbol:d}]},allowGeometryUpdates:!0,hasAttachments:!1,htmlPopupType:"esriServerHTMLPopupTypeNone",
hasM:!1,hasZ:!1,objectIdField:"OBJECTID",globalIdField:"",typeIdField:"",fields:[{name:"OBJECTID",type:"esriFieldTypeOID",actualType:"int",alias:"OBJECTID",sqlType:"sqlTypeOther",nullable:!1,editable:!1,domain:null,defaultValue:null},{name:"grid",type:"esriFieldTypeString",alias:"grid",actualType:"nvarchar",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeNVarchar",length:256}],indexes:[],types:[],templates:[{name:"New Feature",description:"",drawingTool:"esriFeatureEditToolPolygon",
prototype:{attributes:{grid:""}}}],supportedQueryFormats:"JSON",hasStaticData:!1,maxRecordCount:1E4,standardMaxRecordCount:4E3,tileMaxRecordCount:4E3,maxRecordCountFactor:1,exceedsLimitFactor:1,capabilities:"Query,Editing,Create,Update,Delete"}]}},isNameAvailable:function(a,b,d){return H({url:a,content:{name:d,type:"Feature Service",token:b,f:"json"},handleAs:"json",callbackParamName:"callback"},{usePost:!0})},createFeatureService:function(a,b,d){return H({url:a,content:{f:"json",token:b,typeKeywords:"ArcGIS Server,Data,Feature Access,Feature Service,Service,Hosted Service",
createParameters:L.stringify(d),outputType:"featureService"},handleAs:"json",callbackParamName:"callback"},{usePost:!0})},addDefinitionToService:function(a,b,d){return H({url:a,content:{token:b,addToDefinition:L.stringify(d),f:"json"},handleAs:"json",callbackParamName:"callback"},{usePost:!0})},labelReferenceGrid:function(a,b,d,l){for(var p=-1,f=1,F,h=!0,q=null,y=[],c;0<a.length;)if(h){p++;"alphaNumeric"===b?f=1:"alphaAlpha"===b&&(F=0);var r=k.union(a);c=r.getExtent();var C;switch(d){case "lowerLeft":C=
k.nearestCoordinate(r,new x(c.xmin,c.ymin,c.spatialReference));break;case "lowerRight":C=k.nearestCoordinate(r,new x(c.xmax,c.ymin,c.spatialReference));break;case "upperLeft":C=k.nearestCoordinate(r,new x(c.xmin,c.ymax,c.spatialReference));break;case "upperRight":C=k.nearestCoordinate(r,new x(c.xmax,c.ymax,c.spatialReference))}for(c=0;c<a.length;c++)if(k.touches(a[c],C.coordinate)){q=a[c];y.push(K.addGraphicLabel(new Q(a[c]),b,f,p,F));f++;F++;h=a.indexOf(a[c]);a.splice(h,1);h=!1;break}}else{h=!0;
c=q.getExtent();var D;switch(d){case "lowerLeft":D=k.nearestCoordinate(q,new x(c.xmax,c.ymin,c.spatialReference));break;case "lowerRight":D=k.nearestCoordinate(q,new x(c.xmin,c.ymin,c.spatialReference));break;case "upperLeft":D=k.nearestCoordinate(q,new x(c.xmax,c.ymax,c.spatialReference));break;case "upperRight":D=k.nearestCoordinate(q,new x(c.xmin,c.ymax,c.spatialReference))}for(r=0;r<a.length;r++){c=a[r].getExtent();var g;switch(d){case "lowerLeft":g=k.nearestCoordinate(a[r],new x(c.xmin,c.ymin,
c.spatialReference));break;case "lowerRight":g=k.nearestCoordinate(a[r],new x(c.xmax,c.ymin,c.spatialReference));break;case "upperLeft":g=k.nearestCoordinate(a[r],new x(c.xmin,c.ymax,c.spatialReference));break;case "upperRight":g=k.nearestCoordinate(a[r],new x(c.xmax,c.ymax,c.spatialReference))}c=k.buffer(g.coordinate,"UTM"===l?1E4:l/5,9001);if(k.contains(c,D.coordinate)){q=a[r];y.push(K.addGraphicLabel(new Q(a[r]),b,f,p,F));f++;F++;h=a.indexOf(a[r]);a.splice(h,1);h=!1;break}}}return y},addGraphicLabel:function(a,
b,d,l,k){l=K.convertNumberToLetters(l);k=K.convertNumberToLetters(k);var f={};switch(b){case "alphaNumeric":f.grid=l.toString()+d.toString();break;case "alphaAlpha":f.grid=l.toString()+"-"+k.toString();break;case "numeric":f.grid=d.toString()}a.setAttributes(f);return a},checkPolarRegion:function(a){var b=new T({rings:[[[-180,84],[-180,90],[180,90],[180,84],[-180,84]],[[-180,-90],[-180,-80],[180,-80],[180,-90],[-180,-90]]],spatialReference:{wkid:4326}});return k.intersects(a,b)}};return K});