// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/Deferred dojo/when dojo/promise/all jimu/portalUtils esri/lang esri/request jimu/utils esri/dijit/PopupTemplate esri/graphic esri/geometry/webMercatorUtils esri/tasks/ProjectParameters".split(" "),function(f,m,k,u,n,v,q,r,t,w,x,y,z){var p={map:null,layerInfosObj:null,appConfig:null,_esriLocatorRegExp:/geocode(.){0,3}\.arcgis.com\/arcgis\/rest\/services\/World\/GeocodeServer/g,setMap:function(a){this.map=a},setLayerInfosObj:function(a){this.layerInfosObj=
a},setAppConfig:function(a){this.appConfig=a},getConfigInfo:function(a){if(a&&a.sources&&0<a.sources.length){var b=null;return this.searchLayer(this.map)&&a.upgradeFromGeocoder?(b=this.map.itemInfo.itemData.applicationProperties.viewing.search,b=m.map(b.layers,f.hitch(this,function(a,b){b.hintText=a;return this._getQueryTypeGeocoder(b)},b.hintText)),n(b).then(f.hitch(this,function(b){a.sources=[].concat(b).concat(a.sources);return a}))):a}return u(this._getSoucesFromPortalAndWebmap()).then(f.hitch(this,
function(a){return{allPlaceholder:"",showInfoWindowOnSelect:!0,sources:a}}))},_getSoucesFromPortalAndWebmap:function(){var a=[],b=null;this.searchLayer(this.map)&&(b=this.map.itemInfo.itemData.applicationProperties.viewing.search,m.forEach(b.layers,f.hitch(this,function(b,c){c.hintText=b;a.push(this._getQueryTypeGeocoder(c))},b.hintText)));return v.getPortalSelfInfo(this.appConfig.portalUrl).then(f.hitch(this,function(b){if((b=b.helperServices&&b.helperServices.geocode)&&0<b.length)for(var c=0,d=
b.length;c<d;c++){var h=b[c];h&&a.push(this._processSingleLine(h))}return n(a).then(f.hitch(this,function(a){for(var b=[],d=0;d<a.length;d++){var c=a[d];c&&(c&&"query"===c.type||(c={name:c.name||this._getGeocodeName(c.url),url:c.url,singleLineFieldName:c.singleLineFieldName,placeholder:"Find address or place",maxResults:6,searchInCurrentMapExtent:!1,type:"locator"},c.enableLocalSearch=this._isEsriLocator(c.url),c.localSearchMinScale=3E5,c.localSearchDistance=5E4),b.push(c))}return b}))}))},_getQueryTypeGeocoder:function(a){var b=
this.map.getLayer(a.id),d=null,c=null,e=null,e=q.isDefined(a.subLayer)?a.id+"_"+a.subLayer:a.id,d=this.layerInfosObj.traversal(function(a){return a.id===e?(c=a,!0):!1});return b&&d&&c?(d=q.isDefined(a.subLayer)?c.url||b.url+"/"+a.subLayer:c.url||b.url,{name:c.title,layerId:e,url:d,placeholder:a.hintText,searchFields:[a.field.name],displayField:a.field.name,exactMatch:a.field.exactMatch||!1,maxResults:6,searchInCurrentMapExtent:!1,type:"query"}):null},_isEsriLocator:function(a){this._esriLocatorRegExp.lastIndex=
0;return this._esriLocatorRegExp.test(a)},_processSingleLine:function(a){if(a.singleLineFieldName)return a;if(this._isEsriLocator(a.url))return a.singleLineFieldName="SingleLine",a;var b=new k;r({url:a.url,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}).then(f.hitch(this,function(d){d.singleLineAddressField&&d.singleLineAddressField.name?(a.singleLineFieldName=d.singleLineAddressField.name,b.resolve(a)):(console.warn(a.url+"has no singleLineFieldName"),b.resolve(null))}),f.hitch(this,
function(a){console.error(a);b.resolve(null)}));return b.promise},_getGeocodeName:function(a){if("string"!==typeof a)return"geocoder";a=a.split("/");return a[a.length-2]||"geocoder"},getGeocoderName:function(a){return this._getGeocodeName(a)},hasAppSearchInfo:function(a){return a.itemInfo&&a.itemInfo.itemData&&a.itemInfo.itemData.applicationProperties&&a.itemInfo.itemData.applicationProperties.viewing&&a.itemInfo.itemData.applicationProperties.viewing.search},searchLayer:function(a){if(!this.hasAppSearchInfo(a))return!1;
a=a.itemInfo.itemData.applicationProperties.viewing.search;return a.enabled&&0!==a.layers.length?!0:!1},getSingleLineAddressName:function(a){var b=new k;r({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}).then(f.hitch(this,function(a){a&&a.singleLineAddressField&&a.singleLineAddressField.name?b.resolve(a.singleLineAddressField.name):b.resolve(null)}),f.hitch(this,function(a){console.error(a);b.reject()}));return b},version:{isConfigBefore63:function(a){var b=!1;a&&a.geocoderOptions&&
(b=!0);return b},upgradeConfig:function(a){a.geocoderOptions&&delete a.geocoderOptions},getVersionState:function(){}},config:{onLayerInfosFilterChanged:function(a,b){m.some(a,f.hitch(this,function(a){b.searchOptions&&b.searchOptions.sources&&0<b.searchOptions.sources.length&&m.forEach(b.searchOptions.sources,function(b){b._featureLayerId===a.id&&b.featureLayer.setDefinitionExpression(a.getFilter())})}))},getInfoTemplate:function(a,b,d){var c=new k;d=d.getLayerInfoById(b.layerId);var e;if(d)c=d.loadInfoTemplate();
else{var h=[];m.filter(a.fields,function(a){"shape"!==a.name.toLowerCase()&&h.push(a.name)});(a=t.getDefaultPopupInfo(a,b.name+": {"+b.displayField+"}",h))&&(e=new w(a));c.resolve(e)}return c},getWayPoints:function(a,b,d){var c=new k;b&&c.resolve(a.defaultLocations);b=[];for(var e=0,h=a.defaultLocations.length;e<h;e++){var g;g=a.defaultLocations[e];if("object"===typeof g&&g.feature&&g.name){var l={},l=g.feature.attributes;g.name&&(l.Name=g.name);g=new x(g.feature,null,l);b.push(g)}else"string"===
typeof g?b.push(g):b.push("")}p.config.projectGeometriesToMapCoords(b,d).then(f.hitch(this,function(a){c.resolve(a)}),f.hitch(this,function(a){c.reject(a)}));return c},projectGeometriesToMapCoords:function(a,b){var d=new k,c=[],e=[];if(4326===parseInt(b.spatialReference.wkid,10))c.push((new k).resolve(a));else if(b.spatialReference.isWebMercator()){for(var h=0,g=a.length;h<g;h++){var l=a[h];if(b=l.geometry)if(b=y.geographicToWebMercator(b))l.geometry=b;e.push(l)}c.push((new k).resolve(e))}else for(e=
esriConfig&&esriConfig.defaults&&esriConfig.defaults.geometryService,e&&"esri.tasks.GeometryService"===e.declaredClass||(geoServiceUrl&&"string"===typeof geoServiceUrl&&f.trim(geoServiceUrl)?(geoServiceUrl=f.trim(geoServiceUrl),e=new GeometryService(geoServiceUrl)):e=t.getArcGISDefaultGeometryService()),h=0,g=a.length;h<g;h++)(l=a[h])?c.push(p.config.projectedToOthersCoords(l,e,b)):c.push((new k).resolve(""));n(c).then(f.hitch(this,function(a){var b=[];if(1<a.length){for(var c=0,e=a.length;c<e;c++)b.push(a[c]);
return d.resolve(b)}return d.resolve(a[0])}),f.hitch(this,function(a){return d.reject(a)}));return d},projectedToOthersCoords:function(a,b,d){var c=new k,e=new z;e.geometries=[a.geometry];e.outSR=d.spatialReference;b.project(e).then(function(b){return(b=b&&b[0])?(a.geometry=b,c.resolve(a)):c.reject("")},function(a){console.error(a);return c.reject("")});return c},_toPointGeometry:function(a){var b=a.feature.geometry;b&&(b.getCentroid?a.feature.geometry=b.getCentroid():b.getExtent&&(b=b.getExtent())&&
(a.feature.geometry=b.getCenter()));return a},_getLocationObject:function(a){return{name:a.name,extent:a.extent,feature:{geometry:a.feature.geometry,attributes:{Score:100,Addr_Type:"PointAddress"}}}}}};return p});