// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/NearMe/filter-list.html":'\x3cdiv\x3e\r\n  \x3cul class\x3d"filter-list" data-dojo-attach-point\x3d"filterList"\x3e\x3c/ul\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/text!./filter-list.html dojo/_base/array dojo/_base/html dojo/_base/lang dojo/query dojo/on dojo/dom-attr dojo/keys dijit/_WidgetsInTemplateMixin dojo/dom-class jimu/utils jimu/BaseWidget jimu/filterUtils jimu/dijit/FilterParameters esri/symbols/jsonUtils jimu/symbolUtils jimu/LayerInfos/LayerInfos jimu/FilterManager esri/request dojo/Evented dojo/NodeList dojo/NodeList-dom".split(" "),function(v,w,q,f,g,h,n,m,l,x,p,r,y,z,A,B,t,C,D,E,F){return v([y,x,F],{name:"NearMeFilter",
templateString:w,lastFocusNode:null,baseClass:"jimu-widget-nearme-filter",_itemTemplate:'\x3cli aria-label\x3d"${layerTitle}" role\x3d"listitem" tabindex\x3d"0" class\x3d"filter-item" data-index\x3d"${index}"\x3e\x3cdiv class\x3d"header" \x3e\x3cspan role\x3d"button" aria-label\x3d"${toggleTip}" class\x3d"arrow jimu-float-leading jimu-trailing-margin05" title\x3d"${toggleTip}" \x3e\x3c/span\x3e\x3cspan class\x3d"icon"\x3e\x3cimg src\x3d"${icon}" /\x3e\x3c/span\x3e\x3cspan class\x3d"icon symbolIcon" style\x3d"display:none;"\x3e\x3c/span\x3e\x3cspan class\x3d"item-title"\x3e${title}\x3c/span\x3e\x3cspan class\x3d"cando jimu-float-trailing esriCTFliterListCheckbox"\x3e\x3c/span\x3e\x3cspan class\x3d"doing jimu-float-trailing esriCTFliterListCheckbox"\x3e\x3c/span\x3e\x3cspan class\x3d"done jimu-float-trailing esriCTFliterListCheckbox"\x3e\x3c/span\x3e\x3c/div\x3e\x3cdiv class\x3d"body"\x3e\x3cdiv class\x3d"parameters"\x3e\x3c/div\x3e\x3cdiv tabindex\x3d"0" role\x3d"button" aria-label\x3d"${apply}" class\x3d"jimu-btn apply jimu-float-trailing jimu-trailing-margin25"\x3e${apply}\x3c/div\x3e\x3c/div\x3e\x3c/li\x3e',
_layerTitleTemplate:'\x3cdiv class\x3d"esriCTGroupFilterLayerName"\x3e${layerTitle}\x3c/div\x3e',_store:null,totalAppliedFilters:0,postCreate:function(){this.inherited(arguments);this.totalAppliedFilters=0;this._updateClearAllButtonState();this.own(n(this.clearAllButton,"click",g.hitch(this,this._clearAllFilters)));this.own(n(this.clearAllButton,"keydown",g.hitch(this,function(a){a.keyCode!==l.ENTER&&a.keyCode!==l.SPACE||this._clearAllFilters()})));this._store={};this.layerInfosObj=C.getInstanceSync();
this.filterUtils=new z;this.filterManager=D.getInstance();var a=this.config.filters,b={},d=[];this.config.groupFiltersByLayer?(q.forEach(a,function(a,c){b[a.layerId]||(b[a.layerId]=[],d.push(a.layerId));a.index=c;b[a.layerId].push(a)}),q.forEach(d,g.hitch(this,function(a){var c=this.layerInfosObj.getLayerInfoById(a),c=g.replace(this._layerTitleTemplate,{layerTitle:c.layerObject.name||c.title},/\$\{([^\}]+)\}/ig),c=f.toDom(c);f.place(c,this.filterList);for(c=0;c<b[a].length;c++)this._addFilterInList(b[a][c],
b[a][c].index)}))):q.forEach(a,g.hitch(this,function(a,b){this._addFilterInList(a,b)}))},getLastNode:function(){var a;this.lastFocusNode&&(p.contains(this.lastFocusNode,"has-ask-for-value")?(a=r.getFocusNodesInDom(this.lastFocusNode),a=p.contains(this.lastFocusNode,"config-parameters")?a.reverse()[0]:h(".arrow",this.lastFocusNode)[0]):a=this.lastFocusNode);return a},_addFilterInList:function(a,b){var d=this.filterUtils.isAskForValues(a.filter),e={icon:a.icon?r.processUrlInWidgetConfig(a.icon,this.folderUrl):
this.folderUrl+"/css/images/default_task_icon.png",index:b,title:a.name,layerTitle:a.layerTitle?a.layerTitle:a.name,toggleTip:this.nls.toggleTip,hasValue:d?window.appInfo.isRunInMobile?"block !important":"":"none",isAskForValue:d,apply:g.getObject("jimuNls.common.apply",!1,window)||"Apply"};this._store[a.layerId]||(this._store[a.layerId]={mapFilterControls:{}});b=g.replace(this._itemTemplate,e,/\$\{([^\}]+)\}/ig);var c=f.toDom(b);this.lastFocusNode=c;f.place(c,this.filterList);if(a.symbol){b=h(".icon",
c);f.setStyle(b[0],"display","none");f.setStyle(b[1],"display","inline-block");var k=B.fromJson(a.symbol),u=a.symbol.url||a.symbol.imageData;u?(k.setWidth(25),k.setHeight(25)):k.setSize(25);k=u?t.createSymbolNode(k):t.createSymbolNode(k,{width:26,height:26});f.place(k,b[1])}this.own(h(".header",c).on("click",g.hitch(this,"enableFilter",c,a,e,!1)));d?(f.addClass(c,"has-ask-for-value"),m.set(c,"tabindex","-1")):(this.own(n(h(".header",c)[0].parentElement,"keydown",g.hitch(this,"enableFilter",c,a,e,
!0))),f.addClass(c,"not-has-ask-for-value"));d=h(".apply",c);b=h(".arrow",c);"none"!==e.hasValue?(m.set(d[0],"type",""),m.set(b[0],"type",""),m.set(b[0],"tabindex","0"),this.own(b.on("click",g.hitch(this,"configFilter",c,a))),this.own(b.on("keydown",g.hitch(this,function(b){if(b.keyCode===l.ENTER||b.keyCode===l.SPACE)this.configFilter(c,a),b.stopPropagation()}))),this.own(d.on("click",g.hitch(this,"applyFilterValues",c,a,!1))),this.own(d.on("keydown",g.hitch(this,"applyFilterValues",c,a,!0))),f.addClass(c,
"requesting"),this.configFilter(c,a,null,g.hitch(this,function(){this.config.collapse&&f.removeClass(c,"config-parameters");a.autoApplyWhenWidgetOpen&&this.enableFilter(c,a,e)}))):(m.set(d[0],"type","hidden"),m.set(b[0],"type","hidden"),a.autoApplyWhenWidgetOpen&&this.enableFilter(c,a,e))},startup:function(){this.inherited(arguments);this.resize()},_getPriorityOfMapFilter:function(a){a=g.getObject(a+".mapFilterControls",!1,this._store);var b=0,d;for(d in a){var e=a[d];e.priority>b&&(b=e.priority)}return b},
_getMapFilterControl:function(a){a=g.getObject(a+".mapFilterControls",!1,this._store);var b=!0,d;for(d in a){var e=a[d];0<e.priority&&(b=!!e.enable)}return b},_setItemFilter:function(a,b,d,e){this._store[a]["filter_item_"+b]=d;d=this._getPriorityOfMapFilter(a);g.setObject(a+".mapFilterControls.filter_item_"+b,{enable:e,priority:d+1},this._store)},_removeItemFilter:function(a,b){delete this._store[a]["filter_item_"+b];delete this._store[a].mapFilterControls["filter_item_"+b]},_getExpr:function(a){if(!this._store[a])return null;
var b=[];a=this._store[a];for(var d in a){var e=a[d];e&&"mapFilterControls"!==d&&b.push("("+e+")")}return b.join(" AND ")},_bindMapUpdateEvents:function(a,b){n.once(this.map,"update-start",g.hitch(this,function(){f.addClass(a,"applying");f.removeClass(a,"applied")}));n.once(this.map,"update-end",g.hitch(this,function(){b?f.addClass(a,"applied"):f.removeClass(a,"applied");f.removeClass(a,"applying")}))},enableFilter:function(a,b,d,e,c){if(!e||c.keyCode===l.ENTER||c.keyCode===l.SPACE)if(!f.hasClass(a,
"config-parameters")||a.filterParams&&a.filterParams.getFilterExpr())if(!d.isAskForValue||a.filterParams&&a.filterParams.getFilterExpr()){d=b.layerId;e=f.getAttr(a,"data-index");c=null;var k=this.layerInfosObj.getLayerInfoById(d);c=f.hasClass(a,"applied");k.isShowInMap()&&k.isInScale()?this._bindMapUpdateEvents(a,c?!1:!0):c?f.removeClass(a,"applied"):f.addClass(a,"applied");k=null;c?(this._removeItemFilter(d,e),c=this._getExpr(d),k=this._getMapFilterControl(d),this.filterManager.applyWidgetFilter(d,
this.id,c,k),this.totalAppliedFilters--):(a=this._getFilterExpr(a,b),this._setItemFilter(d,e,a,b.enableMapFilter),c=this._getExpr(d),k=this._getMapFilterControl(d),this.filterManager.applyWidgetFilter(d,this.id,c,k),this.totalAppliedFilters++);this.filtersUpdated=!0;this._updateClearAllButtonState()}else this.configFilter(a,b)},configFilter:function(a,b,d,e){a.filterParams?(f.hasClass(a,"config-parameters")?(f.removeClass(a,"config-parameters"),this._changeItemTitleWidth(a,window.appInfo.isRunInMobile?
60:45)):(f.addClass(a,"config-parameters"),this._changeItemTitleWidth(a,60)),e&&e(),this.emit("setLastFilterNode",this.getLastNode())):E({url:b.url,content:{f:"json"},handleAs:"json",callbackPrams:"callback"}).then(g.hitch(this,function(c){f.addClass(a,"config-parameters");f.removeClass(a,"requesting");var d=h(".parameters",a)[0];a.handles=[];a.filterParams=new A;var m=g.clone(b.filter),l=null;b.enableMapFilter&&(l=b.layerId);a.filterParams.build(b.url,c,m,l,this.id);this.own(n(a.filterParams,"change",
g.hitch(this,function(b){b?(h(".apply",a).removeClass("disable-apply"),a.expr=b):(delete a.expr,h(".apply",a).addClass("disable-apply"))})));a.expr=a.filterParams.getFilterExpr();a.expr?h(".apply",a).removeClass("disable-apply"):(delete a.expr,h(".apply",a).addClass("disable-apply"));a.filterParams.placeAt(d);this._changeItemTitleWidth(a,60);e&&e()}));d&&d.target&&d.stopPropagation()},applyFilterValues:function(a,b,d,e){if(!d||e.keyCode===l.ENTER||e.keyCode===l.SPACE){var c=a.filterParams&&(a.expr||
this._getFilterExpr(a,b)),g=!0;d=!1;p.contains(a,"applied")?(d=!0,this._getExpr(b.layerId)==="("+c+")"&&(g=!1)):g=!0;if(c&&g){a.expr=c;var c=b.layerId,g=f.getAttr(a,"data-index"),h=this.layerInfosObj.getLayerInfoById(c);h.isShowInMap()&&h.isInScale()?this._bindMapUpdateEvents(a,!0):f.addClass(a,"applied");this._setItemFilter(c,g,a.expr,b.enableMapFilter);a=this._getExpr(c);b=this._getMapFilterControl(c);this.filterManager.applyWidgetFilter(c,this.id,a,b);this.filtersUpdated=!0;d||this.totalAppliedFilters++;
this._updateClearAllButtonState()}e.stopPropagation()}},_getFilterExpr:function(a,b){return a.filterParams?a.filterParams.getFilterExpr():this.filterUtils.hasVirtualDate(b.filter)?(this.filterUtils.isHosted=r.isHostedService(b.url),this.filterUtils.getExprByFilterObj(b.filter)):b.filter.expr},resize:function(){this.inherited(arguments);this._changeItemTitleWidth(this.domNode,window.appInfo.isRunInMobile?60:45)},_changeItemTitleWidth:function(a,b){var d=h(".header",a)[0];d&&(b=f.getContentBox(d).w-
b,0<b&&h(".header .item-title",a).style({maxWidth:b+"px"}))},destroy:function(){h(".filter-item",this.filterList).forEach(function(a){delete a.filterParams;delete a.expr});if(this._store)for(var a in this._store)a&&this.filterManager.applyWidgetFilter(a,this.id,"",null);this.inherited(arguments)},filterListShown:function(){this.filtersUpdated=!1},_updateClearAllButtonState:function(){0<this.totalAppliedFilters?(p.add(this.clearAllButton,"esriCTClearAllFilterActive"),m.set(this.clearAllButton,"aria-disabled",
"false")):(p.remove(this.clearAllButton,"esriCTClearAllFilterActive"),m.set(this.clearAllButton,"aria-disabled","true"))},_clearAllFilters:function(){if(p.contains(this.clearAllButton,"esriCTClearAllFilterActive")&&this.filterList){var a=h(".applied",this.filterList);q.forEach(a,function(a){(a=h(".header",a))&&0<a.length&&a[0].click()});this._updateClearAllButtonState();this.emit("clearAllFilters")}}})});