// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang jimu/utils dojo/date dojo/_base/array dojo/dom-construct dijit/form/DateTextBox dijit/form/NumberSpinner dijit/form/NumberTextBox dijit/form/FilteringSelect dijit/form/TextBox dijit/form/ValidationTextBox dijit/form/TimeTextBox dijit/Editor dijit/form/SimpleTextarea dojo/store/Memory dojo/query dijit/_editor/plugins/LinkDialog dijit/_editor/plugins/TextColor jimu/dijit/EditorTextColor jimu/dijit/EditorBackgroundColor".split(" "),function(n,g,d,k,e,q,r,p,t,u,l,v,w,x,y,m){return{integerFields:["esriFieldTypeSmallInteger",
"esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],getFieldInfoByFieldName:function(a,c){var b={};k.some(a,function(a){if(a.name===c)return n.mixin(b,a),!0});return b},getDateFromRelativeInfo:function(a,c){var b=new Date;"fixed"===a.dateType?b=a.dateTime?new Date(a.dateTime):"":"future"===a.dateType?(b=d.add(b,"year",a.year),b=d.add(b,"month",a.month),b=d.add(b,"day",a.day),b=d.add(b,"hour",a.hour),b=d.add(b,"minute",a.minute),b=d.add(b,"second",a.second)):"past"===a.dateType&&(a.year&&
(b=d.add(b,"year",-1*a.year)),a.month&&(b=d.add(b,"month",-1*a.month)),a.day&&(b=d.add(b,"day",-1*a.day)),a.hour&&(b=d.add(b,"hour",-1*a.hour)),a.minute&&(b=d.add(b,"minute",-1*a.minute)),a.second&&(b=d.add(b,"second",-1*a.second)));return c&&""!==b?g.localizeDate(b):b},getDateFieldValue:function(a,c){var b;if("esriFieldTypeDate"===a.type){if(c instanceof Array){var d,e;0<c.length&&c[0]&&(d=c[0].getValue());1<c.length&&c[1]&&(e=c[1].getValue());b=d&&e?new Date(d.getFullYear(),d.getMonth(),d.getDate(),
e.getHours(),e.getMinutes(),e.getSeconds(),e.getMilliseconds()):d||e||null}else b=c.getValue(),a.domain&&(b=Number(b));b=b&&b.getTime?b.getTime():b&&b.toGregorian?b.toGregorian().getTime():b}return b},isGuid:function(a){"{"===a[0]&&(a=a.substring(1,a.length-1));return/^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$/gi.test(a)},validateGUID:function(a,c){return this.isGuid(a)},isValidPresetValue:function(a){var c=!0;k.some(a,function(a){if(a.isValid&&
!a.isValid())return c=!1,!0});return c},createPresetFieldContentNode:function(a){var c=[],b;if(a.domain){if("codedValue"===a.domain.type){var d=[];k.forEach(a.domain.codedValues,function(a){d.push({name:a.name,id:a.code})});b=new t({"class":"ee-inputField",name:a.fieldName,store:new y({data:d}),searchAttr:"name",required:!0},e.create("div"))}else{b=null;switch(a.type){case "esriFieldTypeSmallInteger":case "esriFieldTypeInteger":b={min:a.domain.minValue,max:a.domain.maxValue,places:0};break;case "esriFieldTypeSingle":case "esriFieldTypeDouble":b=
{min:a.domain.minValue,max:a.domain.maxValue}}b=new r({"class":"ee-inputField",name:a.fieldName,smallDelta:1,constraints:b,required:!0},e.create("div"))}c.push(b)}else switch(a.type){case "esriFieldTypeGUID":b=new l({"class":"ee-inputField",name:a.fieldName,required:!0,trim:!0},e.create("div"));b.validator=n.hitch(this,this.validateGUID);c.push(b);break;case "esriFieldTypeDate":b=new q({"class":"ee-inputField",name:a.fieldName,required:!0,fieldType:"date"},e.create("div"));c.push(b);a.format&&a.format.time&&
!0===a.format.time&&(a=new v({"class":"ee-inputField",style:"margin-top:2px;",required:!0},e.create("div")),c.push(a));break;case "esriFieldTypeString":b=null;a.length&&Number(a.length)&&0<Number(a.length)&&(b=a.length);if(a.hasOwnProperty("stringFieldOption"))if("richtext"===a.stringFieldOption){var h,f;h=document.getElementsByTagName("head")[0];f=window.apiUrl+"dojox/editor/plugins/resources/css/TextColor.css";m('link[href\x3d"'+f+'"]',h)[0]||g.loadStyleLink("editor_plugins_resources_TextColor",
f);f=window.apiUrl+"dojox/editor/plugins/resources/editorPlugins.css";m('link[href\x3d"'+f+'"]',h)[0]||g.loadStyleLink("editor_plugins_resources_editorPlugins",f);f=window.apiUrl+"dojox/editor/plugins/resources/css/PasteFromWord.css";m('link[href\x3d"'+f+'"]',h)[0]||g.loadStyleLink("editor_plugins_resources_PasteFromWord",f);b={"class":"ee-inputField ee-inputFieldRichText",trim:!0,maxLength:b,fieldType:"richtext",required:!0};b["class"]+=" atiRichTextField";b.height="100%";b.width="100%";b.name=a.fieldName;
b.plugins=["bold","italic","underline",g.getEditorTextColor("smartEditor"),g.getEditorBackgroundColor("smartEditor"),"|","justifyLeft","justifyCenter","justifyRight","justifyFull","|","insertOrderedList","insertUnorderedList","indent","outdent","|","createLink"];b=new w(b,e.create("div"))}else b="textarea"===a.stringFieldOption?new x({"class":"ee-inputField ee-inputFieldTextArea",name:a.fieldName,maxlength:b,fieldType:"textarea",required:!0},e.create("div")):new l({"class":"ee-inputField",name:a.fieldName,
maxlength:b,required:!0,trim:!0},e.create("div"));else b=new l({"class":"ee-inputField",name:a.fieldName,maxlength:b,required:!0,trim:!0},e.create("div"));c.push(b);break;case "esriFieldTypeSmallInteger":case "esriFieldTypeInteger":b=new p({"class":"ee-inputField",name:a.fieldName,required:!0,constraints:{places:0}},e.create("div"));c.push(b);break;case "esriFieldTypeSingle":case "esriFieldTypeDouble":b=new p({"class":"ee-inputField",name:a.fieldName,required:!0},e.create("div"));c.push(b);break;
default:b=new u({"class":"ee-unsupportField",name:a.fieldName,value:"N/A",readOnly:!0},e.create("div")),c.push(b)}return c},changeFieldToMostRestrictive:function(a,c){if(!a.hasOwnProperty("type")&&c.hasOwnProperty("type"))return c;c.length&&Number(c.length)&&0<Number(c.length)&&(a.length&&Number(a.length)?c.length<a.length&&(a.length=c.length):a.length=c.length);if(a.type===c.type)switch(c.type){case "esriFieldTypeString":a.hasOwnProperty("stringFieldOption")&&c.hasOwnProperty("stringFieldOption")&&
("richtext"===a.stringFieldOption&&"richtext"!==c.stringFieldOption?a.stringFieldOption=c.stringFieldOption:"textarea"===a.stringFieldOption&&"textbox"===c.stringFieldOption&&(a.stringFieldOption=c.stringFieldOption))}return a}}});