// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/SmartEditor/requiredFields.html":'\x3cdiv style\x3d"max-height: 445px;padding: 0 5px;"\x3e\r\n    \x3cdiv class\x3d"esriCTValuePickerHint"\x3e\r\n        ${nls.requiredFields.displayMsg}\r\n    \x3c/div\x3e\r\n    \x3cdiv style\x3d"width: 100%;" data-dojo-attach-point\x3d"fieldsDijitContainer"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/Evented dojo/_base/lang dojo/text!./requiredFields.html dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/dijit/Popup dojo/dom-construct dojo/_base/array dojo/string dojo/dom-style dojo/on dojo/dom-class dojo/dom-attr".split(" "),function(l,m,c,n,p,q,r,g,f,t,u,v,h,w){return l([q,m,p],{baseClass:"jimu-widget-smartEditor-requiredFields",templateString:n,fieldsPopup:null,nodes:[],postCreate:function(){this.nodes=[];this._createPopupContent();this._createPopUp()},
_createPopupContent:function(){f.forEach(this.requiredFieldsInfos,c.hitch(this,function(b){var a=b.alias?b.alias:b.name,k=g.create("div",{class:"esriCTFieldContainer esriCTMarginLeft15"},this.fieldsDijitContainer),e=t.substitute(this.nls.requiredFields.foundNullRecordCount,{fieldName:a,count:this.AttributesCount[b.name]});g.create("div",{innerHTML:e,class:"esriCTFieldName"},k);var d=this.presetUtils.createPresetFieldContentNode(b);this.nodes.push(d);0<d.length&&f.forEach(d,c.hitch(this,function(b){u.set(b,
"width","100%");w.set(b,"aria-label",a);b.placeAt(g.create("div",{style:"width:90%"},k));b.startup()}));d[0].hasOwnProperty("fieldType")&&-1!==["richtext","textarea"].indexOf(d[0].fieldType)&&v(d[0],"change",c.hitch(this,function(a){""===a||null===a||void 0===a?(h.add(d[0].domNode,"ee-error"),d[0].focusNode.focus()):h.remove(d[0].domNode,"ee-error")}))}))},_createPopUp:function(){this.fieldsPopup=new r({titleLabel:this.nls.requiredFields.popupTittle,width:400,maxHeight:300,autoHeight:!0,"class":this.baseClass,
content:this,buttons:[{label:this.nls.ok,id:"okButton",onClick:c.hitch(this,function(){this._validateFieldsDijits()&&(this._getRequiredFieldsEnteredvalues(),this.fieldsPopup.close())})},{label:this.nls.cancel,id:"cancelButton",classNames:["jimu-btn-vacation"],onClick:c.hitch(this,function(){this.emit("cancelButtonClicked");this.fieldsPopup.close()})}]})},_getRequiredFieldsEnteredvalues:function(){var b={};f.forEach(this.nodes,c.hitch(this,function(a){var c=a[0].name;if(a[0].hasOwnProperty("fieldType")&&
"date"===a[0].fieldType)if(1===a.length)b[c]=(new Date(a[0].getValue())).getTime();else{var e=a[0].getValue().toDateString();a=a[1].getValue().toTimeString();b[c]=(new Date(e+" "+a)).getTime()}else a[0].hasOwnProperty("fieldType")&&-1!==["richtext","textarea"].indexOf(a[0].fieldType)?(e=this.presetUtils.getFieldInfoByFieldName(this.requiredFieldsInfos,a[0].name).length,a=a[0].getValue(),a.length>e&&(a=a.slice(0,e)),b[c]=a):b[c]=a[0].getValue()}));this.emit("providedValuesToRequiredFields",b)},_validateFieldsDijits:function(){var b=
!0;f.some(this.nodes,c.hitch(this,function(a){if(a[0].hasOwnProperty("fieldType")&&-1!==["richtext","textarea"].indexOf(a[0].fieldType)){if(""===a[0].getValue()||null===a[0].getValue()||void 0===a[0].getValue())return h.add(a[0].domNode,"ee-error"),b=!1,a[0].focusNode.focus(),!0}else{if(!a[0].isValid())return b=!1,a[0].focus(),!0;if(1<a.length&&!a[1].isValid())return b=!1,a[1].focus(),!0}}));return b}})});