// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/Evented dojo dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-class dojo/on dojo/query dijit/registry jimu/filterUtils jimu/dijit/Filter jimu/BaseWidgetSetting".split(" "),function(q,r,t,p,k,c,u,m,v,w,y,x){return t([x,q],{_attrInspector:null,_fieldValidation:null,_feature:null,_fieldInfo:null,_gdbRequiredFields:null,_notEditableFields:null,_fieldNameToAlias:null,_fieldsWithRules:null,_attTable:null,_filterUtils:null,_mapLayer:null,OPERATORS:null,constructor:function(){this.inherited(arguments);
p.mixin(this,arguments[0]);String.prototype.endsWith||(String.prototype.endsWith=function(a,d){if(void 0===d||d>this.length)d=this.length;return this.substring(d-a.length,d)===a});this.useFieldName=!1;this._mapLayer=this._feature.getLayer();this._attTable=m("td.atiLabel",this._attrInspector.domNode);if(0<this._attTable.length){var a=this._attTable[0];a&&a.hasAttribute("data-fieldname")&&(this.useFieldName=!0)}this._processLayer();this._filterUtils=new w;this.OPERATORS=p.clone(this._filterUtils.OPERATORS);
void 0!==this._attTable&&null!==this._attTable&&this._bindEvents()},_processLayer:function(){this._gdbRequiredFields=[];this._notEditableFields=[];this._fieldsWithRules=[];k.forEach(this._fieldInfo,function(a){var b;!0===this.useFieldName||!1===a.hasOwnProperty("label")?b=a.fieldName:(b=a.label,0<=b.indexOf('\x3ca class\x3d"asteriskIndicator"\x3e *\x3c/a\x3e')&&(b=b.replace('\x3ca class\x3d"asteriskIndicator"\x3e *\x3c/a\x3e',"")));!1===a.nullable&&!0===a.isEditable&&this._gdbRequiredFields.push(b);
!1!==a.isEditable&&!1!==a.isEditableSettingInWebmap||this._notEditableFields.push(b);this._fieldValidation&&this._fieldValidation.hasOwnProperty(a.fieldName)&&this._fieldsWithRules.push(b)},this)},toggleFields:function(a){a="undefined"!==typeof a&&null!==a?a:!0;if(void 0!==this._attTable&&null!==this._attTable&&void 0!==this._fieldValidation&&null!==this._fieldValidation&&void 0!==this._feature&&null!==this._feature){var b=null,d=[],e;k.forEach(this._fieldInfo,p.hitch(this,function(c){var l;!0===
this.useFieldName||!1===c.hasOwnProperty("label")?l=c.fieldName:(l=c.label,0<=l.indexOf('\x3ca class\x3d"asteriskIndicator"\x3e *\x3c/a\x3e')&&(l=l.replace('\x3ca class\x3d"asteriskIndicator"\x3e *\x3c/a\x3e',"")));b=null;e=this.validateField(c.fieldName);b=e[1];if("Required"===b&&"esriFieldTypeDate"===c.type){var f=this._getDijitForField(c.fieldName);f&&1<f.length&&null===f[1].get("value")&&(e[2]=!1)}e[2]&&"esriFieldTypeDate"===c.type&&(f=this._getDijitForField(c.fieldName))&&1<f.length&&null===
f[0].get("value")&&(e[2]=!1);!1===e[2]&&d.push({fieldName:c.fieldName});!0===e[0]&&this.toggleFieldOnAttributeInspector(l,b,e[2],a)}));return d}},_getDijitForField:function(a){var b;k.some(this._attrInspector._currentLInfo.fieldInfos,p.hitch(this,function(d){if(d.fieldName===a)return b=d.dijit,!0}));return b},validateField:function(a){var b=null;if(this._fieldValidation.hasOwnProperty(a)){if(0===this._fieldValidation[a].length)return[!1,null,!0];var d=[!1,null,null];k.some(this._fieldValidation[a],
function(e){if(void 0!==e.filter&&null!==e.filter&&(b=e.filter,d=[!0,null,null],this.processFilter(b,this._feature)))return"Required"===e.actionName?!1===this._feature.attributes.hasOwnProperty(a)?(d=[!0,e.actionName,!1],!0):null===this._feature.attributes[a]||""===this._feature.attributes[a]?(d=[!0,e.actionName,!1],!0):this.myIsNaN(this._feature.attributes[a])?(d=[!0,e.actionName,!1],!0):(d=[!0,e.actionName,!0],!0):(d=[!0,e.actionName,null,e.submitWhenHidden],!0)},this);return d}return[!1,null,null]},
_bindEvents:function(){void 0!==this._attTable&&null!==this._attTable&&0<this._attTable.length&&k.forEach(this._attTable,function(a){a=this._getRowInfo(a);-1!==this._fieldsWithRules.indexOf(a[3])&&"dijit.form.FilteringSelect"===a[2].declaredClass&&u(a[2],"change",p.hitch(this,this._smartComboValidate()))},this)},process_relative_date:function(a,b,d){var e=new Date,c=this._isNumeric(b);if(void 0===a||null===a||""===a)return b;if(a==this.OPERATORS.dateOperatorMinutes&&!0===c)return e.setMinutes(e.getMinutes()-
b);if(a==this.OPERATORS.dateOperatorHours&&!0===c)return e.setHours(e.getHours()-b);if(a==this.OPERATORS.dateOperatorDays&&!0===c)return e.setDate(e.getDate()-b);if(a==this.OPERATORS.dateOperatorWeeks&&!0===c)return e.setDate(e.getDate()-7*b);if(a==this.OPERATORS.dateOperatorMonths&&!0===c)return e.setMonth(e.getMonth()-b);if(a==this.OPERATORS.dateOperatorYears&&!0===c)return e.setFullYear(e.getFullYear()-b);if("today"==a.toLowerCase())return(new Date(e.setDate(e.getDate()))).setHours(23,59,59,999);
if("tomorrow"==a.toLowerCase())return(new Date(e.setDate(e.getDate()+1))).setHours(23,59,59,999);if("yesterday"==a.toLowerCase())return(new Date(e.setDate(e.getDate()-1))).setHours(23,59,59,999);if("thisweek"==a.toLowerCase()){var g=(new Date(e.setDate(e.getDate()-e.getDay()))).setHours(0,0,0,0),f=(new Date(e.setDate(e.getDate()-e.getDay()+6))).setHours(23,59,59,999);return!0===d?g:f}if("thismonth"==a.toLowerCase())return g=(new Date(e.getFullYear(),e.getMonth(),1)).getTime(),f=(new Date(e.getFullYear(),
e.getMonth()+1,0)).setHours(23,59,59,999),!0===d?g:f;if("thisquarter"==a.toLowerCase()){a=new Date(e.getTime());var h=a.getFullYear();a.setHours(0,0,0,0);b=(new Date(h,2,31)).setHours(23,59,59,999);var c=(new Date(h,5,30)).setHours(23,59,59,999),k=(new Date(h,8,30)).setHours(23,59,59,999),h=(new Date(h,11,31)).setHours(23,59,59,999);a<=b&&(g=(new Date(e.getFullYear(),0,1)).getTime(),f=c);a<=c&&(g=b,f=c);a<=k&&(g=c,f=k);a<=h&&(g=k,f=h);return!0===d?g:f}return"thisyear"==a.toLowerCase()?(f=(new Date(e.getFullYear(),
11,31)).setHours(23,59,59,999),g=(new Date(e.getFullYear(),0,1)).getTime(),!0===d?g:f):b},process_part:function(a){var b=null,d=null,e=null,c=null,g=null,f=null;a.valueObj.hasOwnProperty("value")&&(b=void 0===a.valueObj.virtualDate||null===a.valueObj.virtualDate?null:a.valueObj.virtualDate,g=void 0===a.valueObj.range||null===a.valueObj.range?null:a.valueObj.range,d=a.valueObj.value);a.valueObj.hasOwnProperty("value1")&&(b=void 0===a.valueObj.virtualDate1||null===a.valueObj.virtualDate1?null:a.valueObj.virtualDate1,
null===b&&(b=void 0===a.valueObj.virtualDate||null===a.valueObj.virtualDate?null:a.valueObj.virtualDate),g=void 0===a.valueObj.range1||null===a.valueObj.range1?null:a.valueObj.range1,d=a.valueObj.value1);a.valueObj.hasOwnProperty("value2")&&(e=void 0===a.valueObj.virtualDate2||null===a.valueObj.virtualDate2?null:a.valueObj.virtualDate2,null===e&&(e=void 0===a.valueObj.virtualDate||null===a.valueObj.virtualDate?null:a.valueObj.virtualDate),f=void 0===a.valueObj.range2||null===a.valueObj.range2?null:
a.valueObj.range2,c=a.valueObj.value2);"esriFieldTypeDate"==a.fieldObj.type&&(a.operator==this.OPERATORS.dateOperatorInTheLast?(null!==g&&(d=this.process_relative_date(g,d)),null!==f&&(c=this.process_relative_date(f,c))):a.operator==this.OPERATORS.dateOperatorNotInTheLast?(null!==g&&(d=this.process_relative_date(g,d)),null!==f&&(c=this.process_relative_date(f,c))):a.operator==this.OPERATORS.dateOperatorIsIn?(d=this.process_relative_date(b,d,!0),c=this.process_relative_date(e,c,!1)):a.operator==this.OPERATORS.dateOperatorIsNotIn?
(d=this.process_relative_date(b,d,!0),c=this.process_relative_date(e,c,!1)):(null!==b&&(d=this.process_relative_date(b,d,!1)),null!==e&&(c=this.process_relative_date(e,c,!1))));return[d,c]},processFilter:function(a){var b=[];k.forEach(a.parts,function(a){if(a.hasOwnProperty("parts"))b.push(this.processFilter(a,this._feature));else{var d=this.process_part(a),c=d[0],d=d[1];switch(a.valueObj.type){case "value":b.push(this.validatePart(a.operator,this._feature.attributes[a.fieldObj.name],c,d,a.caseSensitive));
break;case "unique":b.push(this.validatePart(a.operator,this._feature.attributes[a.fieldObj.name],c,d,a.caseSensitive));break;case "field":this._feature.attributes.hasOwnProperty(c)&&(c=this._feature.attributes[c]),b.push(this.validatePart(a.operator,this._feature.attributes[a.fieldObj.name],c,d,a.caseSensitive))}}},this);return this.ruleValid(b,a.logicalOperator)},ruleValid:function(a,b){var d=!1;if(void 0===b||null===b)b="OR";k.some(a,function(a){if("OR"===b){if(!0===a)return d=!0;d=!1}else{if(!1===
a)return d=!1,!0;d=!0}});return d},myIsNaN:function(a){return a!==a},_isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},validatePart:function(a,b,d,c,l){var e=null;if(void 0===a||null===a)return!1;0===a.lastIndexOf("string",0)?!1===l&&(void 0!==b&&null!==b&&(b=String(b).toUpperCase()),void 0!==d&&null!==d&&(d=String(d).toUpperCase()),void 0!==c&&null!==c&&(c=String(c).toUpperCase())):0===a.lastIndexOf("date",0)&&(void 0!==d&&null!==d&&(d=new Date(d)),void 0!==c&&null!==c&&(c=new Date(c)));
switch(a){case this.OPERATORS.stringOperatorIs:if(b===d)return!0;break;case this.OPERATORS.stringOperatorIsNot:if(b!==d)return!0;break;case this.OPERATORS.stringOperatorStartsWith:if(null===b&&null===d)return!0;if(null===b&&null!==d)break;if(null!==b&&null===d)break;if(0===b.lastIndexOf(d,0))return!0;break;case this.OPERATORS.stringOperatorEndsWith:if(null===b&&null===d)return!0;if(null===b&&null!==d)break;if(null!==b&&null===d)break;return b.endsWith(d);case this.OPERATORS.stringOperatorContains:if(null===
b&&null===d)return!0;if(null===b&&null!==d)break;if(null!==b&&null===d)break;if(0<=String(b).toUpperCase().indexOf(d.toUpperCase()))return!0;break;case this.OPERATORS.stringOperatorDoesNotContain:if(null===b&&null===d)break;if(null===b&&null!==d||null!==b&&null===d||!(0<=String(b).toUpperCase().indexOf(d.toUpperCase())))return!0;break;case this.OPERATORS.stringOperatorIsBlank:return void 0===b||null===b||""===b;case this.OPERATORS.stringOperatorIsNotBlank:return void 0!==b&&null!==b&&""!==b;case this.OPERATORS.numberOperatorIs:if(this._isNumeric(b))return String(b)===
String(d);break;case this.OPERATORS.numberOperatorIsNot:if(this._isNumeric(b))return String(b)!==String(d);break;case this.OPERATORS.numberOperatorIsAtLeast:if(this._isNumeric(b)&&this._isNumeric(d))return Number(b)>=Number(d);break;case this.OPERATORS.numberOperatorIsLessThan:if(this._isNumeric(b)&&this._isNumeric(d))return Number(b)<Number(d);break;case this.OPERATORS.numberOperatorIsAtMost:if(this._isNumeric(b)&&this._isNumeric(d))return Number(b)<=Number(d);break;case this.OPERATORS.numberOperatorIsGreaterThan:if(this._isNumeric(b)&&
this._isNumeric(d))return Number(b)>Number(d);break;case this.OPERATORS.numberOperatorIsBetween:if(this._isNumeric(b)&&this._isNumeric(d)&&this._isNumeric(c))return Number(b)>Number(d)&&Number(b)<Number(c);break;case this.OPERATORS.numberOperatorIsNotBetween:if(this._isNumeric(b)&&this._isNumeric(d)&&this._isNumeric(c))return Number(b)<=Number(d)||Number(b)>=Number(c);break;case this.OPERATORS.numberOperatorIsBlank:if(null===b||void 0===b||!1===this._isNumeric(b))return!0;break;case this.OPERATORS.numberOperatorIsNotBlank:if(null!==
b&&void 0!==b&&!0===this._isNumeric(b))return!0;break;case this.OPERATORS.dateOperatorIsOn:if(void 0===b||null===b)break;if(void 0===d||null===d)break;e=new Date(b);return d.toDateString()===e.toDateString();case this.OPERATORS.dateOperatorIsNotOn:if(void 0===b||null===b)break;if(void 0===d||null===d)break;e=new Date(b);return d.toDateString()!==e.toDateString();case this.OPERATORS.dateOperatorIsBefore:if(null===b||void 0===b)break;if(void 0===d||null===d)break;return b<d.getTime();case this.OPERATORS.dateOperatorIsAfter:if(null===
b||void 0===b)break;if(void 0===d||null===d)break;return b>d.getTime();case this.OPERATORS.dateOperatorIsOnOrBefore:if(null===b||void 0===b)break;if(void 0===d||null===d)break;return b<=d.getTime();case this.OPERATORS.dateOperatorIsOnOrAfter:if(null===b||void 0===b)break;if(void 0===d||null===d)break;return b>=d.getTime();case this.OPERATORS.dateOperatorInTheLast:if(null===b||void 0===b)break;if(void 0===d||null===d)break;return b>d.getTime()&&b<=(new Date).getTime();case this.OPERATORS.dateOperatorNotInTheLast:if(null===
b||void 0===b)break;if(void 0===d||null===d)break;return b<=d.getTime()||b>=(new Date).getTime();case this.OPERATORS.dateOperatorIsIn:if(null===b||void 0===b)break;if(void 0===d||null===d)break;if(void 0===c||null===c)break;return b>=d.getTime()&&b<=c.getTime();case this.OPERATORS.dateOperatorIsNotIn:if(null===b||void 0===b)break;if(void 0===d||null===d)break;if(void 0===c||null===c)break;return b<d.getTime()||b>c.getTime();case this.OPERATORS.dateOperatorIsBetween:if(null===b||void 0===b)break;if(void 0===
d||null===d)break;if(void 0===c||null===c)break;return b>=d.getTime()&&b<=c.getTime();case this.OPERATORS.dateOperatorIsNotBetween:if(null===b||void 0===b)break;if(void 0===d||null===d)break;if(void 0===c||null===c)break;return b<d.getTime()||b>c.getTime();case this.OPERATORS.dateOperatorIsBlank:if(null===b||void 0===b)return!0;break;case this.OPERATORS.dateOperatorIsNotBlank:if(null!==b&&void 0!==b)return!0}return!1},_processChildNodes:function(a,b){a.disabled=b;!0===b?a.style&&(a.style.pointerEvents=
"none"):a.style&&(a.style.pointerEvents="auto");k.forEach(a.childNodes,function(a){a.disabled=b;!0===b?a.style&&(a.style.pointerEvents="none"):a.style&&(a.style.pointerEvents="auto");0<a.childNodes.length&&this._processChildNodes(a,b)},this)},_smartComboValidate:function(){this.toggleFields()},_getRowInfo:function(a){var b=a.parentNode.childNodes[1].childNodes[0],d=null,e=null;1<a.parentNode.childNodes[1].childNodes.length&&(d=a.parentNode.childNodes[1].childNodes[1],c.contains(d,"esriCTValuePickerButton")&&
(e=a.parentNode.childNodes[1].childNodes[1],d=null),3===a.parentNode.childNodes[1].childNodes.length&&(e=a.parentNode.childNodes[1].childNodes[2]));var l;l=!0===this.useFieldName?a.hasAttribute("data-fieldname")?a.getAttribute("data-fieldname"):a.childNodes[0].data:a.childNodes[0].data;a=a.parentNode;var g=v.getEnclosingWidget(b);return[b,a,g,l,d,e]},_removeRequireFieldMarkings:function(a,b,d){var e=null;void 0===d||null===d?(c.contains(a,"dijitComboBoxError")&&c.remove(a,"dijitComboBoxError"),c.contains(a,
"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),c.contains(a,"dijitValidationTextBox")&&c.remove(a,"dijitValidationTextBox"),c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError"),e=m(".dijitValidationContainer",b),k.forEach(e,function(a){a.parentNode.removeChild(a)})):(e=p.isFunction(d.isValid)?d.isValid():!0,"dijit.form.TextBox"===d.declaredClass&&!0===e?(c.contains(a,"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),
c.contains(a,"dijitValidationTextBox")&&c.remove(a,"dijitValidationTextBox"),c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError"),e=m(".dijitValidationContainer",b),k.forEach(e,function(a){a.parentNode.removeChild(a)})):"dijit.form.ValidationTextBox"===d.declaredClass&&!0===e?(c.contains(a,"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),c.contains(a,"dijitTextBoxDisabled")&&c.remove(a,"dijitTextBoxDisabled"),
c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError")):"dijit.form.DateTextBox"===d.declaredClass&&!0===e?(c.contains(a,"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),c.contains(a,"dijitValidationTextBox")&&c.remove(a,"dijitValidationTextBox"),c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError"),e=m(".dijitValidationContainer",
b),k.forEach(e,function(a){a.parentNode.removeChild(a)})):"dijit.form.TimeTextBox"===d.declaredClass&&!0===e?(c.contains(a,"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),c.contains(a,"dijitValidationTextBox")&&c.remove(a,"dijitValidationTextBox"),c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError"),e=m(".dijitValidationContainer",b),k.forEach(e,function(a){a.parentNode.removeChild(a)})):"dijit.form.FilteringSelect"===
d.declaredClass&&!0===e?(c.contains(a,"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),c.contains(a,"dijitComboBoxError")&&c.remove(a,"dijitComboBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError"),c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError")):!0===e&&(c.contains(a,"dijitComboBoxError")&&c.remove(a,"dijitComboBoxError"),c.contains(a,"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),c.contains(a,"dijitValidationTextBox")&&c.remove(a,"dijitValidationTextBox"),
c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError"),e=m(".dijitValidationContainer",b),k.forEach(e,function(a){a.parentNode.removeChild(a)})))},_removeRedAst:function(a,b){-1===this._gdbRequiredFields.indexOf(b)&&(a=m("a.asteriskIndicator",a),0<a.length&&k.forEach(a,function(a){a.parentNode.removeChild(a)}))},_removeHideRule:function(a){c.contains(a,"hideField")&&c.remove(a,"hideField")},_removeDisableRule:function(a,
b){-1===this._notEditableFields.indexOf(a)&&(c.contains(b,"dijitTextBoxDisabled")&&c.remove(b,"dijitTextBoxDisabled"),c.contains(b,"dijitComboBoxDisabled")&&c.remove(b,"dijitComboBoxDisabled"),c.contains(b,"dijitValidationTextBoxDisabled")&&c.remove(b,"dijitValidationTextBoxDisabled"),c.contains(b,"dijitDisabled")&&c.remove(b,"dijitDisabled"));this._processChildNodes(b,!1)},_remove:function(a,b,d,c,l){this._removeRequireFieldMarkings(d,c,l);this._removeRedAst(a[0],b);this._removeDisableRule(b,d);
this._removeHideRule(c)},toggleFieldOnAttributeInspector:function(a,b,d,e){e="undefined"!==typeof e&&null!==e?e:!0;if(void 0===this._gdbRequiredFields||null===this._gdbRequiredFields)this._gdbRequiredFields=[];if(void 0===this._notEditableFields||null===this._notEditableFields)this._notEditableFields=[];if(void 0!==this._attTable&&null!==this._attTable){if(0<this._attTable.length){var l=r.filter(this._attTable,p.hitch(this,function(b){return b.childNodes&&0<b.childNodes.length?!0===this.useFieldName?
b.hasAttribute("data-fieldname")?b.getAttribute("data-fieldname")===a:b.childNodes[0].data===a:b.childNodes[0].data===a:!1})),g=null;if(null!==l&&0<l.length){var f=this._getRowInfo(l[0]),h=f[0],g=f[4],k=f[5],n=f[1],f=f[2];if(void 0!==f&&null!==f)switch(b){case "Hide":this._removeRequireFieldMarkings(h,n,f);this._removeRedAst(l[0],a);this._removeDisableRule(a,h);g&&this._removeDisableRule(a,g);k&&c.remove(k,"disabled");c.add(n,"hideField");break;case "Disabled":this._removeRedAst(l[0],a);this._removeHideRule(n);
this._removeRequireFieldMarkings(h,n,f);c.add(h,["dijitValidationTextBox","dijitTextBoxDisabled","dijitComboBoxDisabled","dijitValidationTextBoxDisabled","dijitDisabled"]);this._processChildNodes(h,!0);null!==g&&(this._removeRequireFieldMarkings(g,n,f),c.add(g,["dijitValidationTextBox","dijitTextBoxDisabled","dijitComboBoxDisabled","dijitValidationTextBoxDisabled","dijitDisabled"]),this._processChildNodes(g,!0));k&&c.add(k,"disabled");break;case "Required":this._removeDisableRule(a,h);g&&this._removeDisableRule(a,
g);k&&c.remove(k,"disabled");this._removeHideRule(n);!0===d?(this._removeRequireFieldMarkings(h,n,f),g&&c.contains(g,"dijitTextBoxError","dijitError")&&c.remove(g,"dijitTextBoxError","dijitError")):"dijit.form.TextBox"===f.declaredClass?(g=m(".dijitValidationContainer",n),0===g.length&&(b=document.createElement("div"),b.setAttribute("class","dijitReset dijitValidationContainer"),d=document.createElement("input"),d.setAttribute("class","dijitReset dijitInputField dijitValidationIcon dijitValidationInner"),
d.setAttribute("value","x"),d.setAttribute("type","text"),d.setAttribute("tabindex","-1"),d.setAttribute("readonly","readonly"),d.setAttribute("role","presentation"),b.appendChild(d),h.insertBefore(b,h.childNodes[0])),c.add(h,["dijitTextBoxError","dijitValidationTextBox","dijitValidationTextBoxError","dijitError"])):"dijit.form.ValidationTextBox"===f.declaredClass?(g=m(".dijitValidationContainer",n),c.add(h,["dijitTextBoxError","dijitValidationTextBox","dijitValidationTextBoxError","dijitError"])):
"dijit.form.FilteringSelect"===f.declaredClass?c.add(h,["dijitTextBoxError","dijitComboBoxError","dijitError","dijitValidationTextBoxError"]):f.get("value")?(c.remove(h,"dijitTextBoxError","dijitError"),g&&c.add(g,["dijitTextBoxError","dijitError"])):c.add(h,["dijitTextBoxError","dijitError"]);h=m("a.asteriskIndicator",l[0]);b=m("span.atiRequiredField",l[0]);-1===this._gdbRequiredFields.indexOf(a)&&0===h.length&&0===b.length&&(h=document.createElement("a"),h.setAttribute("class","asteriskIndicator"),
h.innerHTML=" *",l[0].appendChild(h));break;case "Value":break;default:e&&(this._remove(l,a,h,n,f),k&&c.remove(k,"disabled"),g&&this._removeDisableRule(a,g))}}}this.emit("onFieldToggle")}}})});