// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/_base/html dojo/on dojo/aspect dojo/keys dijit/focus dojo/topic dojo/string jimu/utils jimu/LayoutManager".split(" "),function(t,n,e,l,c,u,f,m,q,r,d,v){return t(null,{_layoutManager:null,_focusedTab:null,focusToDisplay:!1,hasBeenActivated:!1,postCreate:function(){this.inherited(arguments);this._layoutManager=v.getInstance();this.focusToDisplay=!0;this.hasBeenActivated=this.config.initiallyExpand;this.own(c(this.domNode,"keydown",e.hitch(this,
function(a){l.hasClass(a.target,this.baseClass)&&a.keyCode===f.ENTER&&(this.focusToDisplay=!1,this.hasBeenActivated=!0,this.showing||(this.widgetManager.activateWidget(this),this._switchTable()))})));this.own(c(this.domNode,"focus",e.hitch(this,function(){d.isInNavMode()&&this.focusToDisplay&&!this.showing&&(this.widgetManager.activateWidget(this),this._switchTable())})));this.own(c(this.domNode,"blur",e.hitch(this,function(){d.isInNavMode()&&this.focusToDisplay&&this.showing&&(this.hasBeenActivated||
this._switchTable());this.focusToDisplay=!0;this.showing||(this.hasBeenActivated=!1)})));this.own(q.subscribe(this.id+"_table_created",e.hitch(this,function(a){this._applyA11y2Grid(a&&a.grid,a&&a.context)})),q.subscribe(this.id+"_toolbar_created",e.hitch(this,function(a){this._applyA11y2Toolbar(a&&a.toolbar,a&&a.context)})))},applyA11y:function(){this._isOnlyTable()&&l.removeAttr(this.domNode,"tabindex");this.switchBtn&&this.own(c(this.switchBtn,"keydown",e.hitch(this,function(a){a.keyCode===f.ENTER&&
(this._switchTable(),this.focusToDisplay=this.showing,this.__focus2WidgetNode())})));this.tabContainer&&this.tabContainer.hasChildren()?this._applyA11y2TabContainer(this.tabContainer):this.NoTableMessageDiv&&(l.setAttr(this.NoTableMessageDiv,{tabindex:"0"}),d.initFirstFocusNode(this.domNode,this.NoTableMessageDiv),d.initLastFocusNode(this.domNode,this.NoTableMessageDiv),this.own(c(this.NoTableMessageDiv,"keydown",e.hitch(this,function(a){a.keyCode===f.ESCAPE&&this.__escape2WidgetSwitch(a)}))),this._isOnlyTable()&&
m.focus(this.NoTableMessageDiv))},_applyA11y2TabContainer:function(a){if(a){var b=this,h=function(g){g&&(n.forEach(a.tablist.getChildren(),function(a){!a.active&&a.closeButton&&a.id!==g.id&&l.setAttr(a.closeNode,"tabindex",-1)}),l.setAttr(g.closeNode,"tabindex",0))},p=a.tablist.onkeydown;a.tablist.onkeydown=function(a,w){var h=null,e=!1;switch(a.keyCode){case f.LEFT_ARROW:case f.UP_ARROW:a._djpage||(h=!1);break;case f.PAGE_UP:a.ctrlKey&&(h=!1);break;case f.RIGHT_ARROW:case f.DOWN_ARROW:a._djpage||
(h=!0);break;case f.PAGE_DOWN:a.ctrlKey&&(h=!0);break;case f.HOME:for(var g=this.getChildren(),d=0;d<g.length;d++){var c=g[d];if(!c.disabled){m.focus(c.focusNode);b._focusedTab=c;break}}a.stopPropagation();a.preventDefault();break;case f.END:g=this.getChildren();for(d=g.length-1;0<=d;d--)if(c=g[d],!c.disabled){m.focus(c.focusNode);b._focusedTab=c;break}a.stopPropagation();a.preventDefault();break;case f.DELETE:case 87:this._currentChild.closable&&(a.keyCode==f.DELETE||a.ctrlKey)&&(a.stopPropagation(),
a.preventDefault());break;case f.ENTER:case f.SPACE:b.tabForwardStep=0;break;case f.ESCAPE:"Close"===a.target.title?b._focusedTab&&m.focus(b._focusedTab.focusNode):b.__escape2WidgetSwitch(a);a.stopPropagation();a.preventDefault();break;case f.TAB:if(b.isLoading()){a.stopPropagation();a.preventDefault();return}break;default:e=!0}if(null!==h){this.isLeftToRight()||this.tabPosition&&!/top|bottom/.test(this.tabPosition)||(h=!h);var g=this.getChildren(),d=n.indexOf(g,this.pane2button(b._focusedTab?b._focusedTab.page&&
b._focusedTab.page.id:this._currentChild.id)),c=g[d],k;do d=(d+(h?1:g.length-1))%g.length,k=g[d];while(k.disabled&&k!==c);b._focusedTab=k;m.focus(b._focusedTab.focusNode);a.stopPropagation();a.preventDefault()}e&&p.apply(this,arguments)};if(a.hasChildren()){n.forEach(a.getChildren(),e.hitch(this,function(a){a.controlButton.checked||l.setAttr(a.controlButton.focusNode,"aria-selected","false");a.closable&&l.setAttr(a.controlButton.closeNode,"role","button")}));var k=a.tablist.getChildren()[0];this._focusedTab=
k;d.initFirstFocusNode(this.domNode,k.focusNode);k.closeNode&&h(k);!this._isOnlyTable()||"LaunchpadTheme"!==this.appConfig.theme.name&&"BillboardTheme"!==this.appConfig.theme.name||m.focus(k.focusNode)}this.own(u.after(a,"selectChild",function(){var a=e.getObject("controlButton",!1,this.selectedChildWidget);a&&(d.initFirstFocusNode(b.domNode,a.focusNode),a.closeNode&&h(a));b._focusedTab=a}),c(a.tablist,"blur",e.hitch(this,function(){this._focusedTab=null})))}},_applyA11y2Toolbar:function(a,b){a&&
(e.mixin(a,{_onLeftArrow:function(){},_onRightArrow:function(){}}),this.own(c(a,"keydown",e.hitch(this,function(b){if(b.keyCode===f.TAB){if(b.shiftKey){if(b.target.id===a._getFirstFocusableChild().id)return}else if(b.target.id===a._getLastFocusableChild().id)return;b.shiftKey?a.focusPrev():a.focusNext();b.stopPropagation();b.preventDefault()}else b.keyCode===f.ESCAPE&&this.__escape2ActiveTab(b)}))),b&&b.toggleColumnsMenuItem&&this.own(c(b.toggleColumnsMenuItem,"click",e.hitch(this,function(a){d.isInNavMode()&&
this.__applyA11y2GridHiderMenu(this._activeTable&&this._activeTable.grid)}))))},_applyA11y2Grid:function(a,b){if(a&&a.hiderToggleNode&&a.hiderMenuNode){var h=a.hiderToggleNode,p=a.hiderMenuNode;d.initLastFocusNode(this.domNode,h);if(!a._customEvtHandlersInitialized){var k=b.id+"_ScreenReader_Node",g=l.create("div",{"class":"sr-only","aria-live":"assertive",id:k},b.footer,"after");this.own(c(b,"row-click",function(a){d.isInNavMode()&&(g.textContent=a.selectedIds.length+" "+this.nls.selected)}),c(b,
"clear-selection",function(){d.isInNavMode()&&(g.textContent="")}),c(a,"keydown",e.hitch(this,function(a){d.isInNavMode()&&a.keyCode===f.ESCAPE&&(g.textContent="",this.__escape2ActiveTab(a))})),m.watch("curNode",e.hitch(this,function(b,h,c){d.isInNavMode()&&c&&c.classList&&c.classList.contains("dgrid-column-selectionHandle")&&(b=-1,a.selection&&0===Object.keys(a.selection).length&&(b=this.__IndexOfGridRowHandle(c,a),-1<b&&(g.textContent="Row "+b+", Selection Handle.",c.setAttribute("aria-labelledby",
k))))})),c(a,"dgrid-select",e.hitch(this,function(b){b=m.curNode;if(d.isInNavMode()&&b&&b.classList&&b.classList.contains("dgrid-column-selectionHandle")){var c=(a.selection&&Object.keys(a.selection)).length,h=-1;0<c&&b&&(h=this.__IndexOfGridRowHandle(b,a),-1<h&&(g.textContent=1===c?r.substitute(this.nls.rowHeaderColumnTitle,{rowId:h}):r.substitute(this.nls.rowHeaderColumnTitleMultiple,{rowId:h,rowCount:c}),b.setAttribute("aria-labelledby",k)))}})),c(h,"keydown",e.hitch(this,function(b){if(b.keyCode===
f.SPACE||b.keyCode===f.ENTER)a._toggleColumnHiderMenu(),this.__applyA11y2GridHiderMenu(a),b.stopPropagation(),b.preventDefault()})),c(p,"keydown",e.hitch(this,function(b){b.keyCode===f.ESCAPE&&(h.focus(),a._hiderMenuOpened&&a._toggleColumnHiderMenu(b),b.stopPropagation(),b.preventDefault())})));a._customEvtHandlersInitialized=!0}this._focusedTab&&this._focusedTab.checked&&b&&l.setAttr(this._focusedTab.focusNode,"aria-labelledby",this._focusedTab.focusNode.id+" "+this.id+"_"+b.id+"_footer")}},__escape2WidgetSwitch:function(a){this.switchBtn?
this.switchBtn.focus():d.isDomFocusable(this.domNode)?this.__focus2WidgetNode():this._controllerDiv&&this._controllerDiv.focus();if(this.closeable&&this._isOnlyTable()&&this.widgetManager){var b;n.some(this._layoutManager&&this._layoutManager.layoutManager&&this._layoutManager.layoutManager.onScreenWidgetIcons,e.hitch(this,function(a){if(a&&a.widgetConfig&&a.widgetConfig.id===this.id)return b=a,!0}));b?b.domNode.focus():this.widgetManager.closeWidget(this)}a&&(a.stopPropagation(),a.preventDefault())},
__focus2WidgetNode:function(){this.domNode.focus()},__escape2ActiveTab:function(a){d.focusFirstFocusNode(this.domNode);a&&(a.stopPropagation(),a.preventDefault())},__applyA11y2GridHiderMenu:function(a){if(a&&a._hiderMenuOpened&&(a=a.hiderMenuNode,a.children&&0<a.children.length)){var b=a.children[0],c=a.children[a.children.length-1],e=b.querySelector("input");d.initFirstFocusNode(a,b.querySelector("input"));d.initLastFocusNode(a,c.querySelector("input"));e&&e.focus()}},__focusOnActiveTab:function(){setTimeout(e.hitch(this,
function(){d.focusFirstFocusNode(this.domNode)}),600)},__IndexOfGridRowHandle:function(a,b){var c;b=b.domNode.querySelectorAll(".dgrid-column-selectionHandle");n.some(b,function(b,d){if(b.isEqualNode(a))return console.log(d),c=d,!0});return c}})});